### ISSUE TITLE
Frequent failing test: contract-empty-implicit-account-into-new-implicit-account.spec.ts

### ISSUE THREAD

**Issue by roxaneletourneau** [ecadlabs/taquito#1047]
**Description**
The integration test `contract-empty-implicit-account-into-new-implicit-account.spec.ts`  frequently fails on Granadanet with a ` Confirmation polling timed out` error.

As stated in the [issue 496](https://github.com/ecadlabs/taquito/issues/496), 

> the cost of emptying an account has increased in Delphinet. The transaction to empty the account succeeds when increasing the gas limit. 

However now on Granadanet, it seems like the fees are too low compared to this increased gas limit, and thus, the operation is not included (which leads to the timeout error).

We can increase the fee to have the transaction included, but a proper investigation needs to be conducted on this issue.

**Comment by michaelkernaghan** [comment]
I think this test is stable now. I cannot replicate the flaky behaviour running it locally. I am closing the issue.

**Comment by roxaneletourneau** [comment]
Temporary fix, see https://gitlab.com/tezos/tezos/-/issues/1754
