### ISSUE TITLE
Fetch missed block instead of throwing MissedBlockDuringConfirmationError

### ISSUE THREAD

**Issue by roxaneletourneau** [ecadlabs/taquito#1050]
**Is your feature request related to a problem and use case? Please describe.**
A clear and concise description of what the problem/use case is. 
On the `confirmation` method of the wallet API, a `MissedBlockDuringConfirmationError` error is thrown if a block is missed during polling:
https://github.com/ecadlabs/taquito/blob/master/packages/taquito/src/wallet/operation.ts#L42

**Describe the solution you'd like**
A clear and concise description of what you'd want to happen.
It would be more convivial to fetch this missed block instead of throwing an exception.

**Comment by michaelkernaghan** [comment]
We see on some dapps the message "Taquito missed a block", mostly Paul.

see:  https://files.slack.com/files-pri/T5NR47ECV-F02NB3BABJB/image.png

**Comment by claudebarde** [comment]
This also happens from time to time on MyTezosDefi
<img width="1025" alt="Screenshot 2021-11-28 at 13 04 58" src="https://user-images.githubusercontent.com/25201109/143889089-9a34f841-50d9-4ddd-a4c2-1dfef5e24c97.png">

**Comment by danielelisi** [comment]
The current polling implementation faces an important limitation. There is a high chance of throwing `MissedBlockDuringConfirmationError` exception when using Taquito with chains that produce blocks every 4 seconds or less.

I'm running Taquito integration tests against a Tezos sandbox network with `minimal_block_delay` set to 1 second. I've added additional logging to the polling function to echo the last checked block level and the new block that Taquito fetches; More often than not, Taquito misses about 6 blocks as shown in the example below. 

```
newHead: 12694 lastHead: 12688
newHead: 12707 lastHead: 12701
```

```
Summary of all failing tests
 FAIL  ./wallet-api.spec.ts (32.592 s)
  ● Test wallet api using: http://localhost:8732 › Test simple origination and wait for confirmation using promise

    MissedBlockDuringConfirmationError: newHead: 12694 lastHead: 12688 Taquito missed a block while waiting for operation confirmation and was not able to find the operation. 

      1322 |                     this.lastHead &&
      1323 |                     newHead.header.level - this.lastHead.header.level > 1) {
    > 1324 |                     throw new MissedBlockDuringConfirmationError(newHead.header.level, this.lastHead.header.level);
           |                           ^
      1325 |                 }
      1326 |                 this.lastHead = newHead;
      1327 |             }), operators.shareReplay({ bufferSize: 1, refCount: true }));


  ● Test wallet api using: http://localhost:8732 › Test simple origination and wait for confirmation using observable

    MissedBlockDuringConfirmationError: newHead: 12707 lastHead: 12701 Taquito missed a block while waiting for operation confirmation and was not able to find the operation. 

      1322 |                     this.lastHead &&
      1323 |                     newHead.header.level - this.lastHead.header.level > 1) {
    > 1324 |                     throw new MissedBlockDuringConfirmationError(newHead.header.level, this.lastHead.header.level);
           |                           ^
      1325 |                 }
      1326 |                 this.lastHead = newHead;
      1327 |             }), operators.shareReplay({ bufferSize: 1, refCount: true }));
```

**Comment by roxaneletourneau** [comment]
@danielelisi Can you confirm what was the `pollingIntervalMilliseconds` used? 

I ran the integration tests suite against a Tezos sandbox network with minimal_block_delay set to 1 second. I configured the TezosToolkit with a low polling interval (100 milliseconds). Most of the tests were successful. I got one test failing with `MissedBlockDuringConfirmationError` and another with `Timeout - Async callback was not invoked within the 600000 ms timeout specified by jest.setTimeout.Timeout`. (The other failures were related to breaking changes because the sandbox was running the Alpha protocol.)
