### ISSUE TITLE
Teams Building logos fixes on website

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taquito#1068]
- [x] Fix the distorted tezos taquito website section "Teams Building on Tezos"
- [x] Fix the broken logo for plenty
![image](https://user-images.githubusercontent.com/1114943/134721638-4ba930f6-878d-460d-80ca-48db13be73ab.png)
- [ ] Add more:
   - see logos for apps from DAppradar research are here: https://drive.google.com/drive/u/0/folders/1vgnUPul0p8G-Xfh5fDNA3wx7auQY9vNF?ths=true

**Comment by michaelkernaghan** [comment]
The first two items are verified as completed. The adding more is to be done. Need access to the spreadsheet.

**Comment by michaelkernaghan** [comment]
Closing as it looks fine now.
