### ISSUE TITLE
Error from HttpBackend has no request info

### ISSUE THREAD

**Issue by psmolinsky** [ecadlabs/taquito#1091]
`HttpBackend` throws generic `Error` in case of timeout or when unable to parse the response. This error contains no info about the request. Example: `Request timed out after: 30000ms`. This error is not handled by upper layer and bubbles up to client code. Therefore it is hard to diagnose.

**Describe the solution you'd like**
Error message contains request URL, maybe also method.

**Comment by dsawali** [comment]
Picking this up in 12.1 since it's related to #160

**Comment by psmolinsky** [comment]
Hi guys, I think this issue still persists. The latest taquito just wraps an error from *axios* and it ends up like this:
```
HttpRequestFailed: Error: timeout of 10ms exceeded
    at HttpBackend.<anonymous> ...
```

So still no info about the actual request. Can you fix it please?

**Comment by hui-an-yang** [comment]
Hi @psmolinsky 

We are taking care of this issue. This is a screenshot of what the error will look like added url and method property. Can you let me know if this will fix what you are asking?

<img width="1124" alt="image" src="https://user-images.githubusercontent.com/106410553/184755379-09c66002-cc31-4637-9047-790da4069e20.png">

**Comment by psmolinsky** [comment]
Hi @hui-an-yang, thanks for the improvement. From my point of view, it would be the best to include the details in message itself so that simple `error.toString()` contains them. Properties (like `url`, `method`) are usable in the code if someone wants to check them. What do you think?

So suggested `Error.message`:

```
Http request POST http://mainnet.api.tez.it/chains/main/blocks/head/helpers/baking_rights?level=0 failed: Error: timeout of 1ms exceeded.
```

**Comment by hui-an-yang** [comment]
Hi @psmolinsky
