### ISSUE TITLE
Allow to set HttpBackend on IpfsHttpHandler

### ISSUE THREAD

**Issue by psmolinsky** [ecadlabs/taquito#1092]
Is there a reason why there is no way how to set `HttpBackend` on `IpfsHttpHandler`? Similar `HttpHandler` has a public setter. Can you please expose it? It is useful if a consumers wants to add custom logic HTTP logic e.g. logging, retry...

**Comment by roxaneletourneau** [comment]
Thanks for pointing this, we will provide a way to set the HttpBackend for the IpfsHttpHandler.
