### ISSUE TITLE
CommonJS module loading causes rollup.js to break

### ISSUE THREAD

**Issue by benjtinsley** [ecadlabs/taquito#1098]
**Description**
There is a bit of mixing of CommonJS module loading (`require`) and ES Module loading (`import`) in the [taquito-rpc utils](https://github.com/ecadlabs/taquito/blob/master/packages/taquito-rpc/src/utils/utils.ts#L1-L3) which causes rollup.js to break when trying to load both.

It appears that ESM imports are used universally across the project for dependencies, so it may be best to update these to match the pattern elsewhere.

**Steps To Reproduce**
1. Install an app bundler that uses rollup (snowpack/vite/etc)
2. Follow the [Beacon "First dApp" instructions](https://docs.walletbeacon.io/getting-started/first-dapp/) with the Taquito settings
3. When you go to run the app, it won't work in the browser

**Expected behavior**

**Screenshots**
It fails silently but can be seen as an error in the browser console:
<img width="407" alt="Screen Shot 2021-10-06 at 4 57 55 PM" src="https://user-images.githubusercontent.com/3211091/136289682-2da9f526-1851-419c-8154-8eb302c5c53f.png">

**Desktop (please complete the following information):**
 - OS: MacOS 11.4
 - Browser: Firefox
 - Version 92

**Comment by faragos** [comment]
I had the same problem. Maybe the solution in this ticket works for you https://github.com/ecadlabs/taquito/issues/491 😃
