### ISSUE TITLE
Error when setting the initial storage with annotation for a contract to be originated

### ISSUE THREAD

**Issue by claudebarde** [ecadlabs/taquito#1101]
When trying to originate [this contract](https://better-call.dev/granadanet/KT1T836HqhBu9waqmknStVDCXu2WogZtzsNz/operations) using Taquito, the expected formatting for pairs doesn't work: `complex` is a pair of type `(pair nat string)` whose fields are not annotated. One would expect the pair to be rendered as an array (`[1, "test"]`) or an object (`{ 0: 1, 1: "test" }`) but it doesn't work and produce an error.
`ExtractSchema` returns the following:
```
{
  "simple": "int",
  "complex": {
    "1": "nat",
    "2": "string"
  },
  "optional": {
    "2": {
      "int": "int",
      "string": "string"
    },
    "3": {
      "int": "int",
      "string": "string"
    }
  },
  "last_checked_sig": {
    "msg": "bytes",
    "sender": "address",
    "sig_": "signature"
  }
}
```

**Comment by michaelkernaghan** [comment]
The link to the contract no longer works as BCD does not host granadanet anymore. It is available here: https://granadanet.tzkt.io/KT1T836HqhBu9waqmknStVDCXu2WogZtzsNz/code

**Comment by michaelkernaghan** [comment]
The contract exists on Hangzhounet: https://better-call.dev/hangzhou2net/KT1T2gL26SwYMxpkR5SZT1pHRBF84knfw8Cg/operations (

**Comment by michaelkernaghan** [comment]
the workaround was to add annotations, but the bug is about the behaviour when there are no annotations.

**Comment by roxaneletourneau** [comment]
The indexes returned by the extractSchema method were wrong. They did not match what was expected by the encodeObject method. It should have been:
```
...
"optional": {
    "3": {
      "int": "int",
      "string": "string"
    },
    "4": {
      "int": "int",
      "string": "string"
    }
  }
...
```
