### ISSUE TITLE
Abstraction to execute contract views

### ISSUE THREAD

**Issue by roxaneletourneau** [ecadlabs/taquito#1117]
**Is your feature request related to a problem and use case? Please describe.**
We want to provide a new feature on the ContractAbstraction class that will allow users to execute the new views proposed in the Hangzhou protocol.

**Describe the solution you'd like**
The user creates an instance of ContractAbstraction using the `at` method of the Contract or Wallet API. The `contractViews` member of the `ContractAbstraction` instance is dynamically populated with methods that match the on-chain view names. _`contractViews` is an object where the key is the view name, and the value is a function that returns an instance of the OnChainView class._
The view parameter is expected in the JS object format and not as flattened arguments.
_Note for reference, the flattened arguments are the expected format when calling a contract entrypoint using the methods member, but we plan to move away from this format and favor the object one (see the methodsObject vs methods members of the ContractAbstraction)._
A method named `getSignature` on the `OnChainView` class allows inspecting the parameter and the returned type of the view. The `executeView` method of the `OnChainView` class allows simulating the view. It takes as a parameter a viewCaller which represents the contract address which is the caller of the view and an optional source which is the public key hash of the account that initialized this view execution.

Here is an example where a contract script contains an on-chain view called fib:
```
const contract = await Tezos.contract.at('KT1...');
contract.contractViews.fib().getSignature();
// getSignature returns: { parameter: 'nat', result: 'nat' }
await contract.contractViews.fib(10).executeView({ viewCaller: 'KT1... });
// executeView returns the BigNumber 55
```

The implementation to execute the view can be very similar to the Michelson view from the tzip16 package.

**Note: on-chain view should not be confused with the tzip4 views which are represented by ContractAbstraction.views.**

**Comment by roxaneletourneau** [comment]
The feature is ready, but needs to be documented on the website.

**Comment by 852Kerfunkle** [comment]
Again, works great, thank you.

On a slightly rambly side note, before you added support for on-chain views I tried to figure out how to do it and I was surprised there isn't a dedicated rpc endpoint for them. It feels like there should be and it would certainly be nice to have (in terms of the complexity involved in using run_code).

**Comment by roxaneletourneau** [comment]
Thank you @852Kerfunkle !

I was confused at first because actually there is a new RPC [/helpers/scripts/run_view](https://gitlab.com/tezos/tezos/-/blob/master/docs/api/hangzhou-openapi.json), but it is intended to simulate the [tzip4 views](http://localhost:3000/docs/lambda_view) and not those "hangzhou" on-chain views. Thought to share in case you come across this RPC as well.
I haven't found an easier method than using run_code to simulate the on-chain views.
