### ISSUE TITLE
Migrate supported companion DApps to Hangzhou: Svelte Boilerplate dApp

### ISSUE THREAD

**Issue by Innkst** [ecadlabs/taquito#1120]
- [x] Boilerplate dapp - same functionality to the svelte app as react has now

cloney.tezostaquito.io. We are rewriting cloney, so this is a separate task

**Comment by claudebarde** [comment]
Double-checked that the [dapp](https://github.com/ecadlabs/taquito-svelte-template) is connected to Hangzhounet
