### ISSUE TITLE
Add a "dApp pre-launch check list" to website documentation

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taquito#1135]
As a Tezos dApp developer I would like to have a list of best practice/recommendations to implement in my dApp that uses Taquito so that users of my dApp can have a performant, safe and reliable dApp experience.

**Describe the solution you'd like**

Create a new website page listing best practices, the trade-offs on various practices, and the reasoning for the practice.

See https://hackmd.io/5t0E9fogQFuYNrr6Xr_BOw for draft material.

**Comment by claudebarde** [comment]
Pull request created: https://github.com/ecadlabs/taquito/pull/1151
