### ISSUE TITLE
Follow-up work for flextesa setup for keygen - 3

### ISSUE THREAD

**Issue by kjaiswal** [ecadlabs/taquito#1144]
Please create a new PR with changes for flextesa workflow in taquito file. Flextesa related changes are in `repository: kjaiswal/tezos-key-gen-api` Once keygen changes are merged in master and initial PR-115 is merged to master, please change flextesa workflow file to checkout master branch of keygen to run integration tests instead of local branch.

**Comment by Innkst** [comment]
no longer relevant
