### ISSUE TITLE
A README is required for the Key-gen-api : https://github.com/ecadlabs/tezos-key-gen-api

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taquito#1149]
**Description**
The key-gen-api project is Public so it should have a README.

**Steps To Reproduce**
1. Go to ' https://github.com/ecadlabs/tezos-key-gen-api'
2. There is no readme

**Expected behavior**
There should be a Readme

**Comment by roxaneletourneau** [comment]
Can this issue be opened in the keygen repo instead?

**Comment by michaelkernaghan** [comment]
ok

**Comment by michaelkernaghan** [comment]
ok, moving the issue to key gen repo
