### ISSUE TITLE
Readme is needed for Taquito Metadata Explorer

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taquito#1150]
Description
The Taquito metadata explorer project is Public so it should have a README.

Steps To Reproduce

Go to ' https://github.com/ecadlabs/taquito-metadata-explorer'
There is no detail in the readme
Expected behavior
There should be a Readme with explanation of the software and who wants it for what

**Comment by roxaneletourneau** [comment]
Can this issue be opened in the metadata-explore repo instead?

**Comment by michaelkernaghan** [comment]
ok
