### ISSUE TITLE
"Taquito" logo in README unreadable when GitHub dark mode is enabled

### ISSUE THREAD

**Issue by curiousleo** [ecadlabs/taquito#1161]
**Description**
The "Taquito" logo in the project README unreadable on GitHub when dark mode is enabled.

**Steps To Reproduce**
1. Go to https://github.com/settings/appearance and select the "Default dark" theme
2. Go to https://github.com/ecadlabs/taquito#readme

**Expected behavior**
The "Taquito" logo should be readable.

**Screenshots**
![image](https://user-images.githubusercontent.com/697092/140965717-21f57a4c-52d8-4df4-84d3-639fc582598a.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: surely doesn't matter :)

**Comment by claudebarde** [comment]
This issue is now fixed.
