### ISSUE TITLE
Cannot originate contract with `UNPAIR n` instruction

### ISSUE THREAD

**Issue by guillaumeduhamel** [ecadlabs/taquito#1171]
**Description**

Since edo, `UNPAIR` is not a macro anymore, especially `UNPAIR n`.
So, when I want to originate a contract with this instruction, the parser 
should not throw this exception :
```
macro UNPAIR expects 0 arguments, was given 1
```

source:
https://tezos.gitlab.io/protocols/008_edo.html#comb-pairs
and
https://tezos.gitlab.io/michelson-reference/#instr-UNPAIRN (list only instructions)

for example, this contract below, cannot be originated with taquito, because of `UNPAIR 6`
https://better-call.dev/hangzhou2net/KT1Jia3BfXwWhhZBBLibxwz61SFo8rYDFj2d/code
```
# (Pair 0 (Pair "" (Pair 0 (Pair 0x00 (Pair 1 0)))))
{
  storage (pair (nat %u) (pair (string %v) (pair (int %w) (pair (bytes %x) (pair (nat %y) (nat %z))))));
  parameter (unit %exec);
  code { UNPAIR;
         DIP { UNPAIR 6 };
         DROP;
         DUP 5;
         DUP 5;
         SIZE;
         DUP 3;
         DUP 5;
         SIZE;
         ADD;
         ADD;
         ADD;
         DIP { DIG 5; DROP };
         DUG 5;
         PAIR 6;
         NIL operation;
         PAIR };
}
```

Best regards,

**Comment by jevonearth** [comment]
Thank you for the report @guillaumeduhamel 

Can you tell us what version of Taquito you are using, and more importantly, what's the Tezos protocol hash you are working with? Are you testing on a testnet, or in a sandbox? 

You can find the protocol hash by querying your node with `curl` and `jq` like this: `curl localhost:8732/chains/main/blocks/head | jq '.protocol'`

**Comment by guillaumeduhamel** [comment]
Hi @jevonearth ,
thank you for your answer,
we use taquito 10.2.1 version, on the testnet hangzhounet 2 with `PtHangz2aRngywmSRGGvrcTyMbbdpWdpFKuS4uMWxg2RaH9i1qx` protocol

**Comment by jevonearth** [comment]
Can you re-try your scenario with version `@taquito/taquito@11.0.0-beta-RC.0` ?

If you are using multiple taquito npm packages in your project, make sure they all are the same version.

**Comment by guillaumeduhamel** [comment]
It works fine !
Thank you very much,
(here is a contract deployed with this version of taquito https://better-call.dev/hangzhou2net/KT1SQX7X1r2WGePJbg66gysNcedY8xk2LhYQ/operations)

**Comment by jevonearth** [comment]
Great. We will close this issue now, but I will create a follow up issue, as I think we can improve handling of the protocol hash so you would be less likely to get stuck on an issue like this.

**Comment by mattou78400** [comment]
Hello

I'm getting the same issue on better-call.dev

![image](https://user-images.githubusercontent.com/39678117/144864671-90763dec-980f-4094-84b0-7a8261f7b70d.png)


I keep getting this error when trying to fork this contract on hagzhounet

It worked perfectly on granadanet before… anyone knows what’s going on?

https://better-call.dev/mainnet/KT1JMi5Jg3GX237rgpcsvCNftHtMJpwxuASD/fork


thanks!

**Comment by claudebarde** [comment]
Which version of Taquito are you using?

**Comment by mattou78400** [comment]
None, this is happening when trying to fork a SC directly on better-call.dev with my temple wallet

**Comment by claudebarde** [comment]
Then it's possible that BCD uses an older version of Taquito, which is the source of the error.
