### ISSUE TITLE
Unidentified lambda contract for hangzhounet

### ISSUE THREAD

**Issue by akwodkiewicz** [ecadlabs/taquito#1189]
**Description**
I started using https://hangzhounet.smartpy.io/ RPC node.

When calling `balance_of(...).read()` for a contract I get the following error:
```
UndefinedLambdaContractError {
  name: 'Undefined LambdaContract error',
  message: 'This might happen if you are using a sandbox. Please provide the address of a lambda contract as a parameter of the read method.'
}
```

This is the called URL when creating a contract:
https://hangzhounet.smartpy.io/chains/main/blocks/head/context/contracts/KT1StBf222xBLfLTChsute8F9HSt9kVHpqdY/script

**Comment by jevonearth** [comment]
Hello @akwodkiewicz,

Can you tell us which version of Taquito your are using please? We recommend you use `@taquito/taquito@11.0.1` which has full `hanzhounet` support.

**Comment by akwodkiewicz** [comment]
>Can you tell us which version of Taquito your are using please? 

`@taquito/taquito@10.2.1`

I'll upgrade and let you know if it helped.

**Comment by akwodkiewicz** [comment]
Yes, upgrading to `@taquito/taquito11.0.1` worked!
Initially I got the `UnconfiguredSignerError` (which was not thrown before), but after setting the required signer the `read()` call worked.
