### ISSUE TITLE
Angular cli missing node dependency

### ISSUE THREAD

**Issue by carte7000** [ecadlabs/taquito#119]

**Comment by carte7000** [comment]
Might be related to https://github.com/ethereum/web3.js/issues/2260

**Comment by joshstevens19** [comment]
https://github.com/ethereum/web3.js/issues/3018#issuecomment-541328326 << to fix your angular app not running with web3 if your using 1.x.x

**Comment by jevonearth** [comment]
Thank you @joshstevens19   
I think we implemented the same fix, and it got merged yesterday on #140 It's on master, but not in a release yet.

Hopefully, we will be able to remove this patching when a final solution is implemented for ethereum/web3.js#3018

**Comment by joshstevens19** [comment]
Sorry I accidentally removed your comment. Yes web3 itself should do this for you I created the script in 2.0 but will get it in 1.0 for you so you can then delete that patch. 👍 at least this keeps you moving!

**Comment by jevonearth** [comment]
That will be great!

Let us know if you have any feedback or issues using taquito generally. :)
