### ISSUE TITLE
TokenIdNotFound on metadata view failure

### ISSUE THREAD

**Issue by psmolinsky** [ecadlabs/taquito#1210]
**Description**

`Tzip12ContractAbstraction.getTokenMetadata()` throws `TokenIdNotFound` if execution of `token_metadata` view fails. However, it can fail because of *many other* reasons related to Tezos node (e.g. misconfigured [access-control-lists](https://tezos.gitlab.io/user/node-configuration.html#access-control-lists)) which does not mean that the token metadata does not exist.

Respective Taquito code is [here](https://github.com/ecadlabs/taquito/blob/master/packages/taquito-tzip12/src/tzip12-contract-abstraction.ts#L97-L101).

**Comment by dsawali** [comment]
Issue have been addressed by #641. Error handling will now be handled on the `executeView` level at `tzip16`
