### ISSUE TITLE
Evaluate stenciljs for producing components

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taquito#122]
We have created a couple React components for developers to use directly or to use as reference.

Let's evaluate building web components using stenciljs.com and see if the react/ember/angular/vue.js components that stencil produces are decent. The main risk I'm concerned about is that the resulting components become poor implementations. The upside or proposition of stenciljs is very compelling. Hence this is worth exploring.

**Comment by Innkst** [comment]
Won't do
