### ISSUE TITLE
Combine contract-no-annotations-call-by-index.spec.ts and contract-no-annotations-call-by-index-methodsObject.spec.ts suites

### ISSUE THREAD

**Issue by sinapsist** [ecadlabs/taquito#1222]
**Is your feature request related to a problem and use case? Please describe.**
A clear and concise description of what the problem/use case is. 
There are two test suites in integration tests - `contract-no-annotations-call-by-index.spec.ts` and `contract-no-annotations-call-by-index-methodsObject.spec.ts`, having the same name.
They look similar from the functionality perspective.

**Describe the solution you'd like**
I would suggest combining them into one suite and `contract-no-annotations-call-by-index.spec.ts` moving test for `methodsObject` and removing the second one.

**Describe alternatives you've considered**
Another option would be to leave as it is now

**Comment by michaelkernaghan** [comment]
Here is the file diff:
--- contract-no-annotations-call-by-index.spec.ts       2021-12-31 09:17:07.489072816 -0800
+++ contract-no-annotations-call-by-index-methodsObject.spec.ts 2021-12-31 09:17:07.489072816 -0800
@@ -31,7 +31,13 @@
       const contract = await op.contract()
 
       // Make a transfer
+
-      const operation = await contract.methods[TRANSFER](ACCOUNT1_ADDRESS, ACCOUNT2_ADDRESS, "1").send();
+      const operation = await contract.methodsObject[TRANSFER]({
+          0: ACCOUNT1_ADDRESS, 
+          1: ACCOUNT2_ADDRESS, 
+          2:"1"
+        }).send();
+      
       await operation.confirmation();
       expect(operation.status).toEqual('applied')
 
@@ -44,7 +50,11 @@
       expect(account2[BALANCE].toString()).toEqual('1')
 
       // Approve
-      const operation2 = await contract.methods[APPROVE](ACCOUNT2_ADDRESS, "1").send();
+      const operation2 = await contract.methodsObject[APPROVE]({
+          2: ACCOUNT2_ADDRESS, 
+          3: "1"
+        }).send();
+
       await operation2.confirmation();
       expect(operation2.status).toEqual('applied')


--------
it looks the two files are the same except for formatting

**Comment by michaelkernaghan** [comment]
I did fomrat file on both files and took a diff again. Now it is clearer that one is testing  const operation = await contract.methods[TRANSFER](
