### ISSUE TITLE
Combine integration test suites contract-big-map.spec.ts, contract-fetch-multiple-big-map-keys.spec.ts, contract-init-with-empty-bigmap.spec.ts and contract-big-map-access-by-index.spec.ts

### ISSUE THREAD

**Issue by sinapsist** [ecadlabs/taquito#1223]
**Is your feature request related to a problem and use case? Please describe.**
`contract-big-map-access-by-index.spec.ts` includes only tests related to an empty BigMap.
`contract-fetch-multiple-big-map-keys.spec.ts` includes one test related to a multiple BigMap
`contract-init-with-empty-bigmap.spec.ts` includes one test related to an empty BigMap
And `contract-big-map.spec.ts` may include them both BigMap with value and without

**Describe the solution you'd like**
I would suggest combining these three suites into one `contract-big-map.spec.ts` will reduce the number of test suites and group tests for the same functionality.

**Describe alternatives you've considered**
1. Leave as it is now
2. Rename `contract-big-map-access-by-index.spec.ts` to `contract-big-map-empty.spec.ts` and `contract-fetch-multiple-big-map-keys.spec.ts` to `contract-fetch-big-map-multiple-keys.spec.ts` and `contract-init-with-empty-bigmap.spec.ts` to `contract-bigmap-init-with-empty.spec.ts`

**Comment by michaelkernaghan** [comment]
The combined test option makes sense as these are four files each with one or two tests that cover the same topic. Best combined.
