### ISSUE TITLE
Re-write estimation integration tests (contract-estimation-tests.spec.ts) combine tests for separate networks into one generic and pass network as a parameter

### ISSUE THREAD

**Issue by sinapsist** [ecadlabs/taquito#1224]
**Is your feature request related to a problem and use case? Please describe.**
Currently, tests for contract estimation (contract-estimation-tests.ts) are built for each network separately, e. g.
florencenet('Verify .estimate.transfer with allocated destination result on florencenet', async (done) => {...
granadanet('Verify .estimate.transfer with allocated destination result on granadanet', async (done) => {...
and they look like hardcoded tests

**Describe the solution you'd like**
As a suggestion, we can probably make a string parameter that can be used in a switch statement to select code inside the test block
`test (param) =>{
  switch (param)
     case: testnet1
     case: testne2
}`
This will allow removing skipped tests.

**Describe alternatives you've considered**
Leave as it is now because it does not impact any functionality.
Additionally, it may be a solid reason to leave it if we want to see these tests as skipped.

**Comment by michaelkernaghan** [comment]
while this is generally good refactoring practice in this case, since we only have the two noes at one time, and each has potentially different values to assert against, it will be clearer for maintainers with the current structure. closing as will not do.
