### ISSUE TITLE
Publish minified packages on a CDN

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taquito#123]
Via the telegram tezos developers channel, a couple people asked that we publish packages to a CDN so that they can include the library using a `<script...>` tag on their web page/app.

We can use https://www.jsdelivr.com for this.

Using the `<script>` tag is not ideal, as the developer misses out on tree shaking and other nice ot have features, but to each their own.

We will likely make an all in one minified file including all lower-level packages. The asset size will be a bit larger, but it will be simpler. If developers are concerned about size, they should probably switch to a bundler and define dependencies in `package.json`

**Comment by jevonearth** [comment]
This was implemented back in January, but we lack tests or a testing strategy. Need to discuss.

**Comment by Innkst** [comment]
We also want to create a demo dApp and improve documentation before closing this.

**Comment by jevonearth** [comment]
Demo app can be deployed to Netlify.

Suggestion is to put a drop down on the demo app allowing the user to select a Taquito version. Demo app should read data, originate contracts, call a smart contract method, send some tezos tokens.

As a separate issue, we can write browser-based tests to automated this testing.

**Comment by jevonearth** [comment]
Related to #458

**Comment by Innkst** [comment]
#458 supercedes this one.
