### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by andrevenancio** [ecadlabs/taquito#1240]
**Description**
I am no longer able to use taquito to handle calls to a contract I was able to call just a few days ago. I am able to login, I call an operation on the smart contract using taquito and I have a call that never resolves and timesout after 30 seconds.

The call is `https://granadanet.smartpy.io/chains/main/blocks/head/context/contracts/KT1Lar6n6xiZCUyr77DzRrqW3nwudm69xo6c/script/normalized` where `KT1Lar6n6xiZCUyr77DzRrqW3nwudm69xo6c` is the contract I'm trying to call.

I'm using the latest taquito version 11.0.2

Below is an example of something that used to work before and now it doesn't work

```javascript

let wallet: BeaconWallet;
let tezos: TezosToolkit;
const network: Network = {
  type: NetworkType.GRANADANET,
  name: 'Granadanet',
  rpcUrl: 'https://granadanet.smartpy.io/',
};

wallet = new BeaconWallet({ name: 'versum', preferredNetwork: 'network.type' });

tezos = new TezosToolkit(network.rpcUrl as string);
tezos.setWalletProvider(wallet);

let myAddress: string | undefined;

const activeAccount = await wallet.client.getActiveAccount();
if (activeAccount) {
    myAddress = activeAccount.address;
} else {
    await wallet.requestPermissions();
    myAddress = await wallet.getPKH();
}
console.log('connected address:', myAddress);

const contract = await tezos.contract.at('KT1XUw3is6ZbTJ1xKUYPefuVZ2ECd7LEan2Q'); //this line fails to load
console.log('contract', contract); // this line never gets called

```

**Comment by andrevenancio** [comment]
Even the example of Beacon SDK Documentation (which refers taquito) fails. https://docs.walletbeacon.io/guides/simple-contract-call

```javascript
import { TezosToolkit } from "@taquito/taquito";
import { BeaconWallet } from "@taquito/beacon-wallet";

const Tezos = new TezosToolkit("https://mainnet-tezos.giganode.io");
const wallet = new BeaconWallet({ name: "Beacon Docs" });

Tezos.setWalletProvider(wallet);

const address = await wallet.getPKH();
if (!address) {
  await wallet.requestPermissions();
}

// We now know we are connected, or the above code threw an error
const TZ_BUTTON_COLORS_CONTRACT = "KT1RPW5kTX6WFxg8JK34rGEU24gqEEudyfvz";
const contract = await Tezos.wallet.at(TZ_BUTTON_COLORS_CONTRACT);

const tokenId = "925";

try {
  const result = await contract.methods.set_color(tokenId).send();
} catch (error) {
  console.log(
    `The contract call failed and the following error was returned:`,
    error?.data[1]?.with?.string
  );
}
```
with 
```
"@taquito/beacon-wallet": "^11.0.2",
"@taquito/taquito": "^11.0.2",
"@taquito/utils": "11.0.2",
```
The line `const contract = await Tezos.wallet.at(TZ_BUTTON_COLORS_CONTRACT);` never resolves. it calls the following file https://mainnet-tezos.giganode.io/chains/main/blocks/head/context/contracts/KT1RPW5kTX6WFxg8JK34rGEU24gqEEudyfvz/script/normalized and it timesout after 30seconds..

**Comment by claudebarde** [comment]
I tried the first code and indeed, it doesn't work. But the problem seems to come from the RPC node you are using and not Taquito. When using another RPC node (for example, `https://granadanet.api.tez.ie`), the error goes away. It is possible that SmartPy doesn't maintain their Granada testnet anymore, which creates errors.
As a general rule, the latest testnet should be used to run tests, which is currently `hangzhounet`.

**Comment by andrevenancio** [comment]
Ah interesting. I was under the impression if I'm interacting with smartcontracts deployed to granadanet that I would have to have my node pointing to a granadanet node. So I can point to the new hangzhounet nodes? are they backwards compatible?

**Comment by claudebarde** [comment]
Yes, you are right, if the contract is on Granadanet, you need to interact with a node that points to Granadanet, which is what `https://granadanet.api.tez.ie` does. However, it is best practice to use the latest testnet available, so you can reoriginate (or fork) the contract on Granadanet to Hangzhounet in order to have a testing environment that mimics better the current blockchain.

**Comment by andrevenancio** [comment]
Sorry @claudebarde, I already closed this ticket, but out of curiosity do you know why better-call-dev has 2 different hangzhounet to choose from? one `hangzhounet` and another `hangzhou2net` and tzkt.io only has the `hangzhou2net`.

I'm trying to find nodes I can use

**Comment by andrevenancio** [comment]
You legend! Thanks!
