### ISSUE TITLE
Changes to the Docs Smart Contract Collection

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taquito#1248]
Some edits for the Contract Library and for the names of contracts used in the docs live examples origination script

1. rename the tzip16 off-chain one and two contracts to include the off-chain part, as this is the only difference between them
2.  add the known contracts for Integration tests, unless they are duplicates of ones already listed, in which case indicate that in the listing.
        - knownContract = hangzhounet:  KT1J5Vbek6SAgUStzb3HEMdrgRnMaanxNkNB 
            - to be called "LambdaViewWithStoredCounterContract"            
        -  knownBigMapContract is:  hangzhounet: KT1Ds2LC3QqxVVqh95VdfxTmBsRZZBrh8Pgm
           -    Not a supported FA1.2 contract.  :  Entrypoint "transfer" has type (pair (pair (address %0) (address %1)) (nat %2)), but 
           -    should have type  (pair address address nat). 
           -    Not an FA2 contract
    
3. Add more commentary for tzip and big map contracts
4. change the name from "Contract Library" to "contract Collection"
6. for the Storage, also show the Taquito version and use tabs to show Taquito/Michelson
7. add the new Fibonacci contracts from https://github.com/ecadlabs/taquito/pull/1251

**Comment by roxaneletourneau** [comment]
We need a way of keeping the page up-to-date without requiring too much effort. - When we upgrade the testnet on the website, it would be great not to have to manually update the contract addresses of the page.

- We will continue adding contracts on the website, which means that we will need to add these contracts to this documentation page also

**Comment by michaelkernaghan** [comment]
I have a script that originates the contracts needed for each new protocol. This script can write a json file with an array of names and contract ids. The docs can then get the new contract id by matching on the name. I believe this can work in docusaurus.

**Comment by michaelkernaghan** [comment]
Another option is to simply describe the contracts and not have a link to a specific instance of the contract. That way there is nothing to update; we just add new contracts as we start to use them in tests and examples.

**Comment by michaelkernaghan** [comment]
I am tempted to add
 8. remove the links to BCD.

Do you agree?

**Comment by roxaneletourneau** [comment]
The links to BCD are nice to have, but yes for maintainability we could remove them.

**Comment by michaelkernaghan** [comment]
WE will be going ahead eventually with the full automation using docusaurus. In the meantime, we can manually maintain the links. It may be only one time.

**Comment by michaelkernaghan** [comment]
1,2, and 4 are done.
