### ISSUE TITLE
ExtractSchema() does not consider `option` type

### ISSUE THREAD

**Issue by psmolinsky** [ecadlabs/taquito#1252]
**Description**
`Schema.ExtractSchema()` method does not consider the `option` type. This make it indistinguishable if the `option` is there or not.

**Steps To Reproduce**

1. Create a `Schema` with Michelson containing the `option` type and call the method.

```typescript
const schema = new Schema({ prim: 'option', args: [{ prim: 'nat' }] });
const extracted = schema.ExtractSchema();
```
2. It returns:

```typescript
"nat"
```

3. Do the same with similar schema **without** `option` and call the method

```typescript
const schema = new Schema({ prim: 'nat' });
const extracted = schema.ExtractSchema();
```
4. It returns the same result:

```typescript
"nat"
```

**Expected behavior**

The `option` type should be expressed in the extracted schema. For example in the step 2 the result could be `"option nat"` or an object `{ option: "nat" }`. The step 4 could stay as it is.

**Comment by roxaneletourneau** [comment]
@psmolinsky
The ExtractSchema method is missing some important detail for some types and is not uniform across all tokens.
If adding a property `option` for the option type, I feel that at some point it might become confusing to distinguish between the contract annotations and properties added by Taquito to the schema. 
As the change mentioned in the current ticket would result in a breaking change, I thought it was a good occasion to refactor the `ExtractSchema` method to make it more uniform and easy to discover.
I implemented a new method named `generateSchema`. The intention is to deprecate `ExtractSchema` in favor of this new one.
For each token, `generateSchema` returns an object of type `TokenSchema`. `TokenSchema` has a property `__michelsonType` which is a `string` and a property `schema` that contains information on the schema of the subtoken when applicable.

I would like to know if the proposed solution seems convenient for you.

Here is a link to preview builds: https://github.com/ecadlabs/taquito/pull/1316#issuecomment-1013519287
Some schema examples can be found in the unit tests here: https://github.com/ecadlabs/taquito/pull/1317/files

## Examples:
The michelson type: { prim: 'option', args: [{ prim: 'int' }], annots: [] } will be represented as follow by the generateSchema method:
```
{
        __michelsonType: 'option',
        schema: {
          __michelsonType: 'int',
          schema: 'int'
        }
}
```

The michelson type: { prim: 'pair', args: [{ prim: 'int', annots: ['test'] }, { prim: 'string', annots: ['test2'] }], } will be represented as follow by the generateSchema method:
```
// Nested pair will be brought to the same level (as it is the case with the ExtractSchema)
{
        __michelsonType: 'pair',
        schema: {
          test: {
            __michelsonType: 'int',
            schema: 'int'
          },
          test2: {
            __michelsonType: 'string',
            schema: 'string'
          }
        }
}
```

The michelson type: { prim: 'map', args: [{ prim: 'string' }, { prim: 'int' }], annots: [] } will be represented as follow by the generateSchema method:
```
// schema of a map has `key` and `value` properties
{
        __michelsonType: 'map',
        schema: {
          key: {
            __michelsonType: 'string',
            schema: 'string'
          },
          value: {
            __michelsonType: 'int',
            schema: 'int'
          }
        }
}
```

**Comment by roxaneletourneau** [comment]
Improved the `Tokenschema` type and replaced the link for the preview version in the comment above.

**Comment by psmolinsky** [comment]
Great move, thanks. It makes the schema object much less ambiguous.
