### ISSUE TITLE
Error with `Tezos.contract.transfer`

### ISSUE THREAD

**Issue by phlalx** [ecadlabs/taquito#127]
I'm having the following error using the `Tezos.contract.transfer` method.

```
{
  status: 500,
  statusText: 'Internal Server Error',
  body: '[{"kind":"branch","id":"proto.005-PsBABY5H.contract.previously_revealed_key","contract":"tz1bwT9XB9tpzTKKw7UtTSzS9dfXjAzqXzoi"}]\n'
}
```
My server is a local zeronet node and I'm running this script:
```
const { Tezos } = require('@taquito/taquito')
const { InMemorySigner } = require('@taquito/signer')
..
const privateKey = 'edsk4KYzU19Hj7wuZX9it5L6pyRwz9zss2wk627kkvuGJB7vXHcwB8'
const server = 'http://127.0.0.1:8732'
Tezos.setProvider({signer: new InMemorySigner(privateKey)})
Tezos.setProvider({rpc: server})
const some_address = 'tz1bwT9XB9tpzTKKw7UtTSzS9dfXjAzqXzoi'
Tezos.contract.transfer({to: contract_address, amount: 2}).then (
    x => console.log(x)
).catch(
    x => console.log(x)
)
```
I have no issue running the same transaction with `tezos-client`. Am I doing anything wrong?

**Comment by jevonearth** [comment]
Hi Philippe,

We have been targeting `proto.004` / `Athens` up until recently. We will be pushing a pre-release for Babylon support pretty soon, which will resolve this (and other) issues.

Thank you for logging this!

**Comment by jevonearth** [comment]
Please use the `5.0.1-beta.0` release, as the v5.X tags `babylon/005`.
