### ISSUE TITLE
what is the difference between setDelegate and RegisterDelegate.

### ISSUE THREAD

**Issue by btfdip** [ecadlabs/taquito#1279]
it's a little vague here.

https://tezostaquito.io/docs/set_delegate

![image](https://user-images.githubusercontent.com/96004784/147822500-a5f310ab-d340-4a10-a23d-8097cf5d63af.png)

**Comment by Innkst** [comment]
It depends on your use case. The address needs to be registered as a delegate using 'registerDelegate' before it can be delegated to. Then you can delegate to that account using 'setDelegate'.
If the use case is only to delegate to a known baker(delegate), then you should use 'setDelegate'.
We will update the documentation to make it more clear. Thanks!
