### ISSUE TITLE
Replace deprecated instruction SUB in test

### ISSUE THREAD

**Issue by roxaneletourneau** [ecadlabs/taquito#1294]
The contracts used in the integration tests `contract-call-with-xtz-amount.spec.ts`, `wallet-unit-as-param.spec.ts` and `contract-unit-as-param.spec.ts` use the deprecated instruction `SUB`.
A fix is needed for these contract on ithacanet.

> The SUB instruction on type mutez is deprecated. It can be replaced by SUB_MUTEZ; ASSERT_SOME (and SUB; DROP can be replaced by ASSERT_CMPGE).

**Additional context**
https://tezos.gitlab.io/protocols/012_ithaca.html#michelson

**Comment by michaelkernaghan** [comment]
the three test files all originate the same contract from the Michelson source

~/taquito/integration-tests/data/deposit_contract.ts

There are three uses of SUB in the code:
line 393
line  910
line 1218

**Comment by michaelkernaghan** [comment]
The three tests are marked skip if Ithacanet. After the change, the skip should be removed.
