### ISSUE TITLE
Generate web form based on a contract methods and storage

### ISSUE THREAD

**Issue by carte7000** [ecadlabs/taquito#13]
Goal: to create a web form demo with the goal of improving Taquito APIs.

## Story 1 contract methods

As a developer user of Taquito, I want to easily generate a web-form based on arbitrary smart contract methods so that I can quickly build applications with forms that correspond to the contract.  

## Story 2 initial storage

As a developer user of Taquito, I want to generate a web form for the storage type of my Michelson contract so that I can easily and conveniently generate a user interface that allows me to define the initial storage values for a smart contract that I am about to originate.

**Comment by jevonearth** [comment]
Better call dev provides neat form generation which can be seen here: https://better-call.dev/mainnet/KT1EctCuorV2NfVb1XTQgvzJ88MQtWP8cMMv/interact?entrypoint=freeze

**Comment by Innkst** [comment]
https://myxtzwallet.tokengate.io/

**Comment by jevonearth** [comment]
Related to #418

**Comment by michaelkernaghan** [comment]
factori does this out of the box easily.
