### ISSUE TITLE
Add validation to possible different hashes being passed in the Taquito codebase

### ISSUE THREAD

**Issue by dsawali** [ecadlabs/taquito#1311]
Currently most if not all validation of different types of hashes is being left for the Node.
We would like to validate locally in Taquito to ensure correctness.

Example case:
- https://github.com/ecadlabs/taquito/blob/master/packages/taquito/src/contract/rpc-contract-provider.ts#L402 where we would like to utilize `validateContractAddress()` to validate the address param

AC:
- Identify where we'd like to utilize our validators in our codebase
- Add validation on those parts

This is a follow up to issue #95

**Comment by roxaneletourneau** [comment]
We can validate the addresses passed in the different operations (transfer/delegation/origination...)
 
**taquito/taquito**
Validation on the key hash can be done here:
- params.to, params.source: https://github.com/ecadlabs/taquito/blob/d1cca8cb62f6fa9b5fbeda74f6d8e690a58d8380/packages/taquito/src/batch/rpc-batch-provider.ts#L53
- params.source, params.delegate: https://github.com/ecadlabs/taquito/blob/d1cca8cb62f6fa9b5fbeda74f6d8e690a58d8380/packages/taquito/src/batch/rpc-batch-provider.ts#L74
- https://github.com/ecadlabs/taquito/blob/d1cca8cb62f6fa9b5fbeda74f6d8e690a58d8380/packages/taquito/src/batch/rpc-batch-provider.ts#L85
- params.delegate, params.source: https://github.com/ecadlabs/taquito/blob/d1cca8cb62f6fa9b5fbeda74f6d8e690a58d8380/packages/taquito/src/contract/rpc-contract-provider.ts#L270
- params.to, parmas.source : https://github.com/ecadlabs/taquito/blob/d1cca8cb62f6fa9b5fbeda74f6d8e690a58d8380/packages/taquito/src/contract/rpc-contract-provider.ts#L327
- rest.to, rest.source: https://github.com/ecadlabs/taquito/blob/d1cca8cb62f6fa9b5fbeda74f6d8e690a58d8380/packages/taquito/src/contract/rpc-estimate-provider.ts#L221
- rest.source, rest.delegate: https://github.com/ecadlabs/taquito/blob/d1cca8cb62f6fa9b5fbeda74f6d8e690a58d8380/packages/taquito/src/contract/rpc-estimate-provider.ts#L246
- param.to https://github.com/ecadlabs/taquito/blob/d1cca8cb62f6fa9b5fbeda74f6d8e690a58d8380/packages/taquito/src/wallet/wallet.ts#L34
- https://github.com/ecadlabs/taquito/blob/d1cca8cb62f6fa9b5fbeda74f6d8e690a58d8380/packages/taquito/src/wallet/wallet.ts#L55
- https://github.com/ecadlabs/taquito/blob/d1cca8cb62f6fa9b5fbeda74f6d8e690a58d8380/packages/taquito/src/wallet/wallet.ts#L228

Validation on the contract address can be done here: 
- https://github.com/ecadlabs/taquito/blob/d1cca8cb62f6fa9b5fbeda74f6d8e690a58d8380/packages/taquito/src/contract/rpc-contract-provider.ts#L393
- https://github.com/ecadlabs/taquito/blob/d1cca8cb62f6fa9b5fbeda74f6d8e690a58d8380/packages/taquito/src/contract/rpc-contract-provider.ts#L85
- https://github.com/ecadlabs/taquito/blob/d1cca8cb62f6fa9b5fbeda74f6d8e690a58d8380/packages/taquito/src/contract/rpc-contract-provider.ts#L56
- https://github.com/ecadlabs/taquito/blob/d1cca8cb62f6fa9b5fbeda74f6d8e690a58d8380/packages/taquito/src/wallet/wallet.ts#L263
