### ISSUE TITLE
Update the rpc nodes test

### ISSUE THREAD

**Issue by roxaneletourneau** [ecadlabs/taquito#1356]
Add test cases for the `RpcClient` methods that are not included in the `rpc-nodes.spec.ts` file: https://github.com/ecadlabs/taquito/blob/master/integration-tests/rpc-nodes.spec.ts

Tests needed for the following methods:
- getSaplingDiffById
- getSaplingDiffByContract
- getNormalizedScript

Validate if other methods are missing from the test and add tests case accordingly.

**Comment by michaelkernaghan** [comment]
there are several sapling contracts here:  https://gitlab.com/tezos/tezos/-/tree/master/src/proto_012_Psithaca/lib_protocol/test/contracts
