### ISSUE TITLE
[Website] Note component visual bug in dark mode

### ISSUE THREAD

**Issue by dsawali** [ecadlabs/taquito#1363]
Dark mode in Docusaurus does not work well with the 'Note' component.

![image](https://user-images.githubusercontent.com/16856119/151251956-7f2d7e8b-0de4-462d-aed1-613046f60aa5.png)

**Steps To Reproduce**
1. Go to https://tezostaquito.io/docs/next/ledger_signer
2. Click on the "Dark mode" theme toggle on the top right of the page
3. See that the color scheme of the Note component does not work well with dark mode

**Expected behavior**
"Note" component displays the content correctly

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Google Chrome (97.046)

Fix the Note component styling so that it works well with both light mode and dark mode.

**Comment by michaelkernaghan** [comment]
Here is a list of where the problems are in the site:  

Go to https://tezostaquito.io/docs/lambda_view
select dark mode
scroll to How to deploy a lambda contract (sandbox users):
observe the white box
change to light mode, observe that there is a note that can't be read in dark mode.
There is another one on https://tezostaquito.io/docs/smartcontracts
at: Choosing between the methods or methodsObject members to interact with smart contracts

and at: https://tezostaquito.io/docs/tzip12
Example where the token metadata are found in the big map %token_metadata

also: https://tezostaquito.io/docs/inmemory_signer
Loading an unencrypted private key
and one at
Using a testnet faucet key

At the top of: https://tezostaquito.io/docs/ledger_signer
there are two

on : https://tezostaquito.io/docs/upgrading_guide
at Upgrading to version 7
