### ISSUE TITLE
Origination of complex contracts fail

### ISSUE THREAD

**Issue by asbjornenge** [ecadlabs/taquito#1387]
Hi there 😊

I'm having some trouble originating complex contracts using the wallet API.

I'm in a React app using `@taquito/taquiot@11.2.0` and `@taquito/beacon-wallet@11.2.0` and connecting Temple wallet.

The following code works fine if I use a very simple contract:

```
export async function originate(contract, storage) {
  const op = await Tezos.wallet.originate({
    code: contract,
    init: storage,
  }).send()
  await op.confirmation(1)
  const _contract = await op.contract()
  return _contract.address
}
```

Contract and storage are JSONs produced by a SmartPy compilation of this simple contract:

```
import smartpy as sp

class Simple(sp.Contract):

  def __init__(self, admin):
    self.init(
      admin = admin
    )

  @sp.entry_point
  def default(self):
    pass

  @sp.entry_point
  def setAdmin(self, admin):
    sp.set_type(admin, sp.TAddress)
    self.data.admin = admin
```

However, if I try to originate say a FA2 token contract using the exact same approach (compile via smartpy into jsons and importing them), I get this error:

```
[
  {
    "kind": "temporary",
    "id": "proto.011-PtHangz2.storage_exhausted.operation"
  }
]
```

NOTE: The contract originates fine using smartpy.

🤔🤔🤔

So it seems to me to be some kind of storage and / or gas fee calculation that is failing?

I have tried using the `toolkit.estimate` API but it complains that `No signer has been configured` 😅 And I cannot seem to find a way to set a signer using the BeaconWallet. I do call `.setWalletProvider` ofcourse, but it does not seem to set it...?

Any and all help would be greatly appreciated 🙌

thanks!

**Comment by asbjornenge** [comment]
FYI: Using the exact same code, contracts and versions above, works totally fine in Node.js 😅

Only difference is I use `importKey` instead of `setWalletProvider` 🤔 I guess that sets the signer properly or something 😅

**Comment by roxaneletourneau** [comment]
Hi @asbjornenge 
Did you try increasing the storage limit before confirming the operation with the Temple wallet:
![image](https://user-images.githubusercontent.com/65877347/157491979-948d48ec-b728-4867-948f-325470bfd41c.png)

It is currently only possible to estimate based on a signer. We made a fix so an estimate can be run based on a configured wallet too. It will be part of release 12.0.0.

**Comment by asbjornenge** [comment]
Hi @roxaneletourneau :blush: 

I get this message "Transaction will likely fail" and I cannot adjust anything :see_no_evil: Also, I'm building a site for our customers to use, and I cannot rely on them doing this correctly :man_shrugging: 

What I ideally want to do is to set `storage_limit: calculation + 10` or something so it won't fail.

I have a similar issue with some gas calc issue on a complex contract with some looping that is currently failing.

Awesome to head that estimate is coming in 12.0.0 - will be looking forward to that :partying_face: Hoping that will fix both my issues :raised_hands:
