### ISSUE TITLE
contract.tzip16().metadataViews() return HttpRequestFailed

### ISSUE THREAD

**Issue by daxuanxiaoyou** [ecadlabs/taquito#1403]
**js code:**
const tezos = new TezosToolkit('https://mainnet.api.tez.ie');
tezos.addExtension(new Tzip16Module());
tezos.addExtension(new Tzip12Module());

const contract = await tezos.contract.at(
        contractAddress, 
        compose(tzip16, tzip12));

views = await contract.tzip16().metadataViews();

**result:**
and the result is "HttpRequestFailed":
HttpRequestFailed {
  url: 'https://ipfs.io/ipfs/QmSBc8QuynU7bArUGtjwCRhZUbJyZQArrczKnqM7hZPtfV/',
  innerEvent: ProgressEvent {
    type: 'error',
    bubbles: false,
    cancelable: false,
    loaded: 0,
    lengthComputable: false,
    total: 0,
    target: XMLHttpRequest {
      listeners: {},
      UNSENT: 0,
      OPENED: 1,
      HEADERS_RECEIVED: 2,
      LOADING: 3,
      DONE: 4,
      onreadystatechange: null,
      readyState: 4,
      response: null,
      responseText: '',
      responseType: '',
      status: 0,
      statusText: '',
      timeout: 30000,
      upload: [XMLHttpRequestUpload],
      responseUrl: '',
      withCredentials: false,
      _method: 'GET',
      _url: [Url],
      _sync: false,
      _headers: [Object],
      _loweredHeaders: [Object],
      _mimeOverride: 'text; charset=utf-8',
      _request: null,
      _response: null,
      _responseParts: null,
      _responseHeaders: null,
      _aborting: null,
      _error: null,
      _loadedBytes: 0,
      _totalBytes: 0,
      _lengthComputable: false,
      _restrictedMethods: [Object],
      _restrictedHeaders: [Object],
      _privateHeaders: [Object],
      _userAgent: 'Mozilla/5.0 (Darwin x64) node.js/16.13.0 v8/9.4.146.19-node.13',
      _anonymous: false,
      onload: [Function (anonymous)],
      ontimeout: [Function (anonymous)],
      onerror: [Function (anonymous)]
    }
  },
  name: 'HttpRequestFailed',
  message: 'Request to https://ipfs.io/ipfs/QmSBc8QuynU7bArUGtjwCRhZUbJyZQArrczKnqM7hZPtfV/ failed'
}

**try on chrome:**
i request https://ipfs.io/ipfs/QmSBc8QuynU7bArUGtjwCRhZUbJyZQArrczKnqM7hZPtfV/ on my site with chrome, everything is ok

pls help me, thx very much

**Comment by claudebarde** [comment]
Opening an URL in the browser and sending an HTTP request to a URL are 2 different things, one working doesn't imply that the second one should. The HTTP request may be blocked because of CORS issues or may fail for many reasons.
Inside your JavaScript code, try `await fetch("https://ipfs.io/ipfs/QmSBc8QuynU7bArUGtjwCRhZUbJyZQArrczKnqM7hZPtfV/")` and see if you get a response.

**Comment by daxuanxiaoyou** [comment]
> Opening an URL in the browser and sending an HTTP request to a URL are 2 different things, one working doesn't imply that the second one should. The HTTP request may be blocked because of CORS issues or may fail for many reasons. Inside your JavaScript code, try `await fetch("https://ipfs.io/ipfs/QmSBc8QuynU7bArUGtjwCRhZUbJyZQArrczKnqM7hZPtfV/")` and see if you get a response.

=====

node_modules/node-fetch/lib/index.js:1476
					reject(new FetchError(`network timeout at: ${request.url}`, 'request-timeout'));
					       ^
FetchError: network timeout at: https://ipfs.io/ipfs/QmSBc8QuynU7bArUGtjwCRhZUbJyZQArrczKnqM7hZPtfV/
    at Timeout.<anonymous> (/Users/bj89131ml/work/node_modules/node-fetch/lib/index.js:1476:13)
    at listOnTimeout (node:internal/timers:568:17)
    at processTimers (node:internal/timers:510:7) {
  type: 'request-timeout'
}

Node.js v17.3.0
 the value of timeout is 50000ms, i set

**Comment by daxuanxiaoyou** [comment]
const fetchParam = {
        method: 'GET',
        agent: new HttpProxyAgent("my http proxy")
    }
    let info = await fetch("https://ipfs.io/ipfs/QmSBc8QuynU7bArUGtjwCRhZUbJyZQArrczKnqM7hZPtfV/", fetchParam);

and the request is ok now.

thank you for your replay   @claudebarde
