### ISSUE TITLE
Kukai wallet prompt doesn't disappear after authenticating

### ISSUE THREAD

**Issue by dapperdappy** [ecadlabs/taquito#1415]
**Description**
The prompt never goes away despite having successfully authenticated.

**Steps To Reproduce**
1. Use beacon to connect your wallet
2. Choose Kukai wallet
3. Authenticate using Kukai wallet
4. Beacon popup never goes away

**Expected behavior**
Beacon popup for Kukai should go away after it has authenticated

**Screenshots**
![image](https://user-images.githubusercontent.com/96356120/154873470-375479c3-21ce-4e0a-96b6-c8c7ab19573e.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 98

**Comment by claudebarde** [comment]
Taquito has no control over the popups that Beacon creates, the problem comes most probably from Beacon and you should open an issue [in the Beacon SDK repo](https://github.com/airgap-it/beacon-sdk/issues) to report the problem.

**Comment by Innkst** [comment]
@dapperdappy please check the comment above and feel free to link Beacon SDK issue here. Thanks
