### ISSUE TITLE
Stuck at wallet removeAllPeers

### ISSUE THREAD

**Issue by callmekatootie** [ecadlabs/taquito#1421]
**Description**

The `wallet.client.removeAllPeers()` method won't return

**Steps To Reproduce**

I initialize the BeaconWallet as:

```js
const wallet = new BeaconWallet({
  name: "Foobar",
  preferredNetwork: NetworkType.HANGZHOUNET,
  disableDefaultEvents: true,
});
```

User then connects their wallet (`wallet.requestPermissions()`). Later on, when user wants to disconnect, I invoke:

```js
await wallet.client.removeAllAccounts();
await wallet.client.removeAllPeers();
await wallet.client.destroy();
```

This is as per the code found in the [react-template](https://github.com/ecadlabs/taquito-react-template)

However, I find that the code never returns from `wallet.client.removeAllPeers()` - I navigate the user to a different page after they disconnect their wallet - but that code is never invoked. On debugging, I find that the execution of `await wallet.client.removeAllPeers()` seems to halt and no code is executed after that.

**Expected behavior**

The code in the template work (or the template be updated) and any function call after the destroy be invoked

**Comment by claudebarde** [comment]
When you check the local storage after disconnecting the wallet, do you see a lot of different values associated with the Beacon SDK? Destroying the P2P connection of the wallet should only leave 1-2 values in the local storage, compared to over half a dozen when the wallet is connected.

**Comment by callmekatootie** [comment]
So - when wallet is connected, my local storage looks like this:

![image](https://user-images.githubusercontent.com/2317133/156113494-25a84797-2eca-409f-bdd9-6a8c007f185a.png)

and when I disconnect, I check after 10 seconds (because the function does not return so not sure what is the ideal time I need to wait for):

![image](https://user-images.githubusercontent.com/2317133/156113682-875142d5-b649-4b4e-802d-49c5c78513ea.png)

`beacon:accounts` is not seen. `beacon:active-account` is undefined. Others are untouched.

**Comment by claudebarde** [comment]
When you use `wallet.client`, you access directly the`DappClient` instance of the Beacon SDK, so Taquito has no control over what happens there. I would suggest you post this issue in the Beacon SDK repo to get an answer.

**Comment by callmekatootie** [comment]
Just being sure - is this the beacon sdk - https://github.com/airgap-it/beacon-sdk ?

**Comment by claudebarde** [comment]
Yes, that's the one
