### ISSUE TITLE
Documentation page dedicated to multi-sig

### ISSUE THREAD

**Issue by roxaneletourneau** [ecadlabs/taquito#1434]
Make a new Taquito docs page dedicated to multi-sig, and provide a few practical examples such as minting and transferring assets using the multisig contract.

We do have some integration tests that demonstrate use here; https://github.com/ecadlabs/taquito/blob/master/integration-tests/contract-multisig-scenario.spec.ts

The page should explains/demonstrates the following things;

- Multi-sig
  - Transfer tez from a multi-sig to a third party
  - Mint a NFT on an NFT contract via a multi-sig contract (the multi-sig should be the owner of the NFT)
  - Deploy a new, arbitrary contract via a multi-sig contract
  - Update a lambda in a target contract via a multi-sig contract
  - Remove a key from the multi-sig key list
  - Add a new key to the multi-sig key list

**Comment by claudebarde** [comment]
@roxaneletourneau How do you think the adding and removal of a key in the managers list should be implemented?
We can let individual managers add and remove managers but it is not the safest solution.
We can also add or remove keys via a proposal approved by the other managers, but that may be more cumbersome to test.
