### ISSUE TITLE
Add method to set provider individually on taquito

### ISSUE THREAD

**Issue by carte7000** [ecadlabs/taquito#144]
Currently, we need to set taquito providers using the setProvider method.

Even if the setProvider exposes an easy to change multiple providers at a time some users might appreciate to be able to change one provider using a specific method. For instance:

Instead of doing `Tezos.setProvider({signer: mySigner})`

We could add method to do:
`Tezos.setSigner(mySigner)`

**Comment by jevonearth** [comment]
Done
