### ISSUE TITLE
Beacon-SDK & Taquito with NEXTjs?

### ISSUE THREAD

**Issue by project0xpi** [ecadlabs/taquito#1443]
Anyone tried Beacon &  taquitojs with NextJs ? can't pass this error :

```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
event - compiled client and server successfully in 236 ms (124 modules)
wait  - compiling / (client and server)...
event - compiled client and server successfully in 615 ms (596 modules)
GOT MOCK POST MESSAGE { target: 'toExtension', payload: 'ping' }
GOT MOCK POST MESSAGE { target: 'toExtension', payload: 'ping' }
ReferenceError: localStorage is not defined
```
I tried a generic solution to use the if (typeof window !== 'undefined') wrapper , useEffect & disabling server-side-rendering but no luck at alllll XD

**Comment by claudebarde** [comment]
The `GOT MOCK POST MESSAGE { target: 'toExtension', payload: 'ping' }` message comes from the Beacon SDK detecting that it is not running in the browser. AFAIK, it should set up the right environment to work in this situation.
I would first try to use a package that emulates the local storage in NodeJS. If that fails, you should open an issue in the [Beacon SDK repo](https://github.com/airgap-it/beacon-sdk) or contact the devs directly to get more information about how to set it up with NextJS.

**Comment by project0xpi** [comment]
Thanks a lot ...I will try it out and proceed with your advice :D
