### ISSUE TITLE
Understand and prepare for Michelson Annotation reductions in protocol J 

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taquito#1453]
When running Taquito integration tests against Monday net we found that some contracts originated by Taquito were losing their annotations.

It turns out annotations changes are due for protocol J. It is not clear that the changes were intended to behave in Taquito as they did, making it a breaking change.

Some of the background on the changes:  https://forum.tezosagora.org/t/ignoring-annotations/2643

and a Tzip :  [link](https://gitlab.com/mbouaziz/tzip/-/blob/mehdi@ignoring-annotations/drafts/current/draft-ignoring-annotations.md)

**Comment by roxaneletourneau** [comment]
**Analysis of the impact on Taquito:**

### Storage
As an example, we refer to a contract having the following storage type: `storage (pair (address %theAddress) (nat %theNat))`

**- Origination of the contract using the storage JS object: no impact**
The contract (containing annotations) can be deployed using JS object with annotations like before:
```
const op = await Tezos.contract.originate({
        code,
        storage: {
          theAddress: 'tz1WuWPgU7CerJfxMucFCQ7QdUcSd1Afugwb',
          theNat: "6"
        }
      })
```
**- Accessing a property of the storage after origination: BREAKING CHANGES**
When creating a ContractAbstraction, the script is fetched using the RPC `/context/contracts/${address}/script/normalized`. The returned script does not contain the annotations anymore. The Michelson-Encoder uses indexes to represent the storage as there are no annotations found.
The annotations were useful to access a specific property of the storage and are more convivial than indexes.

Before the J protocol, the storage would look like this:
```
{
      theAddress: 'tz1WuWPgU7CerJfxMucFCQ7QdUcSd1Afugwb',
      theNat: BigNumber { s: 1, e: 0, c: [ 6 ] }
}
```

With the change in J protocol, the storage looks like this:
```
{
     0: 'tz1WuWPgU7CerJfxMucFCQ7QdUcSd1Afugwb',
     1: BigNumber { s: 1, e: 0, c: [ 6 ] }
}
```  

### Calling smart contract entrypoint using methodsObject
As an example we refer to a contract having different entrypoint, one of which is named mint and has the following type : `{ "prim": "pair", "args": [{ "prim": "address", "annots": [":to"] }, { "prim": "nat", "annots": [":value"] }], "annots": ["%mint"] }`

Before version J, it is possible to call the entrypoint point using an object where the keys are the annotations:
```
const opMethod = await contract.methodsObject.mint({
        to: await Tezos.signer.publicKeyHash(), 
        value: 100
}).send();
```

With the change in J protocol, the annotations are not present in the script fetched from the RPC and the parameter needs to be:
```
const opMethod = await contract.methodsObject.mint({
        0: await Tezos.signer.publicKeyHash(), 
        1: 100
}).send();
```

### Tzip16
The specification indicates that the bigmap should have the following type : 
```
{
  prim: 'big_map',
  args: [{ prim: 'string' }, { prim: 'bytes' }],
  annots: ['%metadata'],
}
```
Taquito looks into the storage for this specific type to find the URI of the metadata which can not be done as is with protocol J as the annotation metadata is removed. We can loosen the type (removed the annotation during the lookup), but we need to assess what will be the impact if there is more than one big_map matching the "less specific " type in the storage of the contract.

### Tzip12

Same as the precedent section but with the following type:
```
{
  prim: 'big_map',
  args: [
    { prim: 'nat' },
    {
      prim: 'pair',
      args: [
        { prim: 'nat', annots: ['%token_id'] },
        { prim: 'map', args: [{ prim: 'string' }, { prim: 'bytes' }], annots: ['%token_info'] },
      ],
    },
  ],
  annots: ['%token_metadata'],
};
```

**Comment by mbouaziz** [comment]
Cross-reference: https://gitlab.com/tezos/tezos/-/issues/2707

The `/script/normalized` RPC does two normalizations:
- `storage` data (using the `unparsing_mode`)
- one for `storage` and `parameter` types (_it removes non-entrypoint annotations_, and **this is new**) (`unparsing_mode` has no effects)

To get the original types use the `/script` RPC.

I suggest:
- not change the new protocol proposal
- better document this normalization
- maybe provide a `/code` RPC that would return the `code` field of the `/script` RPC

Let me know whether that suits you

**Comment by roxaneletourneau** [comment]
We were using the `script` entrypoint before Hangzhou, but we moved to `../script/normalized` for the only reason that global constants are expanded in `../script/normalized` and not in `.../script`. See: https://github.com/ecadlabs/taquito/issues/1114
We could switch back to `script`, but we will need an alternative to expand the global constants.

However, we also depend on the` .../entrypoints `endpoint to build the contract abstraction, and annotations are removed in this one.

**Comment by roxaneletourneau** [comment]
[4844](https://gitlab.com/tezos/tezos/-/merge_requests/4844), [4876](https://gitlab.com/tezos/tezos/-/merge_requests/4876), [4893](https://gitlab.com/tezos/tezos/-/merge_requests/4893) brought back the annotations in `.../entrypoints` and it appears that the global constants are expanded in the response from `.../script`. Thank you @mbouaziz 

With this change regarding global constants expansion, when adding support for the J protocol in Taquito, we can start using `.../script` again instead of `../script/normalized` to retrieve contract code.

**Comment by roxaneletourneau** [comment]
Related to https://github.com/ecadlabs/taquito/issues/1532
