### ISSUE TITLE
Estimating fee, gas limit, and storage limit does not work with estimate.reveal() 

### ISSUE THREAD

**Issue by ellingtonsu** [ecadlabs/taquito#1458]
**Description**
I attempted to estimate fee, gas limit, and storage limit with estimate.reveal(). An in-memory signer with an unrevealed account is applied and return 500 (Internal Server Error) with error message 'empty_implicit_contract' which indicates this account is not revealed.

**Steps To Reproduce**
1. Prepare a throw-away account which is not revealed.
2. Create a TezosToolkit with an in-memory signer using the private key of the throw-away account.
3. Call TezosToolkit.estimate.reveal()

**Expected behavior**
An estimate object with fee, gas limit, and storage limit estimation is returned

**Screenshots**
![螢幕擷取畫面 2022-03-14 164352](https://user-images.githubusercontent.com/4967808/158136039-cfead6b8-46ac-4b3c-b5e3-b974b85b099f.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - IDE: VSCode

**Additional context**
Sameple code as 
```
const TezosToolkit = require('@taquito/taquito').TezosToolkit;
const InMemorySigner = require('@taquito/signer').InMemorySigner;

const Tezos = new TezosToolkit("https://hangzhounet.api.tez.ie")
Tezos.setProvider({ signer: new InMemorySigner(unrevealedSK) });

async function testAPI() {
  est = await Tezos.estimate.reveal();
  if(est === undefined) {
    console.log('reveal is not required...')
  } else {
    console.log("reveal suggest fee / mutez :",est.suggestedFeeMutez);
    console.log('reveal: gasLimit', est.gasLimit);
    console.log('reveal: storageLimit',est.storageLimit);
  }
}

testAPI();
```

**Comment by roxaneletourneau** [comment]
Hi @ellingtonsu 
The `empty_implicit_contract` error is thrown not because the account is unrevealed, but because the balance of it is 0. 

> No manager operations are allowed on an empty implicit contract.
https://tezos.gitlab.io/api/errors.html

The solution would be to transfer some tokens to the throw-away account before doing the estimation.

**Comment by ellingtonsu** [comment]
Thanks! By the way, is there any way to estimate fee, gas limit, storage limit without signer for dry-run?

**Comment by roxaneletourneau** [comment]
No, not with the latest version (11.2.0). A signer is needed to run an estimate because its public key hash is used to prepare the operations correctly (ie.: fetch the right counter).

In the next version (12.0.0), it will be possible to run an estimate using the pkh of a configured wallet if there is no signer configured on the TezosToolkit.

**Comment by ellingtonsu** [comment]
Thanks. I will close this issue. Since this is not a bug, is it possible to remove 'bug' label?
