### ISSUE TITLE
Fail to decode Map having ticket as value

### ISSUE THREAD

**Issue by roxaneletourneau** [ecadlabs/taquito#1497]
I am trying to read a ticket on a storage (using taquito v11.2.0)

Here is the stack
![image](https://user-images.githubusercontent.com/2536368/161709889-1e2a3338-8ac0-40fc-bdfa-d746aafeee4f.png)

```
 Typecheck(val: any) {
    if (this.root instanceof BigMapToken && Number.isInteger(Number(val))) {
      return true;
    }
    try {
      this.root.EncodeObject(val);
```

```
  public EncodeObject(_args: any): any {
    throw new EncodeTicketError();
  }
```

Are ticket encoding implemented ?

_Originally posted by @zamrokk in https://github.com/ecadlabs/taquito/issues/550#issuecomment-1088404173_

**Comment by zamrokk** [comment]
As workaround, I manually get ticket info from script.storage field on the contract

**Comment by zamrokk** [comment]
@roxaneletourneau When do you think this bug can be fixed ? Still have the problem :/

**Comment by roxaneletourneau** [comment]
@zamrokk We made a fix in version 14, can you confirm if it still occurs with this version?
Can you share the contract addresses causing the issue?

**Comment by roxaneletourneau** [comment]
Thank you @zamrokk :) 
Closing the issue, please reach out if there is anything else!
