### ISSUE TITLE
react-script new version not compatible with taquito

### ISSUE THREAD

**Issue by danoshi** [ecadlabs/taquito#1544]
*Description*
Hi, I started a fresh react project and after adding Taquito I get this error

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default. This is no longer the case. Verify if you need this module and configure polyfill for it.

I was surprised because other projects that run on react and Taquito work perfect. After I compared dependencies the difference was in my older projects "react-scripts": "4.0.3", and in my fresh created "react-scripts": "5.0.0",
Changing react-scripts back to 4.0.3 solved the problem.
I guess Taquito did not update yet as v5.0.0  was published not long ago on 2021-12-14 according to the announcement
https://github.com/facebook/create-react-app/releases

**Comment by roxaneletourneau** [comment]
Closing as this will be addressed in #1528

**Comment by danoshi** [comment]
Ok thank you, do you have any timeline for that?

**Comment by roxaneletourneau** [comment]
I can not give a specific date at the moment, but it is something we would like to prioritize soon, maybe in version 12.2.

**Comment by BearCooder** [comment]
Hey @roxaneletourneau whats current ETA here for the addresses issue? I saw its addressed in https://github.com/ecadlabs/taquito/issues/1528 and I see version 13.0 is now out :)
