### ISSUE TITLE
Corrections needed for new taquito website

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taquito#1594]
There are some minor typos to fix on the new Taquito website:

front page

1.  "We Believe You Deserve Great Developer Experience"  ->  "We Believe You Deserve A Great Developer Experience"
2.  "Teams Building With Taqueria" -> ""Teams Building With Taquito"

**Comment by dsawali** [comment]
The alignment for objects in the footer uses a lot of white space and is vertical or horizontal alignment is somewhat inconsistent. Could be worth looking into making it 'cleaner', up for discussion

**Comment by Innkst** [comment]
Start now vs. Get started is ok
Let's fix the typos fast and we could discuss the spacing too

**Comment by michaelkernaghan** [comment]
There are two links in the "who builds with Taquito" that need changing

https://www.radion.fm/  -> can't be reached

link to Tezos Domains should be : https://app.tezos.domains/

**Comment by dsawali** [comment]
The navbar also has no clear borders as opposed to the footer which does. I feel like we should be doing either all borders or no borders for design language consistency

**Comment by HamidGoudarzi1988** [comment]
> There are three links in the "who builds with Taquito" that need changing
> 
> https://www.radion.fm/ -> can't be reached https://cryptocodeschool.in/tezos/ -> domain no longer registered to cryptocodeschool.in
> 
> The link to Tezos Domains should be: https://app.tezos.domains/

could you please provide the correct links and related logo screenshot, thanks

**Comment by Innkst** [comment]
Twitter link should be https://t.me/tezostaquito
