### ISSUE TITLE
SPIKE: Design Better error pattern

### ISSUE THREAD

**Issue by carte7000** [ecadlabs/taquito#160]
As of v5.1.0 Taquito's errors are not well defined and are inconsistent.

- [ ] We must define a strategy for our error schema and make them part of our API.
For instance, some error from the RPC are just plain object and other packages returns an Error instance. By applying a consistent approach to errors, the developer experience will improve.
- [ ] Double check if errors are informative and actionable
- [ ] Create follow-up issues based on the design.

**Comment by jevonearth** [comment]
Some progress made in 5.2.0-beta.1 but still more to do.

**Comment by carte7000** [comment]
#225 is related

**Comment by Innkst** [comment]
#363 is related

**Comment by Innkst** [comment]
related #1091

**Comment by dsawali** [comment]
Some custom error classes are not documented properly in Typedoc, we should make an improvement to better explain what the error classes are.

**Comment by dsawali** [comment]
created #1472 to do preliminary evaluation on our error handling

**Comment by dsawali** [comment]
created #1506 as a continuation to #1472

**Comment by roxaneletourneau** [comment]
Error improvement has been done in version 12.1. 
Keeping the issue open to validate if all the comments have been addressed.

**Comment by roxaneletourneau** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Taquito-Development-Team-60ca841c87ca580010057707/issues/ecadlabs/taquito/160?planning-poker) with Zenhub @dsawali @hui-an-yang @zainen

**Comment by roxaneletourneau** [comment]
Here is a plan to improve the errors: https://hackmd.io/oxQqthGlRnWEk8hUADoZgg?both

**Comment by roxaneletourneau** [comment]
Follow up issues created
