### ISSUE TITLE
Operation cancellation

### ISSUE THREAD

**Issue by carte7000** [ecadlabs/taquito#161]
It has been suggested that we could allow cancellation of operation in the mempool before the operation gets included a block.

Example of the suggestion:

```
const promise = Tezos.contract.originate({ ...payload}, cancellationToken)
cancellationToken.cancel()
const op = await promise
assert(op.cancelled === true)
```

**Comment by jevonearth** [comment]
AFAIK it is not possible to cancel/remove, this would need to be a supported feature of the Tezos node. 

Closing this ticket, but if the feature is ever implemented in a new Tezos protocol, we should re-open this issue.
