### ISSUE TITLE
Rollup support - RpcClient

### ISSUE THREAD

**Issue by roxaneletourneau** [ecadlabs/taquito#1617]
Add support for the new RPC endpoints related to rollup:
- ../<block_id>/context/tx_rollup/<tx_rollup_id>/state ([GET](https://tezos.gitlab.io/jakarta/rpc.html#get-block-id-context-tx-rollup-tx-rollup-id-state))
  Example response:
  ```
  { "last_removed_commitment_hashes": null,
  "finalized_commitments": { "next": 0 },
  "unfinalized_commitments": { "next": 0 },
   "uncommitted_inboxes": { "next": 0 }, "commitment_newest_hash": null,
  ["tezos_head_level": null, "burn_per_byte": "0",
  "allocated_storage": "4000", "occupied_storage": "0", "inbox_ema": 0,
  "commitments_watermark": null }
  ```
- ../<block_id>/context/tx_rollup/<tx_rollup_id>/inbox/<block_level>
  Example: https://jakartanet.ecadinfra.com/chains/main/blocks/head/context/tx_rollup/txr1YTdi9BktRmybwhgkhRK7WPrutEWVGJT7w/inbox/0

**Comment by roxaneletourneau** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Taquito-Development-Team-60ca841c87ca580010057707/issues/ecadlabs/taquito/1617?planning-poker) with ZenHub @dsawali @zainen

**Comment by dsawali** [comment]
P.S. the integration test being written for this ticket does not include mondaynet. Due to the weekly resets, we would have to originate and create our own data for `txr1` addresses on mondaynet. Since the features in Taquito are still in progress, we do not have that capability. See #1660
