### ISSUE TITLE
Support txr1 in the local forger

### ISSUE THREAD

**Issue by roxaneletourneau** [ecadlabs/taquito#1642]
**Is your feature request related to a problem and use case? Please describe.**
In jakarta, the types address and contract can store a rollup address txr1.

**Describe the solution you'd like**
Add support for txr1 in the addressEncoder, pkhEncoder, pkhDecoder and addressDecoder methods which will currently throw an error because they only support tz1, tz2, tz3 and/or KT1 addresses.

**Comment by roxaneletourneau** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Taquito-Development-Team-60ca841c87ca580010057707/issues/ecadlabs/taquito/1642?planning-poker) with ZenHub @dsawali @zainen

**Comment by zainen** [comment]
@roxaneletourneau just wondering about the pkh for a txr1 
is there a pk for it? the txr1 is the pkh right? and the txr1 from my understanding wouldnt have a pk since its not a user address right?

**Comment by roxaneletourneau** [comment]
Closing this ticket as it won't be implemented. In a transaction, the destination can't be a txr1 address.
