### ISSUE TITLE
Update J protocol integration tests to include mondaynet endpoint after features are completed

### ISSUE THREAD

**Issue by dsawali** [ecadlabs/taquito#1660]
Currently most features that are being developed in J protocol have integration tests in place, but not all have integration tests that can be pointed to mondaynet. 

Mondaynet resets every week, meaning that we would have to create data on the fly as we run the integration tests. Once the Jakarta features are in place, update relevant integration tests to point to mondaynet.

Notable issues:
- #1617 

Please feel free to update notable issues/tickets to keep track of the integration tests we would need to write.

**Comment by roxaneletourneau** [comment]
I am not sure if this ticket is still relevant. it looks like the TORU operations are already disabled on mondaynet.
