### ISSUE TITLE
Update unit tests for Tx Rollup operations and operation responses

### ISSUE THREAD

**Issue by dsawali** [ecadlabs/taquito#1662]
Update unit tests periodically as more examples are produced on the chain for the following operations:

- [x] OperationContentsTxRollupOrigination 
- [x] OperationContentsTxRollupSubmitBatch
- [x] OperationContentsTxRollupCommit
- [ ] OperationContentsTxRollupReturnBond - to separate into an issue. We don't have an example of this yet. - moved to #1887 
- [x] OperationContentsTxRollupFinalizeCommitment
- [x] OperationContentsTxRollupRemoveCommitment (see onshfiuvBT2CCyuYMwdjQYqmdNoAKTSHkRNryZcuepwdGQgHcfw, block 302396)
- [x] OperationContentsTxRollupRejection
- [x] OperationContentsTxRollupDispatchTickets (see opTaTahvmWWtGC6h7DTdYmGC4Nx5FScEyaP8MWyqVALpvK8HDNm in block 263188: https://jakartanet.ecadinfra.com/chains/main/blocks/263188/)
- [x] OperationContentsTransferTicket

**Comment by roxaneletourneau** [comment]
We can keep an eye on this address https://jakarta.tzstats.com/tz1MDU45gNc9Ko1Q9obcz6hQkKSMiQRib6GZ#transfers for the remaining operation examples.

**Comment by roxaneletourneau** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Taquito-Development-Team-60ca841c87ca580010057707/issues/ecadlabs/taquito/1662?planning-poker) with ZenHub @dsawali @zainen

**Comment by roxaneletourneau** [comment]
An example for tx_rollup_rejection can be found on jakartanet in [block 457911](https://jakartanet.ecadinfra.com/chains/main/blocks/457911/) operation hash: op6bktW5cUyxcMB85xE2zPurufmH9WCEwFUDb6nqyDTey4pBVtA

**Comment by hui-an-yang** [comment]
Thanks for letting me know, will add unit test accordingly:)
