### ISSUE TITLE
Rollup operation support: Contract and Estimate APIs (part 2)

### ISSUE THREAD

**Issue by roxaneletourneau** [ecadlabs/taquito#1680]
Add support to estimate and inject the new operation kind transfer_ticket. Add support to the batch API as well.

For reference: Support for other operations added in #1616 

Note: To test the feature it implies that we need to first transfer tickets on the layer 2 and withdraw them.

See:
-  https://gitlab.com/tezos/tezos/-/merge_requests/5058 with a first draft of what can be seen as a walkthrough of what the rollup node can be used to do
- https://tezos-dev.slack.com/archives/C01SF8V04AG/p1654614681916309
- https://docs.google.com/document/d/1x_5_vtEvZGzevPyJDh28as9w7sS2t_CUPYEYbJH1T-4/edit#heading=h.4d821lkifzzy
- https://docs.google.com/document/d/1qClVJk0suSmgZtnjw4d8JCBBHkEPoNjeH-TJzXG-Pzk/edit#heading=h.sr0pql583a1x

**Comment by roxaneletourneau** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Taquito-Development-Team-60ca841c87ca580010057707/issues/ecadlabs/taquito/1680?planning-poker) with ZenHub @dsawali @zainen

**Comment by dsawali** [comment]
@zainen https://github.com/ecadlabs/taquito/issues/1684#issuecomment-1189328900
