### ISSUE TITLE
Exploration: transfer ticket on the layer 2 and back to layer 1

### ISSUE THREAD

**Issue by roxaneletourneau** [ecadlabs/taquito#1684]

**Comment by roxaneletourneau** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Taquito-Development-Team-60ca841c87ca580010057707/issues/ecadlabs/taquito/1684?planning-poker) with ZenHub @dsawali @zainen

**Comment by dsawali** [comment]
Have been continuously trying to go through [this documentation](https://gitlab.com/tezos/tezos/-/blob/lthms@tx-rollup-getting-started/docs/jakarta/transaction_rollups.rst) for TORU using various testnets and methodologies (locally built client, Docker container)

Currently consulting protocol team to test on Dailynet and am reaching out to an individual from Functori that was successful in transferring tickets from L2 to L1.

**Comment by dsawali** [comment]
After consulting with the protocol team, we were able to successfully withdraw tickets from L2 to L1. The process had been documented [here](https://hackmd.io/@dsawali/BkDhBWFtc)

**Comment by dsawali** [comment]
To further support TORU we consulted Thomas from the protocol team again to give us a crash course on transferring/withdrawing tickets in L2 via the RPC.

The main concern now is to craft the transaction, which is a list of operations in L2 that can be either a **withdrawal** or a **transfer**.

Some relevant links to help out with implementing in Taquito: 
- https://gitlab.com/tezos/tezos/-/blob/master/src/proto_013_PtJakart/lib_protocol/tx_rollup_l2_batch.ml
- https://gitlab.com/tezos/tezos/-/blob/master/src/proto_013_PtJakart/lib_protocol/tx_rollup_l2_batch.mli
- https://gitlab.com/tezos/tezos/-/blob/master/src/proto_013_PtJakart/lib_tx_rollup/l2_transaction.ml
- https://gitlab.com/tezos/tezos/-/blob/master/src/proto_013_PtJakart/lib_tx_rollup/l2_transaction.mli

Endpoint in L2 to facilitate operation injection is defined as follows: https://gitlab.com/tezos/tezos/-/blob/master/src/proto_013_PtJakart/lib_tx_rollup/RPC.ml#L656

Note that before we are able to withdraw/transfer tickets we need to deposit them first. Depositing can be done by calling a smart contract that deposits tickets to an L2 address. See https://gitlab.com/tezos/tezos/-/blob/master/tezt/tests/contracts/proto_alpha/tx_rollup_deposit.tz
