### ISSUE TITLE
Sometimes operations are ignored and confirmation() fails with "confirmation polling timed out"

### ISSUE THREAD

**Issue by 852Kerfunkle** [ecadlabs/taquito#1690]
Hello,

Basically, sometimes operations don't seem to be accepted by rpc nodes and they time out with "confirmation polling timed out" after some minutes.

**Steps To Reproduce**
The easiest way to reproduce this seems to be to send an operation with insufficient gas (manually reduce the gas limit in temple to 20% of the estimate):

```js
const batch_op = await some_wallet_operation_batch.send();
const op_res = await batch_op.confirmation(); // throws "confirmation polling timed out"
const op_status = await batch_op.status();
// check status etc
```

**Expected behavior**
I'd expect to get some kind of error when the operation is rejected by the rpc node. (I think that's what's happening here - not sure).

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chromium
 - Version: 12.1

**Comment by claudebarde** [comment]
Most of the time, when this error happens, it means that the node took longer than expected to send the confirmation.
You can change the timeout value this way:
```
const Tezos = new TezosToolkit(RPC_URL);
Tezos.setProvider({
    config: { streamerPollingIntervalMilliseconds: VALUE_IN_MILLISECONDS }
});
```
in order to give more time to Taquito to wait for a response.

**Comment by 852Kerfunkle** [comment]
@claudebarde I assume you meant `confirmationPollingTimeoutSecond`?

Thing is, the operation is never even added to the mempool (I think) - so I could set the timeout to hours and it would still happen.

If it seems convoluted to force a failure by setting the gas way too low, it's just a way I managed to to find to reproduce this behaviour. It does seem to happen in the wild - but it's difficult to reproduce. It's conceivable increasing the timeout might help there, I suppose.

**Comment by Innkst** [comment]
@852Kerfunkle do you still experience this issue or configuring timeout helped? Thanks

**Comment by 852Kerfunkle** [comment]
@Innkst I just assumed the timeout would make it fail faster, but I feel that's just a workaround for the underlying issue here.

I didn't look at the details, but I would assume (maybe incorrectly) the node would give some kind of error when it plainly rejects an operation - it certainly does sometimes, just not in this case. I don't know if this is an RPC node issue or a taquito issue, but it sure is an issue that I occasionally experience under "normal" circumstances.

**Comment by 852Kerfunkle** [comment]
Oh, by the way - if my memory serves me right, it's also reproducible in a flextesa sandbox.

**Comment by OjusWiZard** [comment]
Hi everyone, I have been facing this error at every run in my code. It seems like I've found a way to recreate this issue.
I've created a script [here](https://github.com/OjusWiZard/Plenty-API) to reproduce this error, hoping that someone can help resolve this issue.

**Comment by dvkam** [comment]
I am experiencing this odd behaviour too. I started the shifumi game from [Marigold](https://github.com/marigold-dev/training-dapp-shifumi)  and when I try to submit a tx with Temple it always happens (I switched rpc too) , just like 852Kerfunkle said `Thing is, the operation is never even added to the mempool (I think) - so I could set the timeout to hours and it would still happen.` I experience the same. However when I switch to Kukai it works.

**Comment by hui-an-yang** [comment]
Hello @852Kerfunkle 
Thank you for bringing this up to us, we're looking to understand it better and hopefully resolve this issue.
I reproduced this bug by decreasing the gas_limit like you mentioned and it turned out that Kuaki is returning a `insufficient_gas_for_manager` error which is expected behaviour but temple do just hang there and can't resolve. 
Form the first look, it can be how temple is dealing with pre-apply operation error response didn't resolve it or reflect the error to user. (might need to look into their code to confirm
You also mentioned that it can be reproduce in flextesa can you provide more context for us to investigate?

**Comment by hui-an-yang** [comment]
Hello @852Kerfunkle, @dvkam, @OjusWiZard  

I've done more investigation on this that I realized the temple `Gas fee` that let you adjust value of is actually `fee` not `gasLimit`. I tried even with octez-client when it comes to low fee operations they can get injected but was never confirmed. Here's the [documentation](https://tezos.gitlab.io/protocols/003_PsddFKi3.html#baker) of how without minimum fee the operation won't propagate into a block. If you configure your TezosToolkit with [marigold rpc ur](https://ghostnet.tezos.marigold.dev/) and tried to reproduce this behaviour that you'll see the operations in the reject section [of mempool_operation ](https://nairobinet.tezos.marigold.dev//chains/main/mempool/pending_operations). 
We'll appreciate that you try this out and let us know if this will resolve this issue many people have :)

Side note that Kukai seem to enforce the fee that they calculated for users even that you tried to change in advanced mode it doesn't show in operations object at all.

Looking forward to hear back from you

**Comment by hui-an-yang** [comment]
Hi @852Kerfunkle 

Thanks for replying, those are great question!
Screenshot below is a list of reasons that an operation won't propagate into a block, I believe those you saw in the wild will belong to one of them. 
For the fact that the accessibility of a mempool is node dependent, it's a technical difficulty for taquito to returned the refused message and abort the search early for now. (don't think it's reasonable to only abort the search for those rpc node have mempool public access either)
I have raised this behaviour to tezos core developer team to see if they're willing to improve on a protocol level. 
Will keep you updated when I hear back from them, hope this is helpful :)

<img width="1062" alt="image" src="https://github.com/ecadlabs/taquito/assets/106410553/54fa98e0-ac7f-43ca-81fb-8802a0ebee0f">

**Comment by 852Kerfunkle** [comment]
> For the fact that the accessibility of a mempool is node dependent
I see. That does make it complicated.

> Will keep you updated when I hear back from them, hope this is helpful :)
Very, thank you :)

Also, congratulations for getting to the bottom of this one!
