### ISSUE TITLE
live code examples in docs on Wallet API page - try temple wallet gets error about bad parameters

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taquito#1698]
in temple docs, on the Wallets API page
try the live code example "Try Temple Wallet"

using f12 dev tools you can see there is an error about the parameters passed by the example code.

**Comment by roxaneletourneau** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Taquito-Development-Team-60ca841c87ca580010057707/issues/ecadlabs/taquito/1698?planning-poker) with ZenHub @dsawali @zainen
