### ISSUE TITLE
Wallet not opening, "_proto" is read-only

### ISSUE THREAD

**Issue by Riyenz** [ecadlabs/taquito#1705]
**Description**

**Steps To Reproduce**
1. Connect Wallet on Ithacanet
2. Run the code below.
```
Tezos.wallet
  .batch([
    {
      kind: 'transaction',
      to: 'KT1CZMHskePxx8xgDwNfvfdAdDCUoE9jMzbA',
      amount: 0,
      mutez: false,
      parameter: {
        entrypoint: 'approve',
        value: {
          prim: 'Pair',
          args: [
            { string: 'KT193W4yQZXLwLfW6wzvgVdUYncnC5imvWUq' },
            { int: '0' },
          ],
        },
      },
    },
    {
      kind: 'transaction',
      to: 'KT1CZMHskePxx8xgDwNfvfdAdDCUoE9jMzbA',
      amount: 0,
      mutez: false,
      parameter: {
        entrypoint: 'approve',
        value: {
          prim: 'Pair',
          args: [
            { string: 'KT193W4yQZXLwLfW6wzvgVdUYncnC5imvWUq' },
            { int: '110' },
          ],
        },
      },
    },
    {
      kind: 'transaction',
      to: 'KT193W4yQZXLwLfW6wzvgVdUYncnC5imvWUq',
      amount: 0,
      mutez: false,
      parameter: {
        entrypoint: 'deploy_FA1_vesting',
        value: {
          prim: 'Pair',
          args: [
            {
              prim: 'Pair',
              args: [
                { string: 'tz1fxojJcp9viALhishZ34pkmnHgEwiies3p' },
                {
                  prim: 'Pair',
                  args: [
                    [
                      {
                        prim: 'Elt',
                        args: [
                          { string: 'tz1fxojJcp9viALhishZ34pkmnHgEwiies3p' },
                          { int: '100' },
                        ],
                      },
                    ],
                    { int: '3589' },
                  ],
                },
              ],
            },
            {
              prim: 'Pair',
              args: [
                { int: '31536000' },
                {
                  prim: 'Pair',
                  args: [
                    { prim: 'True' },
                    { string: 'KT1CZMHskePxx8xgDwNfvfdAdDCUoE9jMzbA' },
                  ],
                },
              ],
            },
          ],
        },
      },
    },
  ])
  .send();
```

**Expected behavior**
Expected Behavior is to open a wallet to confirm the transaction.

**Screenshots**
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/31911993/174471156-adc4902b-41d8-46f5-907a-6f515a44304a.png">

**Desktop (please complete the following information):**
 - Firefox, Chrome

**Smartphone (please complete the following information):**
 - Macbook Pro 13inch

**Additional context**
N/A

**Comment by claudebarde** [comment]
The error in the first screenshot seems to suggest that you are trying to forge the transaction with an account that hasn't been revealed yet.
If you give me the address, I can check it for you and reveal it if necessary so you can use it :)

**Comment by Riyenz** [comment]
HI @claudebarde,

here's the contract address `KT193W4yQZXLwLfW6wzvgVdUYncnC5imvWUq` then I'm using this address `KT1CZMHskePxx8xgDwNfvfdAdDCUoE9jMzbA` as fake token when calling `deploy_FA1_vesting` in `vested_token_address`.

Thank you for your assistance, I appreciate it a lot.

**Comment by claudebarde** [comment]
I am sorry, I meant the address of the implicit account you are using to sign the transaction.
I got it from your screenshot (`tzlfV0angAfb9J1hRRMP2bSB6LvASD6KpY8A`) and it says it wasn't revealed in the explorer, so it cannot work.
https://ithacanet.tzkt.io/tzlfV0angAfb9J1hRRMP2bSB6LvASD6KpY8A/operations/

**Comment by Riyenz** [comment]
I tried again with a revealed address (https://ithacanet.tzkt.io/tz1gncPPFVkzaWVAoe57RRVZ3np3db1qdXoQ/info), but still getting the same error. So we can discard this hypothesis. Any idea on what that error might be due to ? It’s really blocking. I’m using next.js btw

**Comment by claudebarde** [comment]
I hardly believe you still get an `empty_implicit_account` with a revealed and funded account. You must be signing the transaction with another account that is not revealed, for example, the one I mentioned in my previous comment and that is included in the error message itself (and still not revealed).

**Comment by tbinetruy** [comment]
Hi!

I'm confirming the `empty_implicit_account` error is now indeed gone! However, that `_proto is readonly` error remains. It's really weird as it only happens when running against the testnet. Any idea what's going on ? What in your code could make this attribute readonly ? That sounds very weird as it's cleary being mutated here: https://github.com/ecadlabs/taquito/blob/080483a8189ba0c2c8a7cebf018e2b68e7edb56a/packages/taquito/src/forger/taquito-local-forger.ts#L14.

Do you think it could somehow be due to next.js?

Thanks for your help.

**Comment by claudebarde** [comment]
I don't think it is mutated but instantiated instead. As you can see [in this file](https://github.com/ecadlabs/taquito/blob/080483a8189ba0c2c8a7cebf018e2b68e7edb56a/packages/taquito/src/context.ts), the `_proto` property is private, which means that TypeScript will prevent you from overwriting it.
Are you trying to modify it?

**Comment by tbinetruy** [comment]
Hi, sorry for the late reply.

I'm not at all trying to modify it. Somewhere in your library code is the variable trying to get mutated. But not by us. Again, it works fine against the mainnet somehow. We're just switching networks. And again, the same code works when build in prod mode using next.js, but not in dev mode. 

So I assume you've never encountered or heard of anything similar behavior ?

**Comment by dsawali** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Taquito-Development-Team-60ca841c87ca580010057707/issues/ecadlabs/taquito/1705?planning-poker) with Zenhub @hui-an-yang @roxaneletourneau @zainen

**Comment by hui-an-yang** [comment]
Hi @Riyenz & @tbinetruy 

Thanks for reaching out. We are looking into the issue you encountered, tried recreating the bug doesn't seem possible from my end at the moment.  Would be helpful to know what's next.js & taquito version you use. Also the ticket is opened in June would like to know if it's still the case now? Hope to help to sort this out soon :)

**Comment by Innkst** [comment]
Can't reproduce
