### ISSUE TITLE
Extension not detected consistently

### ISSUE THREAD

**Issue by karimkawambwa** [ecadlabs/taquito#1706]
**Description**

Using @taquito/beacon-wallet@13.0.0

When using localhost, initializing the Beacon SDK with as a DappClient, then starting a pairing request directly afterwards, extensions, such as Temple Wallet and Spire, are not always detected when they are installed.

**Steps To Reproduce**

1 - Start project on your local machine with localhost domain.
2 - Initialize wallet connection.
3 - Notice temple wallet says not installed.

**Expected behavior**

Expected the wallet option to be available.

**Screenshots**

<img width="986" alt="Screen Shot 2022-06-21 at 9 43 59 AM" src="https://user-images.githubusercontent.com/4308339/174796575-0f36fb65-5a4a-4f32-b5ac-7d2e1ec28d32.png">

**Desktop (please complete the following information):**
 - Browser chrome
 - Version 102.0.5005.115 (Official Build) (arm64)

**Additional context**

Seems similar to this issue
https://github.com/airgap-it/beacon-sdk/issues/259

**Comment by claudebarde** [comment]
Unfortunately, Taquito has no control over this as the `@taquito/beacon-wallet` package is just a wrapper for the Beacon SDK.  
I would suggest you contribute to the issue you mentioned by reposting this in the issue comments.

**Comment by karimkawambwa** [comment]
Noted with thanks @claudebarde
