### ISSUE TITLE
Loaded FA121 contract doesn't have a 'do' method 

### ISSUE THREAD

**Issue by Sarodh** [ecadlabs/taquito#171]
I'm  trying to follow the test for Babylon/005: [integration-tests/manager-contract-scenario](https://github.com/ecadlabs/taquito/blob/master/integration-tests/manager-contract-scenario.spec.ts)

Working with the FA121 contract here: https://assets.tqtezos.com/quickstart/2-index
Loading the deployed contract then inspecting the methods only shows a "main" method taking 12 arguments. According to the parameterSchema those 12 arguments are a mapping of all the contract methods by index.

**Comment by jevonearth** [comment]
Thanks for trying out Taquito!

Can you provide me with the address of the contract? I presume it is deployed in babylonnet testnet?

I can't seem to find the contract source code at the above link either. Can you provide that to be also?

**Comment by jevonearth** [comment]
In the https://assets.tqtezos.com/quickstart/2-index the contract `KT1RUhPAABRhZBctcsWFtymyjpuBQdLTqaAQ` is originated, we loaded this contract from babylonnet using the latest release of Taquito, and it works for us as expected.

If you can provide me with some code examples, that would be helpful, and can you also let me know what version of Taquito you are using.

Thank you @Sarodh

**Comment by Sarodh** [comment]
Contract address: `KT1NoXksDfuR97NPoGTfegnkWiTPw5EmwHcB`
Library version: `"@taquito/taquito": "5.1.0-beta.1"`

`this.contract = await Tezos.contract.at(this.address);`

Contract object: 
`
Contract {
  address: 'KT1NoXksDfuR97NPoGTfegnkWiTPw5EmwHcB',
  script: {
    code: [ [Object], [Object], [Object] ],
    storage: { prim: 'Pair', args: [Array] }
  },
  provider: RpcContractProvider {
    context: Context {
      _rpcClient: [RpcClient],
      _signer: [InMemorySigner],
      _proto: undefined,
      _config: [Object]
    },
    estimator: RPCEstimateProvider {
      context: [Context],
      DEFAULT_PARAMS: [Object]
    }
  },
  entrypoints: {
    unreachable: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object]
    ],
    entrypoints: {}
  },
  methods: { main: [Function: method] },
  schema: Schema {
    root: PairToken {
      val: [Object],
      idx: 0,
      fac: [Function: createToken],
      createToken: [Function: createToken]
    },
    bigMap: BigMapToken {
      val: [Object],
      idx: 0,
      fac: [Function: createToken],
      createToken: [Function: createToken]
    }
  },
  parameterSchema: ParameterSchema {
    root: OrToken {
      val: [Object],
      idx: 0,
      fac: [Function: createToken],
      createToken: [Function: createToken]
    }
  }
}
`

`const schema = Object.values(this.contract.parameterSchema.ExtractSchema());`

Schema: 
`[
  { '0': 'address', '1': 'address', '2': 'nat' },
  { '1': 'address', '2': 'address', '3': 'address', '4': 'nat' },
  { '2': 'address', '3': 'nat' },
  { '3': 'address', '4': 'address', '5': 'nat' },
  { '4': 'address', '5': 'address', '6': 'contract' },
  { '5': 'address', '6': 'contract' },
  { '6': 'unit', '7': 'contract' },
  'bool',
  'address',
  { '9': 'unit', '10': 'contract' },
  { '10': 'address', '11': 'nat' },
  { '11': 'address', '12': 'nat' },
  'address'
]`

**Comment by jevonearth** [comment]
Thanks, we will investigate.

**Comment by jevonearth** [comment]
@Sarodh Confirming this as a bug for the case that a contract does not have annotations. We should have a fix, tests and new release for this out tomorrow. Thank you so much for the report.

**Comment by Sarodh** [comment]
Thanks, appreciate the fix.

**Comment by jevonearth** [comment]
@Sarodh You can use the `next` version now, and see if that works for you. 

We will update some of our internal projects, and all going well, push a proper release probably tomorrow.

**Comment by jevonearth** [comment]
Fixed in 5.2.0-beta.1
Closing. Thanks for the help @Sarodh
