### ISSUE TITLE
Accept `amount`, `fee`,  `gasLimit` and `storageLimit` as paramaters of the `withContractCall` method

### ISSUE THREAD

**Issue by roxaneletourneau** [ecadlabs/taquito#1717]
**Is your feature request related to a problem and use case? Please describe.**
It is not possible to specify the `amount`, the `fee`, the `gasLimit` and the `storageLimit` when calling a smart contract entrypoint using the batch API via the `withContractCall` method.

**Describe the solution you'd like**
Add an additional parameter to the `withContractCall` that will allow users to optionally specify an `amount`, `fee`, `gasLimit` and/or `storageLimit`.

Document the new parameter on the website: https://tezostaquito.io/docs/batch_API#--the-withcontractcall-method

**Describe alternatives you've considered**
Currently, to specify those parameters, users can use the `withTransfer` as a workaround: 
`.withTransfer({...contract.methods.deposit(null).toTransferParams({ amount:1, mutez:true })})`

**Comment by Innkst** [comment]
This is addressing https://github.com/ecadlabs/taquito/issues/1716

**Comment by hui-an-yang** [comment]
addressed in pr#2021, has merged in master https://github.com/ecadlabs/taquito/pull/2021
