### ISSUE TITLE
USER STORY: Add documentation feedback to Taquito website

### ISSUE THREAD

**Issue by Innkst** [ecadlabs/taquito#1732]
**As Taquito user, I want to provide Taquito team with the feedback, so that they know which pages are the most helpful**
How helpful Taquito documentation is by chapter, including TypeDoc**

## Acceptance criteria:
1. User can give feedback on any documentation page for Taquito including TypeDoc

## Implementation notes:
See https://github.com/ecadlabs/docusaurus-feedback
Implementation of google analytics and event is reporting here: https://analytics.google.com/analytics/web/#/realtime/rt-event/a93014135w303602453p260865178/. 

Everything was reimplemented with the built-in docusaurus infima styles, so everything will work nicely with night/day mode etc
Should be able to copy the 'theme' folder into the 'src' directory of any docusaurus project - and rebuild, it should add the new functionality to all docs pages (but not static content like the front page).
Firebase instance and ga account are defined in the firebase.js and top of the AddFeedback.tsx respectively.

**Comment by roxaneletourneau** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Taquito-Development-Team-60ca841c87ca580010057707/issues/ecadlabs/taquito/1732?planning-poker) with ZenHub @dsawali @hui-an-yang @zainen
