### ISSUE TITLE
Investigate Event feature

### ISSUE THREAD

**Issue by roxaneletourneau** [ecadlabs/taquito#1741]
Investigate the upcoming Event feature from the K protocol.

**Describe the solution you'd like**
- Deploy a contract having an event (note: will need to use the RpcForger rather than the LocalForger until EMIT instruction is supported)
  - https://gitlab.com/tezos/tezos/-/blob/master/tests_python/contracts_alpha/opcodes/emit.tz
  - https://gitlab.com/tezos/tezos/-/blob/master/src/proto_alpha/lib_protocol/test/integration/michelson/contracts/emit.tz
- Trigger the event by making a call to the originated contract.
- Read the event execution details from the transaction results of the operation. It should look like this:
```
{
  "protocol": "ProtoALphaALphaALphaALphaALphaALphaALphaALphaDdp3zK",
  "hash": "opNX59asPwNZGu2kFiHFVJzn7QwtyaExoLtxdZSm3Q3o4jDdSmo",
  // ... fields elided for brevity
  "contents": [
    {
      "kind": "transaction",
      // ... fields elided for brevity
      "metadata": {
        // ... fields elided for brevity
        "internal_operation_results": [
          {
            "status": "applied",
            // ... fields elided for brevity
            "source": "KT...",
            "destination": "ev1...",                            // <~
            "parameters": {                                     // <~
              "entrypoint": "event_tag...",                     // <~
              "value": {                                        // <~
                "prim": "Right",                                // <~
                "args": [                                       // <~
                  {                                             // <~
                    "string": "right"                           // <~
                  }                                             // <~
                ]                                               // <~
              }                                                 // <~
            }                                                   // <~
          }
        ]
      }
    }
  ]
}
```

**Additional context**
[Add any other context or screenshots about the feature request here.](https://tezos.gitlab.io/alpha/event.html)

**Comment by roxaneletourneau** [comment]
> Jason Ridgway-Taylor has prepared test data for events on Kathmandunet (see thread). Hopefully this helps with integration as well!
> 2 replies
> Fedor
>   [9:41 AM]
> The event data is from the mock staking contract we have as part of our upcoming demo and blog post which uses a mint/burn mechanims to emit a pair of nats that represent an exchange rate.
> Structure of the operations includes an event which is a pair of nats:
> bash
>   Internal operations:
>         Internal Event:
>           From: KT1Q51TfSvZ7a6PNKiPhUs2CKpG3G1Eh7Cpf
>           Type: (pair (nat %evxtz) (nat %xtz))
>           Tag: xrate
>           Payload: (Pair 11 30)
>           This event was successfully applied
>           Consumed gas: 1000
> The RPC structure will be of the form:
> json
>   "internal_operation_results": [
>                             {
>                                 "kind": "event",
>                                 "source": "KT1Q51TfSvZ7a6PNKiPhUs2CKpG3G1Eh7Cpf",
>                                 "nonce": 0,
>                                 "type": {
>                                     "prim": "pair",
>                                     "args": [
>                                         {
>                                             "prim": "nat",
>                                             "annots": [
>                                                 "%evxtz"
>                                             ]
>                                         },
>                                         {
>                                             "prim": "nat",
>                                             "annots": [
>                                                 "%xtz"
>                                             ]
>                                         }
>                                     ]
>                                 },
>                                 "tag": "xrate",
>                                 "payload": {
>                                     "prim": "Pair",
>                                     "args": [
>                                         {
>                                             "int": "11"
>                                         },
>                                         {
>                                             "int": "30"
>                                         }
>                                     ]
>                                 },
>                                 "result": {
>                                     "status": "applied",
>                                     "consumed_milligas": "1000000"
>                                 }
>                             }
>                         ]
> 						
> Example data exists on the following operational hashes.
> Operation hashes:
> bash
> oopn3ZhwZAntH3JahEw4TJ7n5uAKJhisJF3x9fhmEENyz7iAgJ7  Mint 1
> opNLo2axupTrLHD1oEG3Lx3ypiYU6BknEBV6B3CfGZPc3BzxUV3  Mint 1
> oot116nfmuRh6gncfy5uTbPpgKEwcdR4Jo9GMMrrgZLeKzqy4p1  Mint 16
> ony7WzzRqVEHw9SiG2ZjHyi5kEwoWaG2ygj4Sx4GszdQtReE67x  Mint 5
> op3V1AS1wL68YW2Rf7i7N6Jv65v5BP3N1bUGHzoTcCXuCfXiwt1  Burn 1
> ooToMtN8xBdHEkDxy2u18NPr1HA9KL69kgQzaVFMhGuZ83KTCTV  Mint 1
> opB5gkYaumcShdV7LgAs48Fyqa1NK3EpxaL47sPWF5u2oENLHAW  Burn 10

**Comment by roxaneletourneau** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Taquito-Development-Team-60ca841c87ca580010057707/issues/ecadlabs/taquito/1741?planning-poker) with ZenHub @dsawali @zainen

**Comment by dsawali** [comment]
A quick update on the investigation. 
- This is the most up-to-date event feature documentation: https://tezos.gitlab.io/alpha/event.html

Moving forward there will be no notion of an `ev1` address for events (until further notice). In consequence, we will be closing Taquito issues related to supporting `ev1` addresses
