### ISSUE TITLE
rollup operation support transactions/operations portion contract & estimation 

### ISSUE THREAD

**Issue by zainen** [ecadlabs/taquito#1756]
continuation from #1755 following #1680 

add ability to create transactions on L2 in the rollup node 

using the RollupRpcClient to interact with L2 for operation additions. 

ability to estimate the operations fees and results. 

ability to complete a transaction within the L2 rollup node after creation of L2 address and before Transfer back to L1

**Comment by zainen** [comment]
@roxaneletourneau made this when splitting the work anticipating doing multiple operations for tx_rollups should we just close this?

**Comment by roxaneletourneau** [comment]
Those would be great:
- add the ability to create transactions on L2 in the rollup node
- using the RollupRpcClient to interact with L2 for operation additions.
but I am not sure if we will get there. We will probably prioritize SCORU instead.
But let's keep it open for now.

**Comment by michaelkernaghan** [comment]
Closing this as the decision has been taken to not fully support all the L2 things. Other issues capture what will be changed.
