### ISSUE TITLE
`Schema.generateSchema()` fails for `sapling_transaction_deprecated`

### ISSUE THREAD

**Issue by psmolinsky** [ecadlabs/taquito#1763]
**Description**
If michelson contains `sapling_transaction_deprecated`, then method `generateSchema()` of corresponding `Schema` fails.

**Steps To Reproduce**

1. Create `Schema`:
    ```typescript
    const schema = new Schema({
        "prim": "sapling_transaction_deprecated",
        "args": [{ "prim":"8" }]
    });
    ```
2. Call the method:
    ```typescript
    schema.generateSchema();
    ```
3. It throws an error:
    ```
    Invalid token error: Malformed data expected a value with a valid prim property
        at createToken (..\node_modules\@taquito\michelson-encoder\src\tokens\createToken.ts:23:11)
        at new Schema (..\node_modules\@taquito\michelson-encoder\src\schema\storage.ts:119:17)
        at Object.<anonymous> (..\index.ts:16:12)
    ```

**Additional context**
Such schema is present for example in parameter schema of `KT1BUZy6xNbmo5ogfD7nDRMBspfG1EEFfDFW` on mainnet.

**Comment by roxaneletourneau** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Taquito-Development-Team-60ca841c87ca580010057707/issues/ecadlabs/taquito/1763?planning-poker) with ZenHub @dsawali @hui-an-yang @zainen
