### ISSUE TITLE
Support new operation Increase_paid_storage on the Wallet API

### ISSUE THREAD

**Issue by roxaneletourneau** [ecadlabs/taquito#1768]
**Is your feature request related to a problem and use case? Please describe.**
Increase_paid_storage is a new operation that enables a payer to increase the paid storage of a smart contract by some bytes amount. 

```
{ /* Increase_paid_storage */
         "kind": "increase_paid_storage",
         "source": $Signature.Public_key_hash,
         "fee": $014-PtKathma.mutez,
         "counter": $positive_bignum,
         "gas_limit": $positive_bignum,
         "storage_limit": $positive_bignum,
         "amount": $bignum,
         "destination": $014-PtKathma.contract_id.originated }
```

**Describe the solution you'd like**
- Add support for the operation in the `Wallet` class.

**Additional context**
https://gitlab.com/tezos/tezos/-/merge_requests/5605

**Comment by dsawali** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Taquito-Development-Team-60ca841c87ca580010057707/issues/ecadlabs/taquito/1768?planning-poker) with Zenhub @hui-an-yang @roxaneletourneau @zainen
