### ISSUE TITLE
[Bug] PollingSubscribeProvider used in contract confirmations might skip blocks

### ISSUE THREAD

**Issue by dsawali** [ecadlabs/taquito#1783]
The `PollingSubscribeProvider` is utilized in a couple instances internally to help poll blocks when confirming operations.

Currently there are 2 different behaviours of confirmations (Wallet and Contract).

- In Wallet operation confirmations, the `PollingSubscribeProvider` has a check to throw an error (MissedBlockDuringConfirmationError) when the confirmation misses/skips a block
- In Contract, the `PollingSubscribeProvider` does not check whether a block was missed or skipped, and would just ignore or timeout

We should make these behaviours consistent across wallet and contract. There are 2 options to what we could do to improve user experience:
- Throw a similar error in contract as we do in wallet for consistency, or
- Ensure missed/skipped blocks are refetched and returned to the user during confirmation

**Comment by Innkst** [comment]
Related issue #1050

**Comment by roxaneletourneau** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Taquito-Development-Team-60ca841c87ca580010057707/issues/ecadlabs/taquito/1783?planning-poker) with Zenhub @dsawali @hui-an-yang @zainen
