### ISSUE TITLE
"balance" property for contract origination is a string

### ISSUE THREAD

**Issue by claudebarde** [ecadlabs/taquito#1795]
In the parameters to pass in order to originate a new contract, the `balance` property is a string.
https://tezostaquito.io/typedoc/modules/_taquito_taquito.html#originateparamsbase
It would be more intuitive and easier to use if it were ~a `number` or at least~ a union `string | number`. The property is also in tez, which raises the question about how to pass mutez values like `10_567_324`.

**Comment by roxaneletourneau** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Taquito-Development-Team-60ca841c87ca580010057707/issues/ecadlabs/taquito/1795?planning-poker) with Zenhub @dsawali @hui-an-yang @zainen

**Comment by roxaneletourneau** [comment]
@claudebarde  

> The property is also in tez, which raises the question about how to pass mutez values like 10_567_324.

There is a `mutez` property that can be set to true if we want to pass a balance in mutez.
