### ISSUE TITLE
Binding generator for smart contract abstractions 

### ISSUE THREAD

**Issue by carte7000** [ecadlabs/taquito#181]
A tool that generates types/interfaces from Michelson. This would give a developer the appropriate types required to interact with a specific contract.

A command-line tool would be ideal, that can produce Typescript bindings (specific to Taquito would be nice) or ReasonML bindings. Other languages/libraries could be added.

These bindings would save the developer from manually writing their own types. The CLI could be used/invoked in the developer's toolchain as the contract types evolve.

**Comment by kinokasai** [comment]
Based on some discussion with @phlalx (Philippe B.), we were thinking about having a separate program generating interface files for both Reason and Typescript. Remains to determinate what to use to program that. We were thinking maybe OCaml, cause some stuff is already written - it may still need to be extracted.

**Comment by jevonearth** [comment]
Sounds great @kinokasai I edited the Issue to better reflect the goals. This will be very useful.

**Comment by jevonearth** [comment]
Closing, see #418
