### ISSUE TITLE
Switch project to use eslint instead of tslint

### ISSUE THREAD

**Issue by carte7000** [ecadlabs/taquito#183]
Switch to [eslint](https://eslint.org/), remove tslint (it is deprecated) from project

* Turn on `no-any` tslint rules. Having this rule would ensure that we type everything in Taquito while it is a good thing for the quality of the library itself.
* Update `.vscode/extensions.json` to use ESLint over TSLint
* While we are at it, review the other extension in `.vscode/extensions.json` and update accordingly.

**Comment by jevonearth** [comment]
Superseded by #460
