### ISSUE TITLE
Runtime type assertions on calls via the contract abstraction/storage encoding.

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taquito#184]
We should assert types in Taquito instead of deferring this to the RPC.

The Tezos RPC expects all properties to be encoded as strings `prop: "1"` Vs `prop: 1`. Taquito can add value by checking that inputs are valid before calling out to the RPC. 

When a string is passed to a taquito abstracted entrypoint that expects a `nat`, we will coerce it to a `number` and check that it is `>= 0`.

If a user wants to bypass this checking, they have the ability to use the "injectable semantic action" so a taquito user can either remove the checks or provide their own. Useful for the situation where we try to do the right thing, but it's not the right thing. 
 
- [ ] Find all other cases where validation should be added
- [ ] Add validation (where reasonable) and document the changes

**Comment by carte7000** [comment]
#211 is a first start to runtime type assertions

**Comment by jevonearth** [comment]
Related to #94 and #13

**Comment by jevonearth** [comment]
Closing, refer to #418 which is expected to address the needs here.
