### ISSUE TITLE
Support calling contract entrypoint without explicitly referring to an entrypoint

### ISSUE THREAD

**Issue by jchenche** [ecadlabs/taquito#1843]
Assume we have the Michelson Contract below:
```
{ parameter (or (or (int %decrement) (int %increment)) (unit %reset)) ;
  storage int ;
  code { UNPAIR ;
         IF_LEFT { IF_LEFT { SWAP ; SUB } { ADD } } { DROP 2 ; PUSH int 0 } ;
         NIL operation ;
         PAIR } }
```
We can increment the contract by calling the entry point with explicit mention of the entry point name `Increment 3` or we can do `(Left (Right 3))` which doesn't explicitly mention one.

The LIGO compiler only outputs Michelson parameter in the second case. It'd be nice if Taquito has a way to take in `(Left (Right 3))` directly and pass it to the RPC.

**Comment by roxaneletourneau** [comment]
Taquito supports it already. Here is an example:
```
const exp = { "prim": "Left", "args": [{ "prim": "Right", "args": [{ "int": "2" }] }] };
const op = await Tezos.contract.transfer({
        to: 'KT1P6FAUBASWrdfPfc2q5nBgUnmDMdQ8YMDx',
        amount: 0,
        parameter: {
          entrypoint: 'default',
          value: exp
        },
})

await op.confirmation();
```
