### ISSUE TITLE
Investigate and fix build failures for Node versions above 16.13.1

### ISSUE THREAD

**Issue by dsawali** [ecadlabs/taquito#1845]
Currently Taquito will not build properly with Node version exceeding 16.13.1.

Investigate and fix the cause of the build failures so we can keep the Taquito project up to date with the most recent Node LTS.

**Comment by roxaneletourneau** [comment]
Update the README when fixed: https://github.com/ecadlabs/taquito/pull/2002

**Comment by RichAyotte** [comment]
Seems to build fine with v19.5.0.

![image](https://user-images.githubusercontent.com/294987/221422605-649ba15c-6e4b-400a-9107-090f4e24ca74.png)

@dsawali can you provide more detail on what you encountered?
