### ISSUE TITLE
[Website] Fix feedback component theme

### ISSUE THREAD

**Issue by Innkst** [ecadlabs/taquito#1856]
The newly integrated feedback component doesn't have proper styling for mobile views. 
![File](https://user-images.githubusercontent.com/16856119/185501913-4431a286-ed05-4906-ab6f-35e84616b799.jpg)

- Update the color on the component to fit the website color scheme:
   - Left thick line and the button can be the same color as the buttons for GitHub and signup in the footer  
<img width="233" alt="image" src="https://user-images.githubusercontent.com/73142875/186770101-2afb5594-4f68-451f-bd03-725001af3d44.png">
   - Background to match a selected tab in the live code examples 
<img width="108" alt="image" src="https://user-images.githubusercontent.com/73142875/186770235-b2fda6c5-56b9-4922-af0f-eba680398426.png">

**Comment by roxaneletourneau** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Taquito-Development-Team-60ca841c87ca580010057707/issues/ecadlabs/taquito/1856?planning-poker) with Zenhub @dsawali @hui-an-yang @zainen
