### ISSUE TITLE
Integration/unit tests for OperationContentsTxRollupReturnBond 

### ISSUE THREAD

**Issue by Innkst** [ecadlabs/taquito#1887]
- [ ] OperationContentsTxRollupReturnBond - We don't have an example of this yet.

**Comment by roxaneletourneau** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Taquito-Development-Team-60ca841c87ca580010057707/issues/ecadlabs/taquito/1887?planning-poker) with Zenhub @dsawali @hui-an-yang @zainen
