### ISSUE TITLE
Local Forging fails for timestamps

### ISSUE THREAD

**Issue by impactdni2** [ecadlabs/taquito#1888]
**Description**
The default forger (Local Forging) fails to properly encode timestamp values.  A contract method with a single timestamp parameter fails to encode properly.

**Steps To Reproduce**
- Create a contract with a "set_something(timestamp)" method.
- Confirm Taquito sees it as a timestamp `toTransferParams()`, and `getSignature()`
`{
  ..snipped..
  parameter: {
    entrypoint: 'set_something',
    value: { string: 2022-09-06T16:52:13.000Z }
  }
}`
`[ 'timestamp' ]`
- Call the method passing Date.now()
- Taquito throws an exception:
`The contract call failed and the following error was returned: Failed to encode michelson value '[object Object]' UnexpectedMichelsonValueError: Failed to encode michelson value '[object Object]'
    at valueEncoder ([removed]/node_modules/@taquito/local-forging/dist/taquito-local-forging.umd.js:449:13)
    at parametersEncoder ([removed]/node_modules/@taquito/local-forging/dist/taquito-local-forging.umd.js:926:26)
    at [removed]/node_modules/@taquito/local-forging/dist/taquito-local-forging.umd.js:1118:29
    at Array.reduce (<anonymous>)
    at [removed]/node_modules/@taquito/local-forging/dist/taquito-local-forging.umd.js:1106:19
    at Object.encoders.<computed> [as transaction] ([removed]/node_modules/@taquito/local-forging/dist/taquito-local-forging.umd.js:1223:95)
    at [removed]/node_modules/@taquito/local-forging/dist/taquito-local-forging.umd.js:1090:75
    at [removed]/node_modules/@taquito/local-forging/dist/taquito-local-forging.umd.js:1114:79
    at Array.reduce (<anonymous>)
    at [removed]/node_modules/@taquito/local-forging/dist/taquito-local-forging.umd.js:1114:36 {
  value: { string: 1662575448078 }
}`
- Works using non-local forger:
`const rpcForger = tezos.getFactory(RpcForger)();
tezos.setForgerProvider(rpcForger);`

**Expected behavior**
Shouldn't throw an exception on Timestamps...

**Desktop (please complete the following information):**
- node v16.17.0
- taquito 13.0.0

**Additional context**
This came up on a (rarely used) script that was working properly on 11.2, but failing after upgrading to 13.0 (confirmed to also be failing on 12.0, likely when the change to local-forging by default was made?

**Comment by roxaneletourneau** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Taquito-Development-Team-60ca841c87ca580010057707/issues/ecadlabs/taquito/1888?planning-poker) with Zenhub @dsawali @hui-an-yang @zainen
