### ISSUE TITLE
Ledger signer connect raises error taquito-ledger-signer 

### ISSUE THREAD

**Issue by jorick33** [ecadlabs/taquito#1907]
When simply trying to connect the ledger to get publicKeyHash I get the following error

![image](https://user-images.githubusercontent.com/245119/190011018-d075fb80-1c84-484e-8591-88552a7912f6.png)

Here are my lines of code:

`           const Tezos = new TezosToolkit(NODE)

            const transport = await TransportWeb.create();
            const ledgerSigner = new LedgerSigner(transport);

            Tezos.setProvider({ signer: ledgerSigner });
            const publicKeyHash = await Tezos.signer.publicKeyHash();
            console.log(publicKeyHash)`

From my package.json:

`"@ledgerhq/hw-transport-webhid": "^6.27.2",
  "@taquito/ledger-signer": "^14.0.0",
  "@taquito/taquito": "^14.0.0",`

I tried on Linux, Max & Windows, with Chrome & Safari. Always got the same issue.

Could you please overlook it?

Or tell me where I'm wrong.

Best,

**Comment by roxaneletourneau** [comment]
We tried in the same reported condition and are not having the problem. 
What kind of ledger is it?
What version wallet app the device has?
Did you try different mnemonics? If so, are you always getting the error?

**Comment by jorick33** [comment]
It seems I found the issue. I was from my end. I updated my react from 16.4 to 18 and webpack to 5. It was requesting to include polyfill for packages crypto, stream, http... So I ended up setting a config overrides as follow

`const webpack = require('webpack');
const ModuleScopePlugin = require('react-dev-utils/ModuleScopePlugin');

module.exports = function override(config) {
    const fallback = config.resolve.fallback || {};
    fallback.fs = false
    Object.assign(fallback, {
        "crypto": require.resolve("crypto-browserify"),
        "stream": require.resolve("stream-browserify"),
        "path": require.resolve("path-browserify"),
        "os": require.resolve("os-browserify"),
        "https": require.resolve("https-browserify"),
        "http": require.resolve("stream-http"),
        "url": require.resolve("url"),
        "assert": require.resolve("assert"),
    })
    config.resolve.fallback = fallback;
    //config.ignoreWarnings = [/Failed to parse source map/];
    config.plugins = (config.plugins || []).concat([
        new webpack.ProvidePlugin({
            process: 'process/browser',
            Buffer: ['buffer', 'Buffer']
        })
    ])
    config.resolve.plugins = config.resolve.plugins.filter(plugin => !(plugin instanceof ModuleScopePlugin));
    return config;
}
`

However, even if now the "stream" dependency was pointing to "stream-browserify", "stream" package was still in my package.json and node_modules.

I'm not sure whyt, but when I removed the stream dependency from package.json and resinstalled, everything started to wok properly...

So I guess when updating to webpack 5, we have to make sure to remove "non-browserify" dependencies

**Comment by roxaneletourneau** [comment]
Yes, webpack 5 no longer does auto-polyfilling for node core modules. I am closing the issue but don't hesitate to reach out if there is anything else.
