### ISSUE TITLE
Question: llibsodium-wrappers dep in beacon-wallet

### ISSUE THREAD

**Issue by xsfunc** [ecadlabs/taquito#1924]
Why you use libsodium-wrappers@0.7.9 dependency in beacon-wallet package? 
How I see beacon wallet is just wrapper for dapp-client.

**Comment by jevonearth** [comment]
The beacon team is going to remove the libsodium dependency soon. They are switching from libsodium to stablelib. Somehting we already did in Taquito. As soon as the new version of beacon is released, we will update.

JFYI; here's the relevant PR: https://github.com/airgap-it/beacon-sdk/pull/387
