### ISSUE TITLE
combine the two contract origination scripts in the examples folder

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taquito#1937]
There are two scripts in the examples folder that both originate contracts needed for tests.
There only needs to be one script.

Include the integration tests script into the live code in the docs example script.

**Comment by roxaneletourneau** [comment]
We have a script to deploy the known contracts in the integration tests folder: https://github.com/ecadlabs/taquito/blob/master/integration-tests/originate-known-contracts.ts

And one in the example folder: https://github.com/ecadlabs/taquito/blob/master/example/deploy-integration-tests-contracts.ts

We can delete the one in the example folder.
