### ISSUE TITLE
Support SORU operations from Kathmandu

### ISSUE THREAD

**Issue by psmolinsky** [ecadlabs/taquito#1953]
Taquito 14 already supports the Kathmandu protocol, but many SORU-related operations are missing (according to [block schema](https://tezos.gitlab.io/kathmandu/rpc.html#get-block-id)). Can you please support them at least in `@taquito/rpc`?

- dal_slot_availability
- dal_publish_slot_header
- sc_rollup_originate
- sc_rollup_add_messages
- sc_rollup_cement
- sc_rollup_publish
- sc_rollup_refute
- sc_rollup_timeout
- sc_rollup_execute_outbox_message
- sc_rollup_recover_bond
- sc_rollup_dal_slot_subscribe

**Comment by Innkst** [comment]
These were not added because SCORU is not officially supported till protocol M.

**Comment by psmolinsky** [comment]
Hi, so Taquito 16 with Mumbai support i out. However, it is still missing following operations. Why please?

- smart_rollup_publish
- smart_rollup_cement
- smart_rollup_recover_bond
- smart_rollup_refute
- smart_rollup_timeout

**Comment by dsawali** [comment]
Hey there, the operations that you mentioned relies on communication from Taquito to L2.

Taquito as it stands right now remain an L1 library, so supporting them would require quite a large paradigm shift. While we aren't opposed to the change, we'd like to plan accordingly.

**Comment by dsawali** [comment]
I would probably have to add that when I said 'supporting' I meant support and features to inject said operations.

But we can definitely add support for Taquito to be able to read those ops from the node. @psmolinsky

**Comment by psmolinsky** [comment]
Hi @dsawali, I understand that adding L2 support is a bigger task. For me, it is completely enough to add these operations to RPC block as far as we are building [indexer framework](https://dappetizer.dev/).

**Comment by dsawali** [comment]
Awesome, thanks for understanding @psmolinsky. We'll create a ticket to update that and we'll keep you posted.

**Comment by michaelkernaghan** [comment]
This issue should be closed as it is replaced with this other newer issue here:
