### ISSUE TITLE
Add a contractCall method on the RPCEstimateProvider class

### ISSUE THREAD

**Issue by roxaneletourneau** [ecadlabs/taquito#2019]
Follow up of #432 

**Is your feature request related to a problem and use case? Please describe.**

ContractAbstraction - Estimating a contract method call is less convivial than for the other operations. It requires additional steps that could be abstracted (transform arguments into Michelson, run the estimation as a transfer operation)

Existing Solution:
```
const contract = await Tezos.contract.at('KT1HN6wQquJDFBvRH4Tsbx9SVazK7KzHXZYs')
const param = contract.methods.increment(7).toTransferParams({});
const estimation = Tezos.estimate.transfer(param);
```

**Describe the solution you'd like**

As a user, I want an intuitive API that allows estimating the fees associated with a contract method call.
A contractCall method will be added to the RPCEstimateProvider class. It will take a ContractMethod as a parameter as follow:
```
const contractAbs = await TezosToolkit.contract.at('address');
const op = contract.methods.increment(1)
const estimate = await TezosToolkit.estimate.contractCall(op);
```

**Additional context**
https://www.notion.so/ecad/Design-refactor-contract-API-8cbcd324414d475bbe2d667e86fc188c

**Comment by dsawali** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Taquito-Development-Team-60ca841c87ca580010057707/issues/ecadlabs/taquito/2019?planning-poker) with Zenhub @hui-an-yang @roxaneletourneau @zainen

**Comment by dsawali** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Taquito-Development-Team-60ca841c87ca580010057707/issues/ecadlabs/taquito/2019?planning-poker) with Zenhub @AlirezaHaghshenas
