### ISSUE TITLE
Doc: The signing lifecycle

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taquito#204]
Create a new doc that explains signing life-cycles and what dApp developers should be aware of.

The typical expectation is that signing requests come back quickly, but with multi-sig signing, or other signing schemes, the signing process can take days. dApp developers would need to make a choice to support such types of life-cycles.

**Comment by claudebarde** [comment]
This is now available here: https://tezostaquito.io/docs/signing/

**Comment by michaelkernaghan** [comment]
Closing the issue as the signing page has been created here: https://tezostaquito.io/docs/signing/
