### ISSUE TITLE
Michel Codec - Support LAMBDA_REC + fix TICKET instructions

### ISSUE THREAD

**Issue by roxaneletourneau** [ecadlabs/taquito#2075]
**Is your feature request related to a problem and use case? Please describe.**
1 - Add support to properly validate the code of a contract having the `LAMBDA_REC` instruction in the michel-codec package.

2- TICKET instruction now returns option ticket 'a instead of ticket 'a

**Describe the solution you'd like**
1 - Add a case for the `LAMBDA_REC` instruction in the `retStack` constant: https://github.com/ecadlabs/taquito/blob/master/packages/taquito-michel-codec/src/michelson-typecheck.ts#L889

>  LAMBDA_REC 'a 'b code: Push a lambda with itself on top of the
>  code, recursively, with the given parameter type 'a and return a value of type   'b onto the stack (if it terminates before gas exhaustion).
> 
> ```
> :: 'A ->  (lambda 'a 'b) : 'A
>    iff code::'a: (lambda 'a 'b):[] -> 'b:[]
> 
> > LAMBDA_REC 'a 'b code / S  => {LAMBDA_REC 'a 'b code; code} : S
> ```

2- Add a condition for the `TICKET` instruction in the `retStack` constant to ensure that an optional ticket is returned for the Lima protocol.

Add relevant unit tests. Consider creating a contracts_015 folder containing all tests for the L protocol (as is the case for the other protocols already).

Contract examples:
- https://gitlab.com/tezos/tezos/-/blob/master/src/proto_015_PtLimaPt/lib_protocol/test/integration/michelson/contracts/fail_rec.tz
- https://gitlab.com/tezos/tezos/-/blob/master/src/proto_015_PtLimaPt/lib_protocol/test/regression/contracts/rec_id_unit.tz
- https://gitlab.com/tezos/tezos/-/blob/master/src/proto_015_PtLimaPt/lib_protocol/test/integration/michelson/contracts/omega.tz
- https://gitlab.com/tezos/tezos/-/blob/master/src/proto_015_PtLimaPt/lib_protocol/test/integration/michelson/contracts/rec_fact_apply.tz
- https://gitlab.com/tezos/tezos/-/blob/master/src/proto_alpha/lib_protocol/test/integration/michelson/contracts/rec_fact_store.tz
- https://gitlab.com/tezos/tezos/-/blob/master/src/proto_015_PtLimaPt/lib_protocol/test/integration/michelson/contracts/rec_fact.tz
- https://gitlab.com/tezos/tezos/-/blob/master/src/proto_015_PtLimaPt/lib_protocol/test/integration/michelson/contracts/rec_fact_apply_store.tz

**Additional context**

**Comment by roxaneletourneau** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Taquito-Development-Team-60ca841c87ca580010057707/issues/ecadlabs/taquito/2075?planning-poker) with Zenhub @dsawali @hui-an-yang @zainen

**Comment by arvidj** [comment]
Hello, will this also fix the forging errors related to TICKETs? In TeCI, I'm seeing forgingMismatch errors for integration tests running against protocol alpha using the TICKET instruction. I guess this is related to the changed type of the TICKET instruction in lima:

> Disallow creation, transfer and storage of tickets with zero amounts. TICKET instruction now returns option ticket 'a instead of ticket 'a. For contracts already originated, their TICKET instructions are renamed to TICKET_DEPRECATED. Note that it is not possible to originate contracts containing TICKET_DEPRECATED after the migration. (MR !5963)

https://tezos.gitlab.io/protocols/015_lima.html 

Indeed, the new  `TICKET` is encoded by `0x9a`. The old instruction is renamed `TICKET_DEPRECATED` and is still encoded `0x88`. Experimenting using `octez-codec` (https://tezos.gitlab.io/developer/encodings.html):

``` 
$ ./octez-codec encode 014-PtKathma.script.expr from '{"prim":"TICKET","args":[]}'
0388
$ ./octez-codec encode 015-PtLimaPt.script.expr from '{"prim":"TICKET","args":[]}'
039a
$ ./octez-codec encode 015-PtLimaPt.script.expr from '{"prim":"TICKET_DEPRECATED","args":[]}'
0388
```

**Comment by roxaneletourneau** [comment]
Hi @arvidj,
The following ticket fixed the mismatch error in the integration tests: https://github.com/ecadlabs/taquito/issues/2072.
Changes related to Lima are not merged to master before quorum is reached. We are working on the lima branch here: https://github.com/ecadlabs/taquito/pull/2113

**Comment by arvidj** [comment]
> Hi @arvidj, The following ticket fixed the mismatch error in the integration tests: #2072. Changes related to Lima are not merged to master before quorum is reached. We are working on the lima branch here: #2113

Thanks @roxaneletourneau !
