### ISSUE TITLE
SPIKE: Investigate Testnet Dictator

### ISSUE THREAD

**Issue by roxaneletourneau** [ecadlabs/taquito#2078]
> A Testnet Dictator Proposals operation is now mutually exclusive with any other voting operation inside a same block or mempool.

https://tezos.gitlab.io/protocols/015_lima.html#internal

**Comment by dsawali** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Taquito-Development-Team-60ca841c87ca580010057707/issues/ecadlabs/taquito/2078?planning-poker) with Zenhub @hui-an-yang @roxaneletourneau @zainen

**Comment by dsawali** [comment]
After reaching out to Nomadic, it seems that the testnet dictator change is more of an implementation detail. The wording of the changelog made it seem as if it's now 2 separate operations, but that is not the case. More information can be seen in this Slack thread: https://tezos-dev.slack.com/archives/C042S337D9A/p1670953068099369 (might need permission to view)
