### ISSUE TITLE
[SOLVED] Cannot use taquito on Nuxt3

### ISSUE THREAD

**Issue by felixdenoix** [ecadlabs/taquito#2117]
**Description**
When using Nuxt3, importing the module causes an error.
> global is not defined
> at node_modules/readable-stream/lib/_stream_readable.js 

**Steps To Reproduce**
Link to reproduction [repo](https://github.com/felixdenoix/nuxt-taquito-repro)

**Expected behavior**
Should not throw an error. 

**Additional context**
The issue seems related to the fact that vite requires modules to be either ESM or commonjs modules but not a mix of the two.

**Comment by claudebarde** [comment]
Hey! Server-side rendering is always a bit tricky with Taquito"s libraries, Taquito itself does pretty well, but Beacon is another story!
I have never used Vue so I am not sure about the fix for this one, but I had similar issues testing other frameworks. You can try to add `const global = globalThis;` in your HTML file like [in this example](https://github.com/claudebarde/taquito-bundlers-testing/blob/main/vitejs/index.html#L8).
There may also be some way in the Nuxt/Vue configuration to add `global` for SSR like [in this ViteJS example](https://github.com/claudebarde/taquito-bundlers-testing/blob/main/vitejs/vite.config.js#L11).
Let me know if that helps.

**Comment by RichAyotte** [comment]
Like Claude said, it's a Beacon issue. You can turn off server side rendering for now.
In `nuxt.config.ts`
```ts
export default defineNuxtConfig({
	ssr: false,
})
```

**Comment by felixdenoix** [comment]
Thanks for the fast reply !!

> Hey! Server-side rendering is always a bit tricky with Taquito"s libraries, Taquito itself does pretty well, but Beacon is another story! I have never used Vue so I am not sure about the fix for this one, but I had similar issues testing other frameworks. You can try to add `const global = globalThis;` in your HTML file like [in this example](https://github.com/claudebarde/taquito-bundlers-testing/blob/main/vitejs/index.html?rgh-link-date=2022-11-10T08%3A20%3A09Z#L8). There may also be some way in the Nuxt/Vue configuration to add `global` for SSR like [in this ViteJS example](https://github.com/claudebarde/taquito-bundlers-testing/blob/main/vitejs/vite.config.js?rgh-link-date=2022-11-10T08%3A20%3A09Z#L11). Let me know if that helps.

Tried some of the settings and the error changed! I've updated the reproduction repo. As of now the issue is caused by the following error:

>TypeError: Cannot read properties of undefined (reading 'from')
    at generate-uuid.ts:12:21
    at Array.map (<anonymous>)
    at generate-uuid.ts:11:6
    at Generator.next (<anonymous>)
    at generate-uuid.ts:2:29
    at new Promise (<anonymous>)
    at __awaiter2 (generate-uuid.ts:2:29)
    at generateGUID (generate-uuid.ts:7:35)
    at DAppClient.<anonymous> (BeaconClient.ts:110:25)
    at Generator.next (<anonymous>)
    
The file is looked for in the following folder:
`http://localhost:3000/_nuxt/node_modules/@airgap/beacon-utils/src/utils/generate-uuid.ts`
Could the issue be related to a relative path import ?


>Like Claude said, it's a Beacon issue. You can turn off server side rendering for now.
In nuxt.config.ts
> ```ts
> export default defineNuxtConfig({
> 	ssr: false,
> })
> ```
Good catch on that one, its frequently forgotten but the setting is already defined on the app (also tried using the `definePageMeta` method in a dedicated page but without success)

[repro on stackblitz](https://stackblitz.com/github/felixdenoix/nuxt-taquito-repro?file=nuxt.config.ts)

**Comment by RichAyotte** [comment]
Try this.
```ts
export default defineNuxtConfig({
  vite: {
    optimizeDeps: {
      esbuildOptions: {
        define: {
            global: 'globalThis'
        },
        plugins: [
              NodeGlobalsPolyfillPlugin({
                  buffer: true
              })
          ]
      },
    },
    build: {
      target: "esnext",
      commonjsOptions: {
        transformMixedEsModules: true
      },
    },
    resolve: {
      alias: {
        // dedupe @airgap/beacon-sdk
        // I almost have no idea why it needs `cjs` on dev and `esm` on build, but this is how it works 🤷‍♂️
        "@airgap/beacon-sdk": path.resolve(
          path.resolve(),
          `./node_modules/@airgap/beacon-sdk/dist/esm/index.js`
        ),
        // polyfills
        "readable-stream": "vite-compatible-readable-stream",
        stream: "vite-compatible-readable-stream"
      }
    }
  }
})
```

**Comment by felixdenoix** [comment]
With the provided changes, it works well in dev mode :rocket: , but whe building I still have an error about the `Buffer` not being defined
>ReferenceError: Buffer is not defined
    at ls (entry.973dceb2.js:formatted:37011:5)
    at entry.973dceb2.js:formatted:37422:40

**Comment by RichAyotte** [comment]
Ah yes. One more thing. Add the following at the top.
```ts
import inject from '@rollup/plugin-inject'
```

and 

```ts
    build: {
      rollupOptions: {
        plugins: [inject({ Buffer: ['buffer', 'Buffer'] })],
      },
    },
```

I'll edit my answer above if this works.

**Comment by felixdenoix** [comment]
@RichAyotte, many thanks works like a charm !! 
Would you like me to open a pr on some repo so we can persist this effort into something ?

For future reference as of nuxt@3.0.0-rc.13 the configuration

`package.json`
```json
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@esbuild-plugins/node-globals-polyfill": "^0.1.1",
    "@esbuild-plugins/node-modules-polyfill": "^0.1.4",
    "@rollup/plugin-inject": "^5.0.2",
    "buffer": "^6.0.3",
    "events": "^3.3.0",
    "nuxt": "3.0.0-rc.13",
    "vite-compatible-readable-stream": "^3.6.1"
  },
  "dependencies": {
    "@airgap/beacon-sdk": "^3.3.0",
    "@taquito/beacon-wallet": "^14.1.0",
    "@taquito/taquito": "^14.1.0"
  }
}
```
`nuxt.config.ts`
```typescript
import path from 'path'
import { NodeGlobalsPolyfillPlugin } from '@esbuild-plugins/node-globals-polyfill';
import inject from '@rollup/plugin-inject';

export default defineNuxtConfig({

  ssr: false,

  vite: {
    optimizeDeps: {
      esbuildOptions: {
        define: {
            global: 'globalThis',
        },
        plugins: [
          NodeGlobalsPolyfillPlugin({
              buffer: true
          })
        ]
      },
    },
    build: {
      target: "esnext",
      commonjsOptions: {
        transformMixedEsModules: true
      },
      rollupOptions: {
        plugins: [inject({ Buffer: ['buffer', 'Buffer'] })],
      },
    },
    resolve: {
      alias: {
        // dedupe @airgap/beacon-sdk
        "@airgap/beacon-sdk": path.resolve(
          path.resolve(),
          `./node_modules/@airgap/beacon-sdk/dist/esm/index.js`
        ),
        // polyfills
        "readable-stream": "vite-compatible-readable-stream",
        stream: "vite-compatible-readable-stream"
      }
    }
  }

})

```

**Comment by RichAyotte** [comment]
Looks good. Maybe we can add a new section to the docs titled `Using Taquito in Nuxt` similar to [Using Taquito in Mobile environments
](https://tezostaquito.io/docs/mobile_bundle)

Any thoughts on this @claudebarde?

**Comment by RichAyotte** [comment]
The `Cannot call a namespace ('qrcode')` warning will go away once this Beacon [PR](https://github.com/airgap-it/beacon-sdk/pull/397/files#diff-d3c56fe3ed04d414bc620334ff9a61cd0e9db4463103c62c3c22ea993bbdd4fdL1) is merged.

**Comment by Julien-R44** [comment]
More globally, we definitely need a Taquito integration guide with Vite. Every time I set up a new project using Vite and taquito/beacon, it is a **real** nightmare to configure. 

Every other time, the configuration I used on the previous project, doesn't work on the new one 🤷

---

So, I added everything @RichAyotte advised, but I always had an error related to `vite-compatible-readable-stream` when doing a `beacon.client.requestPermissions`. So I added that, and now it works :

```sh
pnpm add -D events process global
```

And add this in my application entrypoint : 
```ts
import global from 'global'
import * as process from "process";

global.process = process;
```

However, I tried removing the three lines I put just above, to make sure that was what fixed the problem. And now it works even without... Don't ask me why, I don't even try to understand why anymore... And I can assure you that it didn't work before.

**Comment by felixdenoix** [comment]
@Julien-R44 in my nuxt project I didn't put anything in the entry point, only in the nuxt config
>And add this in my application entrypoint :
>```
>import global from https://github.com/Raynos/global
>import * as process from ["process"](https://nodejs.org/api/process.html);
>global.process = process;
>```
Have you tried using exactly the same dependencies versions as in the repro ?

**Comment by claudebarde** [comment]
I have a repo I started to test different bundlers with Taquito and Beacon (still a WIP), I updated the Vite config 2 months ago and it was working at that time, I should have a look again to check if it is still the case: https://github.com/claudebarde/taquito-bundlers-testing/tree/main/vitejs
@RichAyotte Tests for SSR with different frameworks like NextJS, Nuxt or SvelteKit are missing and I will put it on my list of todos :)

**Comment by felixdenoix** [comment]
@claudebarde do you want me to make a pr with the version of nuxt that we manage to setup ?

**Comment by claudebarde** [comment]
@felixdenoix That would be great, it would serve as a basis for later tests :)

**Comment by felixdenoix** [comment]
@claudebarde here you go !
https://github.com/claudebarde/taquito-bundlers-testing/pull/2
