### ISSUE TITLE
Remove `@taquito/signer` dependency from `@taquito/taquito`

### ISSUE THREAD

**Issue by carte7000** [ecadlabs/taquito#212]
`@taquito/signer` is increasing our bundle size a lot ~1.1mb while being not necessary for most browser based application. (Removing this make the main taquito bundle ~0.4mb)

The only function that make use of this package is the `Tezos.importKey` function in taquito

We propose to to move this function into the `@taquito/signer` package

```
import { importKey } from `@taquito/signer`

const Tezos = importKey(key)
```

**Comment by carte7000** [comment]
@CruzMolina I think this would be a breaking change for Truffle, do you have any concern about us making that change?

**Comment by CruzMolina** [comment]
@carte7000 I think this will be fine. We'll add the signer pkg separately to the cli & `@truffle/interface-adapter` .

As an aside, is there a package or method that handles creating, activating, and importing valid signed faucet/demo accounts?

**Comment by carte7000** [comment]
Ok awesome, to your other question: we don't have a package that automatically provide faucet key but I think it is a great idea and worth investigating, I will create an issue related to it.

I believe the faucet account are predefined in the genesis block of each test net (I might be wrong)
If that's true it would mean that we could not generate them on the fly.

**Comment by jevonearth** [comment]
Let's do the following:

- Update `Tezos.importKey()` to call `InMemorySigner.importKey()`.
- Mark `Tezos.importKey()` as deprecated.
- In v7, remove `Tezos.importKey()`

**Comment by jevonearth** [comment]
@AndrewKishino Most of this is implemented, see branch `212-remove-signer-from-taquito-core`
