### ISSUE TITLE
Events on ContractAbstraction

### ISSUE THREAD

**Issue by psmolinsky** [ecadlabs/taquito#2128]
**Is your feature request related to a problem and use case? Please describe.**

Please provide metadata about possible events that a contract can emit on `ContractAbstraction`. It is needed when a user wants to know all events upfront, before waiting for them to be emitted. It is especially useful for indexers.

**Describe the solution you'd like**

- Provide event's tag, its schema(s) and maybe also entrypoint(s) that can emit it.
- Something similar to `entrypoints` property.

**Additional context**

[Tezos docs](https://tezos.gitlab.io/alpha/event.html)

**OUT OF SCOPE:**
- Our abstraction will only follow 1 level of smart contract events abstraction, even if there are contract dependencies where one contract with events calls another contract with events.

**Comment by dsawali** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Taquito-Development-Team-60ca841c87ca580010057707/issues/ecadlabs/taquito/2128?planning-poker) with Zenhub @AlirezaHaghshenas @hui-an-yang @zainen
