### ISSUE TITLE
Remove Kathmandu/Proto14 conditions in taquito-local-forging

### ISSUE THREAD

**Issue by hui-an-yang** [ecadlabs/taquito#2131]
Remove the Kathmandu/Proto14 condition that was required for the transition from Kathmandu to Lima

integration-tests/data/allTestsCases.ts
integration-tests/data/code_with_ticket_proto14.ts
integration-tests/local-forging.spec.ts
integration-tests/wallet-edo-deploy-having-ticket.spec.ts
packages/taquito-local-forging/src/proto14-kathmandu/
packages/taquito-local-forging/src/taquito-local-forging.ts
packages/taquito-local-forging/test/michelson/encoder.spec.ts
packages/taquito-local-forging/test/taquito-local-forging.spec.ts

**Comment by dsawali** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Taquito-Development-Team-60ca841c87ca580010057707/issues/ecadlabs/taquito/2131?planning-poker) with Zenhub @hui-an-yang @zainen
