### ISSUE TITLE
encode method of BoolToken not working

### ISSUE THREAD

**Issue by rognierbenoit** [ecadlabs/taquito#214]
The "encode" method  of BoolToken (invoked by Method.send) does not work properly. 

For example
```
const m = contract.methods.my_entry_point(true);
m.send({ fee: 50000, gasLimit: 500000 })
```

generate the RPC parameter `"true"` instead of `{ "prim" : "True"}` (as EncodeObject does ...)

**Comment by carte7000** [comment]
Thanks for reporting the issue @rognierbenoit that's a good catch we will fix it and publish a new release ASAP

**Comment by carte7000** [comment]
@rognierbenoit it should be fixed in this version of Taquito https://www.npmjs.com/package/@taquito/taquito/v/5.3.1-beta.1
