### ISSUE TITLE
Update website from Telegram to Discord

### ISSUE THREAD

**Issue by egarson** [ecadlabs/taquito#2156]
Add Discord icon and link to the left of Telemgram on the website with the goal of transitioning from Telegram eventually.

This ticket is to change the website to reflect the change already made in the README, which is to elide Telegram in favor of Discord where we have better control over bots and so forth.

**Comment by songproducer** [comment]
Hi, the discord link https://discord.com/invite/tURNUPwp is invalid

**Comment by dsawali** [comment]
@songproducer thanks for bringing that to our attention, we'll update the link to have a non-expiring link.
