### ISSUE TITLE
[Chore] Organize integration tests into sub-folders

### ISSUE THREAD

**Issue by dsawali** [ecadlabs/taquito#2203]
With an increasing amount of support we build for Tezos, we also have an increasing amount of tests written. 

To ensure maintainability and efficiency in the development process, we should start organizing the tests categorically based on which part of Taquito it's testing.
It is hard to scroll through the seemingly unending list of tests or know the exact name of the test for the search.

I.e. Contract API support for operations would go in a folder as such:
`integration-tests/contracts/operations/simple-origination.spec.ts`
`integration-tests/contracts/operations/increase-paid-storage.spec.ts`
...

### Solution
Evaluate the integration-tests folder and organize the tests categorically with relevant sub-folders.
The goal is to have a 1 level depth.
Names of the tests are not intuitive either.

In the future, we can run folders of tests in parallel in CI and rerun only failed folders. Create a devops issue for this to follow.

**Comment by hui-an-yang** [comment]
Would be great to also re-evaluated what tests are still relevant can cross reference file to find duplicate and reduce them
