### ISSUE TITLE
Make Unit type less ambiguous

### ISSUE THREAD

**Issue by carte7000** [ecadlabs/taquito#221]
Given a contract with Unit as storage

Currently originating such a contract with `null` (or any truthy value) in the storage property work, but `undefined` don't
Also decoding the storage of such a contract always return `null`

See this commit for a summary of an example of the current behavior
https://github.com/ecadlabs/taquito/commit/9277430439d1655aee0775fe94f218e063c7531d

Using `null` to represent the Unit value is ambiguous as it can have different meaning. 

One solution would be to use a global constant ex: `Taquito.Unit` which would be required while encoding and returned while decoding storage which contains Unit type.

**Comment by jevonearth** [comment]
#248
