### ISSUE TITLE
Mondaynet Tx Rollup transfer ticket integration test set up

### ISSUE THREAD

**Issue by zainen** [ecadlabs/taquito#2220]
add automated workflow for mondaynet tx rollup  every mondaynet reset

deposit tickets L1 -> L2
transfer tickets  L2 -> L2

enough tickets to ensure amount does not run out

then run test to withdraw tickets from L2 to L1 integration test

**Comment by dsawali** [comment]
closing due to TORU now being disabled on Mondaynet
