### ISSUE TITLE
Avoid RPC error when calling importKey

### ISSUE THREAD

**Issue by carte7000** [ecadlabs/taquito#224]
When calling `importKey` Taquito first try to activate the account even if the account as already been activated. This lead to undesirable RPC errors that bubble into the user app.

One solution would be to use the following RPC endpoint `/chains/main/blocks/head/context/raw/json/commitments/{blinded_pkh_keys}`

The blinded public key can be computed by concatenating the `secret` and `pkh` of a faucet key. Then by hashing (using blake2b) and base58 encoding the result

**Comment by michaelkernaghan** [comment]
Importkey was removed:
"#### Remove the deprecated `Tezos.importKey` method from the main Taquito package
We deprecated the top-level `importKey` method last march, and now it’s finally time to remove it. The method continues to be available in the `@taquito/signer` package as usual."
