### ISSUE TITLE
MichelsonMap with option as key

### ISSUE THREAD

**Issue by 852Kerfunkle** [ecadlabs/taquito#2251]
**Description**
I have some maps with options as key (they are comparable: https://tezos.gitlab.io/michelson-reference/#type-option).

I don't quite see how to use None as a key, say in a map from `option string` to `nat`. Maybe we could have either null or undefined added to `MichelsonMapKey`?

Thanks!

**Comment by claudebarde** [comment]
I thought you should use `null` for a `None`value.
Do you have some code for your use case to reproduce the issue? Thanks.

**Comment by 852Kerfunkle** [comment]
It's maybe just an oversight with the TypeScript types. I didn't try with ts-expect-error.

What I need, a `map option address nat`:

```ts
// Type 'string | null' does not satisfy the constraint 'MichelsonMapKey'.
// Type 'null' is not assignable to type
const map: MichelsonMap<string, BigNumber[]> = new MichelsonMap();
map.set(null, new BigNumber(10));
```
