### ISSUE TITLE
Provide the conversion helper functions `toDryRun`, `toForge`

### ISSUE THREAD

**Issue by Innkst** [ecadlabs/taquito#2256]
https://www.notion.so/ecad/Design-refactor-contract-API-8cbcd324414d475bbe2d667e86fc188c

1. Create helper functions toDryRun and toForge
2. Those functions should be used in PrepareProvider.preparedOperation related to dryrun and forge
3. Unit tests and integration tests are created and passing successfully
4. Documentation for the website is created.
5. Example of usage below

**Example of use - Prepare and simulate (dry-run) a transfer operation**

```tsx
const preparedTransfer = await TezosToolkit.prepare.transfer(...);
TezosToolkit.rpc.preapplyOperations(toDryRun(preparedTransfer));
```

**Example of use - Prepare and forge a transfer operation:**

```tsx
const preparedTransfer = await TezosToolkit.prepare.transfer(...);
TezosToolkit.forger.forge(toForge(preparedTransfer));
```

**Example of use - Prepare and simulate (dry-run) a contract method call:**

```tsx
const contractAbs = await TezosToolkit.contract.at('address');
const op = contractAbs.methods.increment(1)
const preparedContractCall = await TezosToolkit.prepare.contractCall(op);
TezosToolkit.rpc.preapplyOperations(toDryRun(preparedContractCall));
```

**Comment by dsawali** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Taquito-Development-Team-60ca841c87ca580010057707/issues/ecadlabs/taquito/2256?planning-poker) with Zenhub @AlirezaHaghshenas @hui-an-yang @zainen
