### ISSUE TITLE
Use the new PrepareProvider class instead of the OperationEmitter class

### ISSUE THREAD

**Issue by Innkst** [ecadlabs/taquito#2257]
For the complete flow of an operation (from its preparation to its injection), use the new PrepareProvider class instead of the OperationEmitter class. The OperationEmitter contains many responsibilities and having it separated into smaller pieces will make the code easier to maintain

Adjust and refactor OperationEmitter's usage in these following tickets, and leverage PrepareProvider where necessary in these following parts of the code:
- [ ] `RpcContractProvider` #2428
- [ ] `RpcBatchProvider` #2429
- [ ] `RpcTzProvider` #2430 
- [ ] `RpcEstimateProvider` #2431

Note that the changes have to be **_NON-BREAKING_** and backwards compatible

**Comment by dsawali** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Taquito-Development-Team-60ca841c87ca580010057707/issues/ecadlabs/taquito/2257?planning-poker) with Zenhub @AlirezaHaghshenas @hui-an-yang @zainen
