### ISSUE TITLE
Consider upgrading to rxjs version 7

### ISSUE THREAD

**Issue by sirrocco** [ecadlabs/taquito#2261]
**Description**
RxJS V7 is out for a couple of years now and 8 is coming soon-ish - would you consider upgrading to it? 

It's blocking the upgrade of other libraries.

Thank you.

**Acceptance criteria:**
* Play with an upgrade in a branch
* Explore if we can avoid the TS upgrade. The idea is to not upgrade TS, but upgrade rxjs to the highest version we have. Upgrading with TS at the same time is more risky, so if we can upgrade one and then another, it would be better and easier to downgrade if required.
  * discuss with the team if there is any TS dependencies

**Comment by Innkst** [comment]
Thank you for this request. We need to assess the impact of this change on our code base and users' apps and then decided on the timing.

**Comment by dsawali** [comment]
Updating RxJS to version 7.8.1 posed a few complications that I'm currently still working on. A few things to note:
- It needs TS version 4.2.x, we are currently at 4.1.5. So updating will take time to refactor the necessary changes for Taquito to be compatible with TS 4.2.4
- `rx-sandbox` library that we've been using to unit test RxJS observables doesn't seem like it supports the current version of RxJS we're adopting (7.8.1). We need to refactor and rewrite tests that rely on the `rx-sandbox` library that is no longer maintained
- Some types will need updating to accommodate for new typechecks and assertions in the newer TS version

**Comment by dsawali** [comment]
Hello @sirrocco, we're currently looking into upgrading RxJS versions to 7.8.1.

Would you mind sharing what kind of libraries were blocked by RxJS 6? Thanks

**Comment by Innkst** [comment]
Quick recap for the purpose of this ticket:
- updated RxJS version from v6.x to v7.8.1
- updated TS version for the @taquito/taquito package (and the parent package) from 4.1.5 to 4.2.4
