### ISSUE TITLE
[SPIKE] Assess the impact of 15s block time change in Octez

### ISSUE THREAD

**Issue by dsawali** [ecadlabs/taquito#2272]
Mumbai protocol update introduces 15s block times now being the standard across the blockchain.

Investigate and assess the impact in Taquito, and write tickets to address the change accordingly.

The following quantities remain the same:
```
- the minimal time period of a cycle (namely, 2 days, 20 hours, and 16 minutes),
- the length of the nonce revelation period (namely, around 2 hours and 8 minutes)
- the number of nonce commitments per cycle (namely, 128),
- the number of stake snapshots per cycle (namely, 16),
- the maximum rewards per minute (namely 80 tez), and therefore roughly the same inflation,
- the minimal “time to live” of an operation (namely, 1 hour),
- the block gas limit per minute (namely 10400000 gas),
- the ratio between the liquidity baking subsidy and the maximum rewards per block (namely, 1/16).
```

Some protocol parameter values have been changed to adjust for the new block time:

Parameter (unit) | Old (Lima) value | New value
-- | -- | --
minimal_block_delay (seconds) | 30 | 15
delay_increment_per_round (seconds) | 15 | 8
blocks_per_cycle (blocks) | 8192 | 16384
blocks_per_commitment (blocks) | 64 | 128
nonce_revelation_threshold (blocks) | 256 | 512
blocks_per_stake_snapshot (blocks) | 512 | 1024
max_operations_time_to_live (blocks) | 120 | 240
hard_gas_limit_per_block (gas unit) | 5200000 | 2600000
baking_reward_fixed_portion (mutez) | 10000000 | 5000000
baking_reward_bonus_per_slot (mutez) | 4286 | 2143
endorsing_reward_per_slot (mutez) | 2857 | 1428
liquidity_baking_subsidy (mutez) | 2500000 | 1250000

relevant links:
- https://gitlab.com/tezos/tezos/-/merge_requests/7017

**Comment by dsawali** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Taquito-Development-Team-60ca841c87ca580010057707/issues/ecadlabs/taquito/2272?planning-poker) with Zenhub @zainen @hui-an-yang

**Comment by Innkst** [comment]
We want to check if this change is already part of the mondaynet and if all relevant Taquito tests succeed

**Comment by zainen** [comment]
@Innkst we would like to assess this for testnets that hold the exact changed values right?
because for mondaynet the block time and about of blocks per cycle is different right?
