### ISSUE TITLE
Broken link on Dapp pre-launch checklist page

### ISSUE THREAD

**Issue by Innkst** [ecadlabs/taquito#2293]
https://tezostaquito.io/docs/dapp_prelaunch/
Link to the public nodes from this page is broken:
 You can find [here ](http://localhost:3000/docs/rpc_nodes#list-of-community-run-nodes)|] a list of public Tezos nodes.

**Comment by claudebarde** [comment]
This has been fixed in this pull request: https://github.com/ecadlabs/taquito/pull/2338

**Comment by michaelkernaghan** [comment]
fixed
