### ISSUE TITLE
Broken link on Smart contract collection page

### ISSUE THREAD

**Issue by Innkst** [ecadlabs/taquito#2295]
https://tezostaquito.io/docs/contracts_collection#walletcontract
Right after the Caption of Wallet Contract section there is a contract address link referring to the BCD:
https://better-call.dev/jakartanet/KT1T1KsEcVvsVGoHYrzjCzuJjviUDM3uyGmh/code

**Comment by dsawali** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Taquito-Development-Team-60ca841c87ca580010057707/issues/ecadlabs/taquito/2295?planning-poker) with Zenhub @hui-an-yang @zainen

**Comment by claudebarde** [comment]
This has been fixed in this pull request: https://github.com/ecadlabs/taquito/pull/2338

**Comment by michaelkernaghan** [comment]
this should be closed as it was fixed.
