### ISSUE TITLE
Idea: Respect Interface Segregation Principle

### ISSUE THREAD

**Issue by egarson** [ecadlabs/taquito#2300]
Consider the following code from https://tezostaquito.io/docs/smartcontracts:
```
    tezos.contract
        .at('KT1GJ5dUyHiaj7Uuc8gqfsbdv5tTbEH3fiRP')
        .then((contract) => {
            let methods = contract.parameterSchema.ExtractSignatures();
            println(JSON.stringify(methods, null, 2));
        })
        .catch((error) => console.log(`Error: ${error}`));
```
The above abstraction is leaky: to ExtractSignatures() you need to go through parameterSchema. Clients should ideally be abstracted from this implementation detail.
It violates the principle of, "You can play with your toys, and you can play with your friends. However, you can't play with your friend's toys". This is known as Interface Segregation Principle https://en.wikipedia.org/wiki/Interface_segregation_principle.
I suggest to add the method `ExtractSignatures()` on the Contract type, and then delegate to `parameterSchema` therein. You then abstract clients from the implementation, and when you change it they remain blissfully unaware of the fact.
This principle is more easily understood if you consider the degenerate case: `x = y.a.b.c.d.e.f.g`. Here, it's quite obvious that the structure of the system is unreasonably exposed in the scope of `x`. One correct refactoring of this design is to *delegate* to `g` all the way from `y`, whose interface can be: `a.g` and whose implementation is `b.g`. Similarly, `b` delegates to `c`, it's only friend (and so forth).
With the above, each type/interface delegates to its known member, the net result of which is that *changing the structure* anywhere in the call chain limits the *number of places* it needs to be modified.

**Comment by dsawali** [comment]
closing because `parameterSchema` is not an implementation detail, but a necessity.
