### ISSUE TITLE
website broken live codes

### ISSUE THREAD

**Issue by zainen** [ecadlabs/taquito#2305]
**Description**
broken examples in tezostaquito.io

only found broken examples currently

**Steps To Reproduce**
https://tezostaquito.io/docs/next/on_chain_views#how-to-simulate-a-view-execution-using-taquito
https://tezostaquito.io/docs/next/maps_bigmaps#accessing-map-values-with-complex-keys

**Expected behavior**
Examples should return the correct values with no errors

**Comment by dsawali** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Taquito-Development-Team-60ca841c87ca580010057707/issues/ecadlabs/taquito/2305?planning-poker) with Zenhub @hui-an-yang @zainen

**Comment by hui-an-yang** [comment]
The script used to originate live code example can be found here 

contractTopLevelViews
https://github.com/ecadlabs/taquito/blob/master/example/deploy-docs-live-code-contracts.ts#L556

contractMap8pairs
https://github.com/ecadlabs/taquito/blob/master/example/deploy-docs-live-code-contracts.ts#L347
