### ISSUE TITLE
Events are fired even if the transaction fails

### ISSUE THREAD

**Issue by zamrokk** [ecadlabs/taquito#2319]
If I have a tx failing, the event is still subscribed and fired on taquito side, we can see the result field with the error stacktrace on it

![image](https://user-images.githubusercontent.com/2536368/214626714-3b9047b0-d5d9-42e7-bda8-320f5776d139.png)

I am not really sure that developers are really interested by uncompleted events. 
To not break all current implementation I would suggest to filter all failing tx by default and add an option to not ignore failing tx events in case someone as a real use case around it

**Comment by dsawali** [comment]
thanks for submitting this issue, yeah I think we can probably do something like filter the result of the subscribed event by the result status.

**Comment by AlirezaHaghshenas** [comment]
@zamrokk
We are addressing this in #2388 .

However, I'm unable to reproduce the behavior when a contract call fails but the event is shown.
Do you have some reproduction guide (including the contract code)?

Thanks

**Comment by zamrokk** [comment]
yes, there is a way to reproduce.

Do this training :)    => https://github.com/marigold-dev/training-dapp-shifumi

On `play` function (https://github.com/marigold-dev/training-dapp-shifumi/blob/main/solution/app/src/pages/SessionScreen.tsx), look at the part in taquito where I override the default gas 
```
 const op = await preparedCall.send({
        gasLimit: gasLimit + 1000, //we take a margin +100 for an eventual event in case of paralell execution
```
and remove the `1000`

Then run the game on 2 browsers and click on a shifumi action (paper,stone,scissor) at same time on both windows. You can look on tzkt that quite often one of the transaction will be failing and the event will be emitted anyway

FYI : The cause of the failure is a bug on the cost estimator on Tezos code about event gas cost not taken into account. Ticket is open on it

**Comment by zamrokk** [comment]
FYI : same for reveal function, there is same bug and gas override
