### ISSUE TITLE
Unable to pass "Some None" to contract call

### ISSUE THREAD

**Issue by claudebarde** [ecadlabs/taquito#2344]
With the current implementation for contract call parameters, it is impossible to pass the value `Some None` to an entrypoint that requires a value of type `option (option timestamp)`, for example.
Although this is an edge case, Taquito should provide a more intuitive way to pass options and nested options as contract call parameters, as the current way becomes inefficient or even broken with nested options.

**Comment by hui-an-yang** [comment]
We are looking to support nested options contract call in our next release by introducing new semantics. And will deprecate the current semantic in the subsequent release for semantic consistency.  <img width="1005" alt="image" src="https://user-images.githubusercontent.com/106410553/228633063-61e62a6a-ab56-4d62-a9be-164323337444.png">

**Comment by claudebarde** [comment]
The solutions in the *subsequent release* column look great :)
