### ISSUE TITLE
encodePubKey util function improvements 

### ISSUE THREAD

**Issue by zainen** [ecadlabs/taquito#2372]
**Description**
addresses with annotations encoded improperly 

**Steps To Reproduce**
https://tezos-dev.slack.com/archives/CNJJ77B9B/p1677682409145329
to hex and back of kt1 address with %annotation does not encode properly and loses annotation

**Expected behavior**
address should be encoded and decoded without annotation and ideally annotation is not lost and added to the MichelsonV1Expression in the js object 

**_Note_**: investigate first whether michel-codec already supports contract addresses with %annotations.

**Comment by Innkst** [comment]
The user solved it using:

let encode_address = s => (
  Js.String.slice(~from=0, ~to_=44, s)->encodePubKey,
  Js.String.sliceToEnd(~from=44, s)->hex2buf->BufferEx.toNodeBuffer->Node_buffer.toString,
)

**Comment by dsawali** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Taquito-Development-Team-60ca841c87ca580010057707/issues/ecadlabs/taquito/2372?planning-poker) with Zenhub @AlirezaHaghshenas @hui-an-yang @zainen

**Comment by michaelkernaghan** [comment]
is the user work around enough is there a fix that has to be applied to the model code?

**Comment by zainen** [comment]
I believe this work around fully discards the annotation that is with the value

**Comment by hui-an-yang** [comment]
The naming of function `encodePubKey` is misleading should be renamed to something like encodePKH or encodePublicKeyHash for clarity. The logic of this function only covers tz1, tz2, tz3 which are all public key hashes. 
The user in the slack using this function to encode a byte format of kt1 address back to readable kt1, is a misused of the function.
