### ISSUE TITLE
Suggestion -> Update Typescript to v5.0

### ISSUE THREAD

**Issue by BearCooder** [ecadlabs/taquito#2396]
**🔮 Title / Topic**
Update Typescript to v5.0

**💭 Details**

Typescript 5.0 just got released with lots of improvements. So it might be worth to update to v5.

Here is the announcement:
https://twitter.com/typescript/status/1636416665071288321 as of [Mar 16, 2023]

**Comment by Innkst** [comment]
We will be looking at upgrading to a previous version. When the majority of Taquito users are able to upgrade to v5.0, Taquito will do that too.
