### ISSUE TITLE
utils.validateContractAddress false positive for contract addresses which exceed the maximum valid length

### ISSUE THREAD

**Issue by Bug-Reaper** [ecadlabs/taquito#2398]
**Description**
https://tezostaquito.io/docs/validators/
`import { validateContractAddress } from '@taquito/utils';`

ValidateContractAddress method seems to not check if the maximum length for a contract address is exceeded?

**Steps To Reproduce**
1. import utility
2. Try to validate a very very long contract address
3. get code `3` valid

**Expected behavior**
I presume we should get code `2 = INVALID_LENGTH,` if the contract address is sufficiently long

**Desktop (please complete the following information):**
 - OS: Linux
 - JS Ver: `node-js v16.19.1`
 - Version: `"@taquito/utils": "^16.0.0"`

**Additional context**
Was trying to intentionally cause an error to test that the validation works. Seems to work for contract addresses that are too short but not addresses that are too long.

**Comment by Bug-Reaper** [comment]
Looks like either the regex to remove annotations OR the b58 decode works fine with inputs that are too large. Somehow you end up with `decoded.length == prefixLength[prefixKey]` even if the address was too long?

relevant code:
https://github.com/ecadlabs/taquito/blob/bbd425f610b7478f501ce34f771caa604f338593/packages/taquito-utils/src/validators.ts#L42

Fails as expected if address is too short.

**Comment by jevonearth** [comment]
Try `KT1X1LgNkQShpF9nRLYw3Dgdy4qp38MX617z9nRLYw3`

**Comment by Bug-Reaper** [comment]
I believe when I tested I did something akin to:
`validateContractAddress("KT1TcZXVW2RxGkUdfpA9azptJGwFbr5XcCgxaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")`.

**Comment by dsawali** [comment]
Hello @Bug-Reaper, we've released a patch release to address this issue in version 16.0.1 of Taquito
 https://www.npmjs.com/package/@taquito/taquito/v/16.0.1

**Comment by Bug-Reaper** [comment]
Great stuff guys. Thanks for the fix @dsawali ! 🙂
