### ISSUE TITLE
Updated RPC nodes page on website 

### ISSUE THREAD

**Issue by hui-an-yang** [ecadlabs/taquito#2407]
Replace kathmandu references with mumbai

https://tezostaquito.io/docs/rpc_nodes/
<img width="831" alt="image" src="https://user-images.githubusercontent.com/106410553/228071165-4d5748ec-2e0b-4830-b77c-01657c24fccf.png">

**Comment by Innkst** [comment]
Please check other URS and Remove TezTools please
