### ISSUE TITLE
Docs correction (Tezos Domain Lookup Example - TezosDomain => WalletAddress)

### ISSUE THREAD

**Issue by Bug-Reaper** [ecadlabs/taquito#2436]
**Description**
Doc example code needs a small change. The code example for domain lookup returns the owner address and not the address that the `.tez` domain points to.

**Steps To Reproduce**
1. Visit docs for tezos domains https://tezostaquito.io/docs/tezos_domains/
2. Scroll to section with example code to [lookup a domain](https://tezostaquito.io/docs/tezos_domains/#looking-up-a-tezos-domain)

**Expected behavior**
Example code should do what's described in that section
> It is also possible to look up a domain name to find the address it references.

**Additional context**
You can see pretty clearly it returns the **owner** for the Tezos Domain. However the owner address is not necessarily the address that the Tezos Domain points to. I believe it should instead return `domain.address` instead of `domain.owner`.

**Comment by Bug-Reaper** [comment]
Can someone please confirm that `domain.address` is the wallet address the tezos domains points towards whereas `domain.owner` is the wallet address that owns the domain? And that these could be different wallet addresses?

**Comment by zainen** [comment]
Hi @Bug-Reaper, yes, the domain.address will point to the address that the name, ie. alice.tez will point to where, as the domain.address is the address that owns that domain name 
I believe the usual is the two being the same tz1/2/3/4 address. However, that is not a hard rule; they can be different.

I will update the docs! Thank you

**Comment by Bug-Reaper** [comment]
Thanks @zainen ! Glad to assist 💯
