### ISSUE TITLE
Update to axios 1.x

### ISSUE THREAD

**Issue by avysel** [ecadlabs/taquito#2460]
Hello

I’ve updated a React app using Taquito. I was using Taquito 13.x, I’ve updated to 16.x

My project also uses axios. But I was forced to downgrade my axios from 1.x to 0.27.2 because of your new axios-fetch-adapter that uses axios 0.27.2.

Using axios 1.x in an app with Taquito results in this error at build time:

```
./node_modules/@taquito/axios-fetch-adapter/index.js
Attempted import error: 'isFormData' is not exported from 'axios/lib/utils'.
```

Because axios 0.x exports like this:

```
module.exports = {
  isArray: isArray,
…
}
```

But axios 1.x exports like this:

```
export default {
  isArray,
…
}
```

Your code of `axios-fetch-adapter` fits only with axios 0.x. And that forced me to downgrade a part of my app that uses axios too.

Could you consider using a recent axios version?

**Comment by hui-an-yang** [comment]
@avysel & @jdsika  We've changed from axios to fetch in taquito v17.5.0, can you confirm the issue is resolved?

**Comment by avysel** [comment]
@hui-an-yang yes, to me it's ok, thanks.

**Comment by jdsika** [comment]
I forwarded the request but I guess it's fine then :)
