### ISSUE TITLE
Replace Axios with Fetch in Taquito

### ISSUE THREAD

**Issue by dsawali** [ecadlabs/taquito#2461]
Taquito currently relies on `Axios` HTTP request implementation to make calls to any external endpoints. While `Axios` was quite easy to work with, it had its limitations when it comes to running in worker environments or some browser environments. 

In previous version of nodes, fetch wasn't available.
The `axios-fetch-adapter` package was introduced to alleviate such limitations. `Axios` provides an `adapter` parameter property when creating HTTP requests to make sure the requests are made using the custom adapter when certain conditions are met. 

While the `axios-fetch-adapter` was a worthwhile solution at the time, it had introduced new issues due to the package not being maintained actively anymore.

The issues it introduced are as follows:
- Version conflicts between the `axios` version imported in `axios-fetch-adapter` and Taquito, and sometimes even for our users when they also use Axios in their package
- incompatibility with newer ESM packages due to it being written in old JS

### Solution Proposal
One proposed solution we discussed is to use `fetch` and remove `Axios` completely from our dependencies. 

This will involve adapting our current HTTP utils package to account for the different behaviours of `Axios` vs `fetch`
Some differences to note:
- `fetch` is very lean, so there aren't any out of the box features that comes with `Axios` (e.g. auto JSON data transformation, response timeouts)
- Some potential browser incompatibility that might be introduced by `fetch`. `Axios` is built using `XMLHttpRequest`, making it very browser friendly, even with very old browsers
- In `Axios`, anything HTTP code 400 and above are considered `errors`. Fetch just sees them all as responses and will not reject any promises, so we will need to handle them in Taquito accordingly since we have been relying on `Axios` response errors in some of our code

The benefits of using `fetch` as opposed to `Axios` are as follows:
- `fetch` is a built in feature in Node, so no package imports are necessary
- Since it's a built in Node feature, there no chance it will conflict with other packages
- It gives us more flexibility to what we want to implement as opposed to something that's abstracted like Axios
- Removes the dependency on `Axios` when something doesn't work properly

### Acceptance Criteria
- Replace the usage of `Axios` in Taquito in favour of `fetch`
- ensure backwards compatibility with our existing integration/unit tests as to not introduce new issues to our users

**Comment by AlirezaHaghshenas** [comment]
One way to do this:

1. Implement a wrapper that wraps axios and exposes all things we need, the API should be as close to axios as possible
2. Use the wrapper instead of axios everywhere
3. Implement exhaustive unit tests to check the behaviour of the wrapper in case of different failures and corner cases
4. Implement an alternative to that wrapper that uses fetch
5. Ensure the second implementation also passes all tests
6. replace the implementation
7. Remove the one that uses axios
