### ISSUE TITLE
Micheline types returned on the smart contract event payload is different from the expected one

### ISSUE THREAD

**Issue by zamrokk** [ecadlabs/taquito#2462]
Hi. I found something weird with `events `I receive from my smartcontract
On the client side, with Taquito "16.1.2" I display what I receive and it should be an `Array of addresses`  instead I get and `Array of bytes`.

If I look on an indexer, it is able to display the addresses as `Array of string` (https://ghostnet.tzkt.io/oo79S9vVsZeVNZeEKsF3byjurpqewF4kk8Z5giPmQxYMuGPNsAy/249015)

So where is the bug from ? 

![image](https://user-images.githubusercontent.com/2536368/235918281-6ddc04a0-372a-41f0-9944-a1569f2f6937.png)

this how I emit the event in ligo 

`Tezos.emit("%orgMemberRequestsUpdated",[jor.membersToApprove,jor.membersToDecline,org.name])`

Here is the type definition of each field

```
export type joinOrganizationResponse = {
    membersToApprove : set<address>,
    membersToDecline : set<address>, 
    orgName : string
};
```

**Comment by dsawali** [comment]
Hello there @zamrokk, thanks for taking the time to write up an issue.

Was this behaviour observed from using the event listener?

**Comment by zamrokk** [comment]
Yes. For other events returning a simple type, no problem but this is a tuple of 3 items o I receive a complex Micheline with pairs

**Comment by dsawali** [comment]
@zamrokk thanks, we'll look into this

**Comment by zamrokk** [comment]
The person who did the events is thinking that taquito did not unify the payload data with the type correctly
He thinks nothing is wrong with the contract or the indexer-node pair

**Comment by hui-an-yang** [comment]
Hello @zamrokk, 

Thanks for reporting this, we have looked into this and found that it's not a Taquito bug.
[Here](https://rpc.ghostnet.teztnets.xyz//chains/main/blocks/2538648) with ctrl + F 'event' you can see what's being returned by the node is also array of bytes even the type definition is array of address. 
We have raised this question to Tezos core developer team waiting for reply, will get back to you when we have more information.

**Comment by hui-an-yang** [comment]
Hi @zamrokk 

I've confirmed with a tezos core developer that they'll improve the event emitted to be readable form like `tz1...` in the future release. Here's their [MR](https://gitlab.com/tezos/tezos/-/merge_requests/9931) of the change.

**Comment by zamrokk** [comment]
Thank you for the support !!!
