### ISSUE TITLE
No confirmation received when running a Next.js dApp in production mode

### ISSUE THREAD

**Issue by lgaroche** [ecadlabs/taquito#2491]
**Description**
When running a dApp with Next.js 13 in development mode (with a local server and hot reload), contract interactions with Taquito work just fine. However, if the project is built for production, and served either locally or on Vercel, contract interactions never receive a confirmation. Instead, it ends up with the exception ```Error: Confirmation polling timed out``` being thrown. 

**Steps To Reproduce**
1. Clone the simple reproduction repository (copy of the react example): https://github.com/lgaroche/taquito-next-issue
2. Run in development mode (see the README): contract interactions are fine
3. Build for production and start a local server: contract interactions fail

**Expected behavior**
There should be no behavior difference between dev and prod builds. I'm not sure whether the issue is on Next or Taquito side, but there's something odd going on with this specific scenario. 

**Desktop (please complete the following information):**
 - OS: Mac OS X 
 - Browser Brave with Temple

**Comment by pedrus16** [comment]
Hey, after trying a few things it turns out that disabling `swcMinify` in the `next.config.js` fixes the issue. 

Looking at this [discussion](https://github.com/vercel/next.js/discussions/30237), it could be an issue with SWC.

**Comment by Innkst** [comment]
Thanks for your comment @pedrus16 
Closing this issue
