### ISSUE TITLE
Breaking change in `Schema.Execute(...)` + `option` + `Some`

### ISSUE THREAD

**Issue by psmolinsky** [ecadlabs/taquito#2499]
**Description**
`@taquito/michelson-encoder` version 16.2.0 introduced a breaking change in `Schema.Execute(...)` when schema contains `option` and value contains `Some`. Most likely this was not intended and it is a bug.

**Steps To Reproduce**
1. Run following code:
```typescript
import { Schema } from '@taquito/michelson-encoder';

const schema = new Schema({
    prim: 'option',
    args: [{ prim: 'string' }],
});

const value = schema.Execute({
    prim: 'Some',
    args: [{ string: 'abc' }],
})

console.log(value);
```
2. Version 16.2.0 outputs:
```typescript
{ Some: 'abc' }
```
3. Versions prior to 16.2.0 (e.g. 16.1.2) output:
```typescript
abc
```

**Expected behavior**
`Some` value should be still handled transparently. So bare string (`abc` in the example) should be returned.

**Comment by dsawali** [comment]
will be closing as it's an intended change as discussed with @psmolinsky
