### ISSUE TITLE
Feature Request: sign failing_noop operation

### ISSUE THREAD

**Issue by jdsika** [ecadlabs/taquito#2507]
**Is your feature request related to a problem and use case? Please describe.**
I want to sign a string message as failing_noop (tag 17) in order to avoid the misuse of this signature onchain as described in the [Tezos Stackexchange](https://tezos.stackexchange.com/questions/6081/sign-failing-noop-tag-17-message-with-taquito)

**Describe the solution you'd like**
I want to use the [Taquito signer](https://tezostaquito.io/docs/signing/#generating-a-signature-with-the-inmemorysigner) with an argument to make sure it is signed as failing_noop and the bytes message is properly constructed according to the documentation.

**Additional context**
This would also be needed by Sign in with Tezos as the message signed by the user logging into a web3 application in order to proof the ownership of the private key belonging to his address exposes a security risk.

**Comment by Innkst** [comment]
Thank you for your request! The related issue has already been scheduled for v17.1 and we will make sure we will get to it sooner

**Comment by jdsika** [comment]
Is this resolved? @Innkst  as I see you have released v17.1 ?

**Comment by AlirezaHaghshenas** [comment]
@jdsika This is implemented in version 17.2
Closing
