### ISSUE TITLE
Treat pair as comparable type

### ISSUE THREAD

**Issue by carte7000** [ecadlabs/taquito#251]
Michelson supports the use of Pair as key for a map and big-map, however, Taquito smart contract abstraction currently throws an error when encoding contract storage that make use of Pair as key in a map

For example

Given the following contract

```js
const keyType = { "prim": "pair", "args": [{ "prim": "string" }, { "prim": "string" }] };

{
    "code": [
      { "prim": "parameter", "args": [{ "prim": "unit" }] },
      { "prim": "storage", "args": [{ "prim": "map", "args": [keyType, { "prim": "string" }] }] },
      {
        "prim": "code",
        "args":
          [[{ "prim": "DUP" }, { "prim": "CDR" },
          { "prim": "NIL", "args": [{ "prim": "operation" }] },
          { "prim": "PAIR" },
          { "prim": "DIP", "args": [[{ "prim": "DROP" }]] }]]
      }],
    "storage": [
      { "prim": "Elt", "args": [{ "prim": "Pair", args: [{ "string": "test2" }, { "string": "test3" }] }, { "string": "test" }] },
      { "prim": "Elt", "args": [{ "prim": "Pair", args: [{ "string": "test2" }, { "string": "test4" }] }, { "string": "test" }] },
    ]
  }
```
Taquito will throw the following error while encoding the storage into the SC abstract:

`this.KeySchema.ToKey is not a function`

The problem will be the same for big-map, set and map. This is because Taquito does not treat `pair` as comparable value (which it is).

### A problem to consider while solving this issue:

The current implementation of the SC abstract produces a plain JS object for map. So a map is typically rendered as:

```js
{ key : value}
```

However, this approach is not suitable for Pair because a JS object would be serialized before use as a key leading to overriding the other.

### A few solutions to consider:

Given the following Pair: 
`{ "prim": "Pair", args: [{ "string": "test2" }, { "string": "test3" }] }`

#### Taquito could serialize pair using a well known format `test2_test3` leading to:
```
{ test2_test3: value }
```

#### Taquito could change how it abstracts Pair as key doing:
```
{ key: { prop1: test2, prop2: test3}, value: "value" }
```

**Comment by jevonearth** [comment]
Addressed in release [6.1.0-beta.0][https://github.com/ecadlabs/taquito/releases/tag/6.1.0-beta.0]
