### ISSUE TITLE
Website metadata-tzip16 live example of https and sha256 not working

### ISSUE THREAD

**Issue by hui-an-yang** [ecadlabs/taquito#2510]
**Description**

metadata-tzip16 webiste live example not working 

**Steps To Reproduce**
1. Go to [metadata-tzip16 https-example](https://tezostaquito.io/docs/metadata-tzip16#https-example) and [metadata-tzip16 sha256-hash](https://tezostaquito.io/docs/metadata-tzip16#example-having-a-sha256-hash)
2. Click on 'Run code'
3. Scroll down to 'Result'
<img width="771" alt="image" src="https://github.com/ecadlabs/taquito/assets/106410553/65665ebe-764a-4b4d-9490-2b0c111a540b">

and in console:

<img width="677" alt="image" src="https://github.com/ecadlabs/taquito/assets/106410553/7ab6c2f1-74e7-4601-9263-2cbc4b1f5acf">*

**Expected behavior**
for live code example to return metadata like below 
```
{
    "name": "Taquito test with valid metadata",
    "description": "This is metadata test for Taquito integration tests with the Ligo Taco shop contract modified to include metadata in storage",
    "version": "7.1.0-beta.0",
    "license": {
        "name": "MIT",
        "details": "The MIT License"
    },
    "homepage": "https://github.com/ecadlabs/taquito",
    "source": {
        "tools": [
            "Ligo",
            "https://ide.ligolang.org/p/-uS469slzUlSm1zwNqHl1A"
        ],
        "location": "https://ligolang.org/docs/tutorials/get-started/tezos-taco-shop-payout"
    }
}
```

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dsawali** [comment]
The regression was caused by a recent update in the Terraform provider for our GCP bucket that stored these metadata values. It has now been fixed.
