### ISSUE TITLE
Use simulate RPC endpoint instead of run_operation to estimate operations in Taquito

### ISSUE THREAD

**Issue by dsawali** [ecadlabs/taquito#2548]
With protocol 17 comes changes to gas_limits for different address curves. 

This introduced a few problems for users or developers that rely on `run_operation` RPC where `gas_exhausted` error will pop up even with a higher gas limit than needed. See this issue for more context: [link](https://github.com/tezos-reward-distributor-organization/tezos-reward-distributor/pull/675)

Change the simulation step in Taquito to use the simulate endpoint instead of `run_operation` like it's using right now

**Comment by sergey-kintsel** [comment]
Well, I created such a [PR](https://github.com/ecadlabs/taquito/pull/2549), but it looks like it doesn't fix the issue. I was able to catch a gas_exhausted exception when added around 300 operations into a batch. Am I missing anything? 😅 
also, I am wondering how `run_operation` differs from `simulate_operation` and `preapply/operations`  🤷  as listed [here](https://gitlab.com/tezos/tezos/-/blob/master/docs/api/nairobi-openapi.json)

**Comment by sergey-kintsel** [comment]
yeah, of course :)
My point was that even the simulate endpoint does use the gas_limit

**Comment by serjonya-trili** [comment]
@dsawali unfortunately, I cannot run the integration tests. all the tests fail for me. But I updated the branch with the changes you mentioned. Could you try yourself?

**Comment by dsawali** [comment]
@serjonya-trili I think you might need to change the endpoint to use the non-internal testnets in `integration-tests/config.ts`. But I will try and test myself as well since we're also trying to implement a solution for this.

@sergey-kintsel yeah that seems like expected behaviour. We'll probably cook something up internally as well and keep you all updated.
