### ISSUE TITLE
verifySignature with invalid message

### ISSUE THREAD

**Issue by nurs-jubatyrov** [ecadlabs/taquito#2578]
When calling `verifySignature` you can append any character to the message payload and it would verify the signature correctly.

**Steps To Reproduce**
1. Call `verifySignature` with argument and append any character to the message payload.
4. The function should return `false` instead of `true`.

**Additional context**
The issue is in `hex2buf` function in https://github.com/ecadlabs/taquito/blob/27f57de79ab464b7c4d9255275c2f48216214fad/packages/taquito-utils/src/taquito-utils.ts#L199C3-L199C3 which would truncate if the length of the message is odd.

**Comment by jevonearth** [comment]
Addressed in PR #2580

**Comment by dsawali** [comment]
issue #2580 has been completed and the patch release Taquito v17.1.1 has been released here:
https://www.npmjs.com/package/@taquito/taquito/v/17.1.1
