### ISSUE TITLE
Local Forging a smart contract invocation with Taquito Local-Forging

### ISSUE THREAD

**Issue by DalyIng** [ecadlabs/taquito#258]
Can we forge locally a smart contract invocation using **@taquito/local-forging**?

I'm asking because in the documentation of this operartion, the parameters field in contents tab, must have the form:
> *annots: string[]* | *args: MichelsonV1Expression[]* | *prim: string*

Or when using the RPC endpoint to forge the *parameters* field has the form: 

```
{
    entrypoint: "trnasfer",
    value: {
      args: [
        {
          args: [{ int: amount }, { string: from }],
          prim: "Pair"
        },
        { string: to }
      ],
      prim: "Pair"
    }
  };
```

If yes, how to do so? Where to define the entrypoint?

**Comment by jevonearth** [comment]
Hi @DalyIng, Thanks for trying Taquito!

Are you using the `local-forging` package directly for a specific reason? If you use the smart contract abstraction provided by the `@taquito/taquito` package, and set it to use the local-forger, you can call smart contracts using the local-forger.

If you are using the  `@taquito/local-forging` directly for a specific use-case we can help, and I'd also like to know what the use-case is. :)

**Comment by DalyIng** [comment]
Hello @jevonearth , I'm a big fan already :D.
So, my use case is the following:
I'm using an RPC endpoint to get the bytes of a smart contract invocation operation, this is how:
```
    const  forgeOperationRequest = await axios.post(
        `${nodeURL}/chains/main/blocks/head/helpers/forge/operations`,
        forgeOperationData,
        {
          headers: {
            "Content-Type": "application/json"
          }
        }
      );

```
And I get the result that I'll use it lately to sign the transaction, run, preapply and finally inject.

I want to replace the forging process by a local forge, and I found that taquito has a local-forging module so I was trying to:
```
const forgeOperationRequest = await localForger.forge(branch, contents);

// Knowing that

const contents = [
    {
      kind: "transaction",
      source: senderAccount.toString(),
      fee: "600000",
      counter,
      gas_limit: "300000",
      storage_limit: "20000",
      amount: "0",
      destination: smartPyConf.contractAddress.toString(),
      parameters: {
        entrypoint: "transfer",
        value: {
          args: [
            {
              args: [{ int: amount }, { string: from }],
              prim: "Pair"
            },
            { string: to }
          ],
          prim: "Pair"
        }
      }
    }
  ];
```

And I got as result this error:

> TypeError: Expected String
    at decodeUnsafe (/home/daly/smartPyContract/node_modules/base-x/src/index.js:63:45)
    at Object.decode (/home/daly/smartPyContract/node_modules/base-x/src/index.js:110:18)
    at Object.decode (/home/daly/smartPyContract/node_modules/bs58check/base.js:39:25)
    at Object.b58cdecode (/home/daly/smartPyContract/node_modules/@taquito/local-forging/node_modules/@taquito/utils/src/taquito-utils.ts:46:13)
    at /home/daly/smartPyContract/node_modules/@taquito/local-forging/src/codec.ts:16:30
    at /home/daly/smartPyContract/node_modules/@taquito/local-forging/src/schema/operation.ts:127:21
    at Array.reduce (<anonymous>)
    at Object.encoder (/home/daly/smartPyContract/node_modules/@taquito/local-forging/src/schema/operation.ts:113:15)
    at LocalForger.forge (/home/daly/smartPyContract/node_modules/@taquito/local-forging/src/taquito-local-forging.ts:26:39)
    at _callee5$ (/home/daly/smartPyContract/test/TransferFeelessLocalForging.js:116:47)

I appreciate your help.

**Comment by DalyIng** [comment]
Resolved.

**Comment by jevonearth** [comment]
hi @DalyIng 

Just checking that you closed this issue on purpose and you actually got unblocked? Feel free to reopen if you still need assistance. :)

At a minimum, our take away is that we can improve the error message for this situation.

**Comment by DalyIng** [comment]
Thank you @jevonearth ,

Actually I think that the documentation of the package took me to a wrong path, so when checking the tests I found the right way to call the local-forger. I think that you can imporve this content to prevent the same situation in the future https://tezostaquito.io/typedoc/modules/_taquito_local_forging.html **by adding this URL:** _https://github.com/ecadlabs/taquito/blob/master/packages/taquito-local-forging/test/taquito-local-forging.spec.ts_ because who follows hte package documentation will found that the forge method ask for two params just like written here: _https://tezostaquito.io/typedoc/interfaces/_taquito_taquito.forgeparams.html_
**but it actually need one single param, an object with branch and content tab.**

**Comment by jevonearth** [comment]
Great, thank you for the feedback, much appreciated.
