### ISSUE TITLE
Document on how to use the local forging package

### ISSUE THREAD

**Issue by carte7000** [ecadlabs/taquito#259]
Add a page to the website containing documentation about how to use the local forger

The documentation should demonstrate how to:
- How to inject the local forger into Taquito
- Show how to use the package directly like in https://github.com/ecadlabs/offline-tezos-ops
- Also discuss the exported encoders and decoders (https://github.com/ecadlabs/taquito/blob/master/packages/taquito-local-forging/src/taquito-local-forging.ts#L23)

**Comment by michaelkernaghan** [comment]
deployed to https://tezostaquito.io/docs/local_forger
