### ISSUE TITLE
Investigate whether there are new parameters introduced with bootstrapped smart rollups

### ISSUE THREAD

**Issue by dsawali** [ecadlabs/taquito#2592]
Protocol Oxford will introduce bootstrapped smart rollups. Investigate whether this will affect the way Taquito facilitates `smart_rollup_originate` operations and make the necessary adjustments.

Check whether new parameters will be introduced to `smart_rollup_originate` with this new change.

If the findings indicate an impact in Taquito, create new tickets to implement it accordingly

relevant documentation:
https://tezos.gitlab.io/protocols/018_oxford.html#smart-rollups

**Comment by hui-an-yang** [comment]
> Enable the latest version of the WASM PVM (2.0.0-r2). Existing smart rollups will see their PVM automatically upgrade, and newly originated smart rollups will use this version directly (MR [!9051](https://gitlab.com/tezos/tezos/-/merge_requests/9051))

updated pvm enum with new version 2.0.0-r2

**Comment by hui-an-yang** [comment]
> this will facilitate the automatic deployement of some rollups on test-nets (such as Mondaynet).
based on their [mr8552](https://gitlab.com/tezos/tezos/-/merge_requests/8552), this is an tezos internal tool when they restart mondaynet that there will be designeted bootstrapped rollup contract address, origination proof and and node by default.
Therefor this change doesn't affect taquito.
