### ISSUE TITLE
Split duplicated argument `pkh` in RPC

### ISSUE THREAD

**Issue by dsawali** [ecadlabs/taquito#2595]
`smart_rollups/smart_rollup/<address>/staker1/<pkh>/staker2/<pkh>/timeout` and `smart_rollups/smart_rollup/<address>/staker1/<pkh>/staker2/<pkh>/timeout_reached` into /staker1/<staker1_pkh>/staker2/<staker2_pkh>

relevant docs: 
https://tezos.gitlab.io/protocols/018_oxford.html#rpc-changes

**Comment by hui-an-yang** [comment]
according to the documentation that this change doesn't affect use and taquito didn't support 2 rpc endpoints mentioned hence no change needed for this ticket 
> [RPC Changes](https://tezos.gitlab.io/protocols/018_oxford.html#id9)
Split duplicated argument pkh in RPC smart_rollups/smart_rollup/<address>/staker1/<pkh>/staker2/<pkh>/timeout and smart_rollups/smart_rollup/<address>/staker1/<pkh>/staker2/<pkh>/timeout_reached into /staker1/<staker1_pkh>/staker2/<staker2_pkh>. This changes the RPC description but not its use. (MR [!8339](https://gitlab.com/tezos/tezos/-/merge_requests/8339))
