### ISSUE TITLE
Update return types coming from the RPC

### ISSUE THREAD

**Issue by dsawali** [ecadlabs/taquito#2596]
**Change**
- [x] `rpc.getConstants()`: add new properties and omit old ones 
- [x] `rpc.getDelegates()`: DelegatesResponse property frozen_deposits_limit is removed
- [x] `rpc.getBlock(), rpc.preapplyOperations(), rpc.runOperation(), rpc.simulateOperation(), rpc.getBlockMetadata()`: added query parameter `version` default value is `0` will output `kind: "endorsement"` but deprecated ; value `1` will output `kind: "attestation"`
- [x] `rpc.getPendingOperations()` : query parameter version default value is 1 will return { applied: { kind: endorsement} } version 2 will output { validated: { kind: attestation} }

**Removed**
- [x] `rpc.getTxRollupInbox()` 
- [x] `rpc.getTxRollupState()`

--------
Context have been updated with new reward parameters. This changes the JSON from the RPC `/chains/main/blocks/head/context/constants`

Wording from changelog suggests the introduction of new fields when querying said RPC

Also audit some of the current existing typing to not have unused properties from previous protocols.

relevant docs:
- https://tezos.gitlab.io/protocols/018_oxford.html#rpc-changes
- https://gitlab.com/tezos/tezos/-/merge_requests/8657

**Comment by hui-an-yang** [comment]
protocol constant type is updated in [pr2637](https://github.com/ecadlabs/taquito/pull/2637)
audit of existing type will need discussion
