### ISSUE TITLE
Remove `getOriginationProof` RPC method in Taquito

### ISSUE THREAD

**Issue by dsawali** [ecadlabs/taquito#2597]
Protocol Oxford removes the RPC for computing smart rollups' origination proof.

- Remove the RPC method in `@taquito/rpc`, including rpc-cache, interface, etc
- Remove tests related to the origination proof RPC endpoint
- Remove it from smart rollup origination parameters in the Contract API, PrepareProvider, etc

relevant documents:
- https://tezos.gitlab.io/protocols/018_oxford.html#smart-rollups
- https://gitlab.com/tezos/tezos/-/merge_requests/8817

**Comment by hui-an-yang** [comment]
> Enable the latest version of the WASM PVM (2.0.0-r2). Existing smart rollups will see their PVM automatically upgrade, and newly originated smart rollups will use this version directly (MR [!9051](https://gitlab.com/tezos/tezos/-/merge_requests/9051))

updated pvm enum with new version 2.0.0-r2
