### ISSUE TITLE
Change `endorsement` into `attestation`

### ISSUE THREAD

**Issue by dsawali** [ecadlabs/taquito#2599]
Protocol Oxford introduces a renaming of all things related to `endorsement` or `endorsing` into `attestation` or `attesting`.

Do a run through of Taquito and update the names accordingly in:
- the codebase (types, rpc responses, constants, etc)
- the documentation (website, docs)
- the Taquito test dapp (if any)

**Comment by hui-an-yang** [comment]
additional info of this change https://tezos-dev.slack.com/archives/C042S337D9A/p1692964989323969
