### ISSUE TITLE
Update failing_noop tests to use ephemeral keys

### ISSUE THREAD

**Issue by ac10n** [ecadlabs/taquito#2600]
Taquito and the KeyGen Api have a circular dependency:

- KeyGen has Taquito as a dependency in the codebase
- Taquito uses the deployed KeyGen Api for integration tests

Because of this, we needed to work around KeyGen not supporting the `failing_noop` by doing its tests using secret key. After we release Taquito, we can update the Taquito version in the KeyGen api and deploy, then update Taquito to do those tests using ephemeral keys like other tests

**Comment by Innkst** [comment]
There is a new keygen implementation that may work for us. We will hold off on this change for now.
