### ISSUE TITLE
Taquito Debug Mode

### ISSUE THREAD

**Issue by DalyIng** [ecadlabs/taquito#261]
Hi, is there a **debug mode for Taquito**? Something like:

```Tezos.debugMode({node : "on"});```

If yes, how to activate it?

Thank you.

**Comment by jevonearth** [comment]
Hi @DalyIng 

We don't have a debug mode. If you are developing a browser-based project, I recommend you use the browser's dev tools. Looking at the RPC requests on the network tab can be especially useful. 

If you are working on a server-side process, then using either `ngrep` or `whireshark` can also be helpful. If your RPC node is running on port `8732` for example, you can run `ngrep -q -W byline port 8732` which will give you easy to read logs of the traffic to your RPC server.
