### ISSUE TITLE
Incorrect Zarith number encoding/decoding due to rounding errors

### ISSUE THREAD

**Issue by fcremo** [ecadlabs/taquito#264]
Hi! Doyensec has been engaged to perform a security assessment of this library. I will be opening issues to document our findings.

## Description
TypeScript uses the same 64-bit floating point number representation system as JavaScript, IEEE 754. This system can accurately represent whole numbers from -2^53 + 1 to 2^53 - 1. Bigger numbers may incur in a loss of precision. To represent numbers which might exceed these bounds taquito uses BigInt objects. However, two functions responsible to encode and decode Zarith numbers (`zarithEncoder` and `zarithDecoder`) do not use this class and are vulnerable to rounding errors, which might lead to wrong results.

## Reproduction steps
The following code can be used to demonstrate the issue:
```
> taquito_lf = require("./packages/taquito-local-forging")
> zarithEncoder = taquito_lf.encoders.zarith
> zarithDecoder = taquito_lf.decoders.zarith
> Uint8ArrayConsumer = taquito_lf.Uint8ArrayConsumer

> zarithEncoder("9007199254740991")
ffffffffffffff0f
> zarithEncoder("9007199254740992")
8080808080808010
> zarithEncoder("9007199254740993")
8080808080808010
> zarithEncoder("9007199254740994")
8280808080808010

> console.log(zarithDecoder(new Uint8ArrayConsumer(new Uint8Array([0xff,0xff,0xff,0xff,0xff,0xff,0xff,0x0f]))))
9007199254740991
> console.log(zarithDecoder(new Uint8ArrayConsumer(new Uint8Array([0x80,0x80,0x80,0x80,0x80,0x80,0x80,0x10]))))
9007199254740992
> console.log(zarithDecoder(new Uint8ArrayConsumer(new Uint8Array([0x81,0x80,0x80,0x80,0x80,0x80,0x80,0x10]))))
9007199254740992
> console.log(zarithDecoder(new Uint8ArrayConsumer(new Uint8Array([0x82,0x80,0x80,0x80,0x80,0x80,0x80,0x10]))))
9007199254740994
```
Observe that the encoded and decoded numbers are not correct due to the limitations of the IEEE754 internal representation.

We suggest using BigInt to represent the numbers internally in the `zarithEncoder` and `zarithDecoder` functions.

&lt;sales pitch&gt;If you’re looking for an independent vendor to perform security testing or to develop security automation solutions, let us know! [https://doyensec.com](https://doyensec.com)&lt;/sales pitch&gt;

**Comment by jevonearth** [comment]
Hello @fcremo , thank you for the issues! Can you reach out to me directly on security@ecadlabs.com or perhaps via keybase https://keybase.io/jevonearth

Thank you,
