### ISSUE TITLE
String encoding/decoding can violate the Tezos spefication

### ISSUE THREAD

**Issue by fcremo** [ecadlabs/taquito#266]
Hi! Doyensec has been engaged to perform a security assessment of this library. I will be opening issues to document our findings.

## Description
According to the [Michelson documentation](https://tezos.gitlab.io/whitedoc/michelson.html?highlight=ascii#operations-on-strings), strings should be "restricted to the printable subset of 7-bit ASCII, plus some escaped characters". Taquito does not enforce this constraint when encoding or decoding strings, violating the specification.

This is the relevant code from michelson/codec.ts:

```
export const stringEncoder: Encoder<StringValue> = value => {
  const str = Buffer.from(value.string, 'utf8').toString('hex');
  const hexLength = str.length / 2;
  return `01${pad(hexLength)}${str}`;
};

export const stringDecoder: Decoder = (value: Uint8ArrayConsumer) => {
  const str = extractRequiredLen(value);
  return {
    string: Buffer.from(str).toString('utf8'),
  };
};
```

Observe that the strings are encoded and decoded using utf-8. This encoding is equivalent to ASCII in the range allowed by the Tezos specification, however it allows a much wider range of characters with respect to 7-bit ASCII.

The same behaviour can be observed also in the `encodeAnnots` and `decodeAnnots` functions.

You might want to consider to restrict the characters allowed to be encoded/decoded according to the specification.

&lt;sales pitch&gt;If you’re looking for an independent vendor to perform security testing or to develop security automation solutions, let us know! [https://doyensec.com](https://doyensec.com)&lt;/sales pitch&gt;

**Comment by jevonearth** [comment]
Fixed in #272 and released in v6.1.0-beta.0

Thank you for the detailed report and for helping improve Taquito & Tezos.
