### ISSUE TITLE
SPIKE: Setting up the development environment to use the latest node

### ISSUE THREAD

**Issue by AlirezaHaghshenas** [ecadlabs/taquito#2700]
When updating all dependencies, some of them, especially dev_dependencies, depend on newer versions of node than the one we use.

It is possible to build Taquito using one node version, but setup the distributed packages to support older versions of node.

From my understanding, we should be able to do this:

1. Use the lastest LTS (or even the latest node) to develop Taquito. This involves updating the `.nvm` file, as well as keeping the most CI environments on the latest node.
2. (Optional) Setup the integration tests to use an older version of node. This might involve building in one node version, but testing in another.
3. Have test dApps that use the released (or CI prerelease) packages to build their dApp in older versions of node. All currently supported LTS versions are suggested.

Also worth mentioning that Taquito will in fact be running mostly in browsers, not node. For us, the least supported node version is the one that developers can use to develop their dApps. So running the Integration tests in supported nodes is not that important. It is more important to verify Taquito can be used in development projects using older node versions

**Comment by Innkst** [comment]
We confirmed that v16 is EOL in a month, so in the long term we do not have to keep supporting it. 
Also, we are not going to add new Oxford features until the next protocol upgrade, which will also take several months from now.
