### ISSUE TITLE
Remove outdated links from RPC nodes from the Taquito website

### ISSUE THREAD

**Issue by dsawali** [ecadlabs/taquito#2731]
Some RPC nodes in the Taquito website are outdated: https://tezostaquito.io/docs/rpc_nodes/#list-of-community-run-nodes

- Remove TezTools
- Add TzStats RPC under commercial

**Comment by hui-an-yang** [comment]
This has been updated by [PR#2732](https://github.com/ecadlabs/taquito/pull/2732)
Will update this ticket to clean up mumbai nodes on our website instead
