### ISSUE TITLE
enable http keepalive 

### ISSUE THREAD

**Issue by drunkirishcoder** [ecadlabs/taquito#2734]
**Is your feature request related to a problem and use case? Please describe.**

Looking through the code, I don't see an obvious way to enable http keepalive with the underlying HttpBackend. Do I need to create my own HttpBackend wrapper on axios to do that?

**Describe the solution you'd like**

make the keepalive configurable.

**Comment by dsawali** [comment]
Correct, we try to keep HttpBackend in `taquito-http-utils` lean enough for people to extend their own modifiable methods if need be. Although, keep in mind that we're trying to move away from Axios to Node Fetch in an upcoming release. 

You can track the progress here: https://github.com/ecadlabs/taquito/issues/2461
