### ISSUE TITLE
Sending transactions in TalentNet is broken

### ISSUE THREAD

**Issue by keshan3262** [ecadlabs/taquito#2748]
**Description**
The current version of taquito (17.4.0) fails to send any transactions in TalentNet.

**Steps To Reproduce**
1. Create a directory with an empty npm project using `npm init` or `yarn init`.
2. Install `@taquito/signer` and `@taquito/taquito` modules.
3. Create a script with the content below, do not forget to paste the necessary values:
```javascript
const { InMemorySigner } = require('@taquito/signer');
const { TezosToolkit } = require('@taquito/taquito');
const process = require('process');

const senderSecretKey = ''; // Here should be the secret key of the account that has FILM tokens
const receiver = ''; // The receiver of FILM tokens
const tezos = new TezosToolkit('https://rpc.decentralized.pictures');

console.log('Importing account by private key');
InMemorySigner.fromSecretKey(senderSecretKey)
  .then(signer => {
    tezos.setSignerProvider(signer);
    console.log('Sending 1e-6 FILM');

    return tezos.wallet.transfer({ to: receiver, amount: 1, mutez: true }).send();
  })
  .then(operation => {
    console.log(`Operation hash: ${operation.opHash}`);

    process.exit(0);
  })
  .catch(console.error);

```
4. Run it using `node`

**Expected behavior**
Example output:
```
Importing account by private key
Sending 1e-6 FILM
Operation hash: oop9sxn9PobPpZV1vo758DpJJPRag3smGD5LnLf5KNC4HKWujog
```

**Actual behavior**
Example output:
```
Importing account by private key
Sending 1e-6 FILM
HttpResponse: Http error response: (400) Failed to parse the request body: Missing object field signature
    at HttpBackend.<anonymous> (/Users/keshan/cashback-send-script/node_modules/@taquito/http-utils/dist/taquito-http-utils.umd.js:704:31)
    at Generator.throw (<anonymous>)
    at rejected (/Users/keshan/cashback-send-script/node_modules/@taquito/http-utils/dist/taquito-http-utils.umd.js:28:69)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  status: 400,
  statusText: 'Bad Request',
  body: 'Failed to parse the request body: Missing object field signature',
  url: 'https://rpc.decentralized.pictures/chains/main/blocks/head/helpers/scripts/simulate_operation'
}
```

**Desktop (please complete the following information):**
 - OS: macOS
 - Node version: 18

**Additional context**
This bug cannot be reproduced with taquito version 17.1.1.

**Comment by dsawali** [comment]
In your example, you are setting the signer value for the Contract API, but are using the Wallet API. This causes your request to not have a signature, hence throwing the bad request.

What is recommended is to use `const op = Tezos.contract.transfer({ transfer params })`

and then await the confirmation using `await op.confirmation()`

**Comment by jevonearth** [comment]
Hi @alex-tsx, @keshan3262 

TalentNet is on a variant (with minimal changes, as I understand it) of the Itaca protocol. Taquito can't viably support that many protocols in its stable releases. My understanding is that T4L3NT Net pin to version Taquito version 12.0.3. Using that release is probably the most stable option.  If you can let me know what you are trying to achieve, I may be able to come up with some additional ideas.

**Comment by keshan3262** [comment]
@dsawali sorry, I did replace `tezos.wallet` with `tezos.contract` but the result was the same. It looks like @jevonearth is right.

**Comment by dsawali** [comment]
@keshan3262 interesting, I was not aware of the nuances of the Decentralized pictures network being pinned to Ithaca. 

and thanks @jevonearth for the context

**Comment by dsawali** [comment]
@alex-tsx we've updated our estimates recently (around v17.1.0 ish) to follow Nomadic's guidance to use `simulateOperation` instead of `runOperation`.

Additionally, we weren't able to replicate your issue with the same code on any other testnet. Like Jev mentioned, the TalentNet network is based on a much older protocol version.

**Comment by hui-an-yang** [comment]
Hello @alex-tsx 

From tezos's open api definition both `run_operation` and `simulate_operation` request body both has `signature` field but it's optional. Previously, when we were using run_operation we pass on a stub signature and know that it won't be verified against the payload. Now that we changed to simulate_operation as tezos core team suggested we find it unnecessary to pass on a stub signature like before. I have no context of api definition/behaviour of TalentNet(ithaca protocol) that I don't know what's the request body looks like for simulate_operation and if the rpc endpoint will verify the signature against payload either. This is the case for now, if you can provide the context of what the request body looks like for simulate_operation and confirm the rpc endpoint won't verify the signature. We can look into checking current tezos protocol if passing a stub signature will work for for both TalentNet and Tezos. Hope this brings some clarity:)

**Comment by hui-an-yang** [comment]
To evaluate the tradeoff of passing a stub signature to runOperation when simulating to consider adding it for compatibility of TalentNet

**Comment by hui-an-yang** [comment]
hello @alex-tsx 
it seems tezos current protocol doesn't validate the signature sent to make simulate/operations rpc calls, we've added back stub_signature in v19.1. Am hoping using v19.1 will solve this issue you face with this ticket :)
