### ISSUE TITLE
Use default instead of main for smart contract default entrypoint

### ISSUE THREAD

**Issue by carte7000** [ecadlabs/taquito#275]
Currently when a smart contract only have 1 entrypoint (default) Taquito will create a synthetic method called main. This is confusing because it really refers to the default entrypoint in Michelson

http://tezos.gitlab.io/whitedoc/michelson.html#the-default-entrypoint

This issue is about change this synthetic entrypoint name from `main` to `default`

This will cause breaking change with implementation that use the current `main` methods

**Comment by jevonearth** [comment]
If or when we make this change, we must update this SE question: https://tezos.stackexchange.com/questions/2234/taquito-default-entrypoint-not-found

**Comment by jevonearth** [comment]
This will be a breaking change to users of Taquito, but one worth making. Let's make this change on either 6.2 or v7.
