### ISSUE TITLE
Update Teams Building With Taquito on our website

### ISSUE THREAD

**Issue by Innkst** [ecadlabs/taquito#2758]
Update Teams Building With Taquito

1. Remove: 
- Interpop
- Kolibri
- Sweet
- Staker DAO
- Radion
2. Add:
- https://objkt.com/
- Plenty
- Teia
- Mooncakes
- https://www.fxhash.xyz/

**Comment by jevonearth** [comment]
Add;

- https://objkt.com/
- Plenty
- Teia
- Mooncakes
- https://www.fxhash.xyz/
