### ISSUE TITLE
BigMap.get with passing a defaultValue as param

### ISSUE THREAD

**Issue by DalyIng** [ecadlabs/taquito#277]
Can we do something similar to `myMap.get(key, defaultValue = None)` of smartPy with Taquito?
An instruction like: 

```
const myContract = await Tezos.contract.at(contractAddress);
const contractStorage = await myContract.storage();
const value = await contractStorage.myMap.get(key, defaultValue = 0)
```

Thnak you.

**Comment by jevonearth** [comment]
Thanks @DalyIng 

Instead of making this default param optional, we will change the new Get method as follows;

Get throws an error on an unknown key. Let's change this to not throw an error, and return undefined when the key is unknown.

This allows for terse/convenient handling undefined values using `nullish coaslesing` 

const value = await contractStorage.myMap.get(key) ?? 0

**Comment by Sm00g15** [comment]
From the looks of `michelson-map.spec.ts` it looks like `undefined` is already thrown whenever a key isn't found. The tests passes fine.

`describe('Michelson map', () => {
  describe('get', () => {
    it('return undefined when key is not present', () => {
      const map = new MichelsonMap();
      expect(map.get('test')).toBeUndefined();
    });
  });`

**Comment by DalyIng** [comment]
Hello @jevonearth  @Sm00g15 , the **get** is always throwing an _error_ not an _undefined_, I'm using the 6.0.3-beta.0. Am I getting something wrong?
Thank you.

**Comment by Sm00g15** [comment]
Hey @DalyIng, I’m working on a fix for that at the moment and it will most likely be merged in tomorrow

**Comment by DalyIng** [comment]
Ok, thanks @Sm00g15 .

**Comment by Sm00g15** [comment]
Hey @DalyIng this has proven to be more troublesome than I thought, but I just want to let you know I'm still working on it and will let you know as soon as I have merged a fix!

**Comment by DalyIng** [comment]
Hey @Sm00g15 , thank you, appreciate that! Good luck!

**Comment by Sm00g15** [comment]
@DalyIng this PR has been submitted here: #328

**Comment by DalyIng** [comment]
Hi @Sm00g15, this feature will be released in the next version? Or already published?
Thanks.
