### ISSUE TITLE
 RPC api links in reference doc are broken

### ISSUE THREAD

**Issue by itkach** [ecadlabs/taquito#278]
Consider, for example, the following section of reference documentation:
https://tezostaquito.io/typedoc/classes/_taquito_rpc.rpcclient.html#getblock

It tries to point to corresponding Tezos RPC API documentation with the following link:
http://tezos.gitlab.io/master/api/rpc.html#get-block-id but the link is inaccessible, gives 401

**Comment by jevonearth** [comment]
Thanks for the report @itkach
