### ISSUE TITLE
Update Nx version to 17 to resolve netlify build failures

### ISSUE THREAD

**Issue by dsawali** [ecadlabs/taquito#2799]
Recent Netlify builds have been failing unexpectedly with this error below:
```
[commonjs--resolver] Failed to resolve entry for package "@taquito/taquito". The package may have incorrect main/module/exports specified in its package.json.
11:09:15 AM: error during build:
11:09:15 AM: Error: Failed to resolve entry for package "@taquito/taquito". The package may have incorrect main/module/exports specified in its package.json.
```

Supposedly it should be fixed with Nx version 17, according to this issue https://github.com/typescript-eslint/typescript-eslint/issues/7734

Update Nx to v17 from our current version of v16.10.0

**Comment by hui-an-yang** [comment]
We look to migrate to Cloudflare soon and don’t see the need to update to nx17 now for Netlify
