### ISSUE TITLE
TransferTicketParams interface not exported on Taquito v19.0.2

### ISSUE THREAD

**Issue by zamrokk** [ecadlabs/taquito#2827]
I am trying to use the Interface `TransferTicketParams  `for ticket transfer on Taquito` v19.0.2` but it seems to not be exported on the dist folder. If I look on the v19.0.2 branch, I can find the export 

![image](https://github.com/ecadlabs/taquito/assets/2536368/4b78dcca-ab34-45a4-82f3-be9f62d4b6aa)

![image](https://github.com/ecadlabs/taquito/assets/2536368/e2734bd6-1a28-4566-8423-3e260001869d)

**Comment by zamrokk** [comment]
VsCode find me the import on this file , not sure it is normal ?

`import { TransferTicketParams } from "@taquito/taquito/dist/types/operations/types";`

**Comment by hui-an-yang** [comment]
hello @zamrokk 

PR2816 have fixed and will be included in the next release. In the mean time, here's how to use the preview build 
`npm i @taquito/taquito@19.0.2-0f6f366-- --registry https://npm.preview.tezostaquito.io/`
