### ISSUE TITLE
Design and Implement Timelock feature in Taquito

### ISSUE THREAD

**Issue by dsawali** [ecadlabs/taquito#2843]
With the re-release of the Timelock feature, write a design document and implement Timelock in Taquito.

Eugene has been experimenting with a TS Timelock implementation, here: https://github.com/ecadlabs/timelock-ts/blob/main/src/timelock_test.ts

Requirements
- Write up design document for the Timelock feature in Taquito
- Implement Taquito's own implementation of Timelock

Readings:
- https://tezos.gitlab.io/oxford/timelock.html?highlight=timelock
- https://docs.tezos.com/smart-contracts/data-types/crypto-data-types#timelocks

**Comment by hui-an-yang** [comment]
subsequent ticket to exercise timelock feature in integration test and/or test-dapp
