### ISSUE TITLE
[Paris] Investigate DAL and identify parts that are relevant to Taquito

### ISSUE THREAD

**Issue by dsawali** [ecadlabs/taquito#2867]
Some DAL features are included as part of the protocol P update. Investigate and identify parts of DAL that are actionable in Taquito.

Create follow up tickets accordingly from the findings of the investigation.

**Comment by hui-an-yang** [comment]
will create 4 tickets to cover below 
* new consensus_operation
	- `Attestation_with_dal` add rpc type and forger (new tag 23)
	- `Endorsement_with_dal` add rpc type? (forger mapping default to Attestation_with_dal)
* new manager_operation
	- `dal_publish_commitment` rpc type, forger, and contractAPI supports
* `Smart_rollup_refute` rpc type param change
	- added dal_page_proof `{kind: “smart_rollup_refute”, refutation: {properties: “move”, step: {input_proof: {properties: “reveal_proof”, reveal_proof: {reveal_proof_kind: “dal_page_proof”, dal_page_id: {published_level: number, slot_index: number, page_index: number}, dal_proof: string}}}}}`
	- added dal_parameters_proof `{kind: “smart_rollup_refute”, refutation: {properties: “move”, step: {input_proof: {properties: “reveal_proof”, reveal_proof: {reveal_proof_kind: “dal_parameters_proof”}}}}}`
* new rpc endpoints 
	- `/context/dal/confirmed_slot_headers_history`
	- `/context/dal/shards`
