### ISSUE TITLE
[Paris] Test and adjust parameters for 10s block time

### ISSUE THREAD

**Issue by dsawali** [ecadlabs/taquito#2868]
Protocol Paris plans to reduce block time from 15s to 10s. 

Run our current tests against new protocol P to sanity check Taquito for 10s block times. 

Make adjustments accordingly.

relevant changelog entry:
https://tezos.gitlab.io/protocols/019_paris.html#s-blocks-time-mr-11288

**Comment by hui-an-yang** [comment]
reduce block time in mainly protocol constant value changes will be taken care of in https://github.com/ecadlabs/taquito/issues/2869
