### ISSUE TITLE
[Sandbox] Remove Flextesa tests from CI 

### ISSUE THREAD

**Issue by dsawali** [ecadlabs/taquito#2977]
With Flextesa's development halting, we currently do not have an alternative for Tezos sandbox testing.

Remove references (for tests) from Taquito CI so that we have no more artifacts that point to older versions of Flextesa.
Keep in mind that now these 2 tests will be untested:
- drain delegate integration test
- ballot and proposals operation test

We have expressed our interest on having a Tezos sandbox here in issue linked below:
https://gitlab.com/tezos/tezos/-/issues/7198

**Comment by dsawali** [comment]
alternatively, look into adding a separate workflow to test these operations on testnet. 
- Could run independently (slow running weekly tests?)
- Could run in the same CI but with separate workflow

**Comment by hui-an-yang** [comment]
can no longer fetch flextesa nairobi protocol anymore 
<img width="1382" alt="image" src="https://github.com/ecadlabs/taquito/assets/106410553/7b3d2974-fecd-4043-88a7-b485f9cbf2dc">
