### ISSUE TITLE
Missing fields in METADATA_BALANCE_UPDATES_CATEGORY in @taquito 19

### ISSUE THREAD

**Issue by psmolinsky** [ecadlabs/taquito#2978]
**Description**
There are some fields missing in `METADATA_BALANCE_UPDATES_CATEGORY` in `@taquito/rpc` despite they are present in Tezos RPC schema for current *Oxford* protocol or previous protocols.

Missing fields from *Oxford* protocol:
- `lost attesting rewards`

Missing fields from older protocols - What is the reason for their removal? Were they not used at all?
- `double signing evidence rewards`
- `fees`
- `legacy_deposits`
- `legacy_fees`
- `legacy_rewards`
- `rewards`

**Notes**
- This refers to #2816.
- Sorry for very late response, but [our development](https://dappetizer.dev/) is heavily slowed down because of no funding from Tezos Foundation. 
- `people can't get operation response from previous protocol anymore` I don't get it. Taquito has API to fetchy any block from entire blockchain history. Therefore all protocols should be supported, don't they?
- `If you have particular use case` [Our product](https://dappetizer.dev/) is a framework for building Tezos indexers. So it fetches blocks from the past using Taquito.

**Comment by dsawali** [comment]
Hello @psmolinsky, yeah you bring up a good point. We will re-add them into Taquito the next release, thanks for the callout.
