### ISSUE TITLE
Update docs and runable code to use carthagenet instead of babylonent

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taquito#300]
The Taquito docs and runnable examples presently target `babylonnet`. 

Interacting with `babylonnet` has diminished value as `mainnet` has updated to 006/Carthagnet. The `babylonnet` is expected to stop working by the end of March.

Update all Taquito docs to to use `carthagenet` as the default testnet. The keys api on tez.ie now supports `carthagnet`.

**Comment by Sm00g15** [comment]
I've got most of this done. Just need to launch a new smart contact for carthagenet for the contract calls in https://tezostaquito.io/docs/making_transfers ; What's the easiest way to to launch a ligo contract atm @jevonearth ?

**Comment by Sm00g15** [comment]
> The Taquito docs and runnable examples presently target `babylonnet`.
> 
> Interacting with `babylonnet` has diminished value as `mainnet` has updated to 006/Carthagnet. The `babylonnet` is expected to stop working by the end of March.
> 
> Update all Taquito docs to to use `carthagenet` as the default testnet. The keys api on tez.ie now supports `carthagnet`.

Shall I update the integration tests to carthagenet as well for this ticket?

**Comment by jevonearth** [comment]
https://ide.ligolang.org/ has been updated to support carthagenet now FWIW.

**Comment by jevonearth** [comment]
Merged and deployed to the public site. Nice work @Sm00g15

**Comment by Sm00g15** [comment]
> Merged and deployed to the public site. Nice work @Sm00g15

Thanks @jevonearth
