### ISSUE TITLE
RPC changes for protocol Q (part 1)

### ISSUE THREAD

**Issue by dsawali** [ecadlabs/taquito#3022]
Protocol Q brings about a list of RPC deprecation

All strikethrough'd bullet point will NOT be implemented

Disclaimer, the path `../` will be short for `/chains/<chain_id>/blocks/<block_id>/context/delegates/<baker_pkh>/`

Renames:
- `GET ../current_frozen_deposits` is **renamed** to `GET ../total_staked`, the old path is **deprecated**
- ~`GET ../total_delegated_stake` is renamed to `GET ../external_staked`, old path is deprecated~
- ~`GET ../current_baking_power` is renamed to `GET ../baking_power`, old path is deprecated~
- ~`GET ../delegated_contracts` is renamed to `GET ../delegators`, old path is deprecated~
- `GET ../full_balance` is renamed to `GET ../own_full_balance`, old path is deprecated
- ~`GET ../unstaked_frozen_deposits` is renamed to `GET ../total_unstaked_per_cycle`, old path is deprecated~

Additions:
- Added `GET ../total_delegated` endpoint, which returns the amount that counts as delegated to the baker for the purpose of computing its baking rights. This includes tez owned by all delegators including the baker itself, but excludes staked tez (MR: [!14176](https://gitlab.com/tezos/tezos/-/merge_requests/14176))
- Added `GET ../external_delegated`, which returns the amount of non-staked tez owned by all delegators except for the baker itself. (MR [!14187](https://gitlab.com/tezos/tezos/-/merge_requests/14187))
- Added `GET ../own_staked` and `GET ../own_delegated`, these are similar to `total_staked` and `total_delegated`, except they only consider tez owned by the baker itself
- 

Deprecations (only):
- Deprecated RPC `GET ../staking_balance`. Staking balance value can now be obtained by adding values of `GET ../total_staked` and `GET ../total_delegated` together
- Deprecated RPC `GET ../delegated_balance`, Delegated balance value can now be obtained by adding values of `GET ../external_staked` and `GET ../external_delegated` together
- Deprecated RPC `GET ../delegated_balance`. To get its value, you can call `GET ../total_staked` on the last block of 3 cycles ago.
- Deprecated RPC `GET ../frozen_deposits_limit`, currently irrelevant since activation of AI and staking

**Comment by hui-an-yang** [comment]
Currently, in taquito rpc package we only support two endpoints with path `/chains/<chain_id>/blocks/<block_id>/context/delegates/<baker_pkh>/`
one is getDelegates - `/chains/<chain_id>/blocks/<block_id>/context/delegates/<baker_pkh>/`
the other is getVotingInfo - `/chains/${this.chain}/blocks/${block}/context/delegates/${address}/voting_info`
So the above renames and deprecations is not relevant to taquito in q development.
As for additions we usually don't support baker related rpc assuming they'll use octez-client instead, we usually only add support on request. 
Unless you see significant of adding them now, we can discuss
