### ISSUE TITLE
Deprecate legacy encoding of tickets `(Pair (Pair _ _) _)` 

### ISSUE THREAD

**Issue by dsawali** [ecadlabs/taquito#3024]
The legacy encoding of tickets `(Pair (Pair _ _) _)` will be deprecated in protocol Q in favour of the `Ticket` constructor that was introduced in Paris.

This new notation will notably be used in operations metadata.

Investigate and implement necessary changes if needed.

relevant MRs: MRs [!11619](https://gitlab.com/tezos/tezos/-/merge_requests/11619) [!11620](https://gitlab.com/tezos/tezos/-/merge_requests/11620) [!12048](https://gitlab.com/tezos/tezos/-/merge_requests/12048)

**Comment by hui-an-yang** [comment]
this change is no longer included in protocol Q

**Comment by dsawali** [comment]
closing due to the change not being applicable in proto Q
