### ISSUE TITLE
create transactions locally and avoid sending tx.

### ISSUE THREAD

**Issue by roccomuso** [ecadlabs/taquito#3026]
Is there a way to pass params and prevent `tezosToolkit.contract.transfer(...)` method from broadcasting the tx?
I wanna split signing and rpc calls.

**Comment by hui-an-yang** [comment]
Hello @roccomuso 
Yes, you can make use of prepareProvider with `Tezos.prepare.transaction(...)` and `Tezos.prepare.toForge(...)`
Can reference operation flow documentation for more detail
https://taquito.io/docs/operation_flow#customizing-the-operation-flow
https://taquito.io/docs/prepare
