### ISSUE TITLE
Module not found: Can't resolve '@taquito/tezbridge-signer'

### ISSUE THREAD

**Issue by claudebarde** [ecadlabs/taquito#309]
Hi!
I am trying to integrate Taquito into my dapp using Tezbridge as a signer.
However, when I import the TezBridgeSigner as per the documentation, I receive the following message from the React app: "Module not found: Can't resolve '@taquito/tezbridge-signer'".
I checked the node modules folder and indeed, there is no "tezbridge-signer" subfolder and I cannot find any other mention of the Tezbridge signer.
I am using Taquito version 6.1.0-beta.0.
Thank you

**Comment by claudebarde** [comment]
Nevermind, I didn't realize I have to install this as a separate module, sorry 😬

**Comment by jevonearth** [comment]
Thanks @claudebarde 

For others happening upon this issue. The TezBridge plugin `https://www.tezbridge.com/plugin.js` must be imported using a `<script>` tag. There is no npm package available that we are aware of.

**Comment by claudebarde** [comment]
Exactly, I did `npm install @taquito/tezbridge-signer` and added the script tag with the Tezbridge plugin in the HTML file, if that can help another beginner like me :)
