### ISSUE TITLE
Setup docusaurus for mermaid support

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taquito#311]
[Mermaid](https://mermaidjs.github.io/#/) diagrams are very useful for docs

Set up docusaurus so that we can create mermaid diagrams inline within our docs.

See:
https://github.com/facebook/docusaurus/issues/1258#issuecomment-594393744

**Comment by mbykovskyy** [comment]
This issue is dependent on https://github.com/temando/remark-mermaid/issues/8
