### ISSUE TITLE
Sending a transaction to contract that requires a bytes parameter fails validation

### ISSUE THREAD

**Issue by drewstaylor** [ecadlabs/taquito#319]
The type declaration for a bytes value is listed in the docs as a string: https://tezostaquito.io/typedoc/modules/_taquito_local_forging.html#bytesvalue

However, sending either a bytes string or a bytes array doesn't pass the validator.

What I am sending to the contract:
```calling args. (4)
0: 1
1: 0
2: "0x29f920a4f69c6713f133c3e5a9a497f857cd88d8438a039d4a51b256559992f8"
3: 1
length: 4
__proto__: Array(0)
```
Call response from taquito:

```BytesValidationError {value: "0x29f920a4f69c6713f133c3e5a9a497f857cd88d8438a039d4a51b256559992f8", token: BytesToken, name: "BytesValidationError", message: "[rewards_h] Invalid bytes: 0x29f920a4f69c6713f133c3e5a9a497f857cd88d8438a039d4a51b256559992f8"}
value: "0x29f920a4f69c6713f133c3e5a9a497f857cd88d8438a039d4a51b256559992f8"
token: BytesToken
val: {prim: "bytes", annots: Array(1)}
idx: 3
fac: ƒ createToken(val, idx)
createToken: ƒ createToken(val, idx)
__proto__: ComparableToken
name: "BytesValidationError"
message: "[rewards_h] Invalid bytes: 0x29f920a4f69c6713f133c3e5a9a497f857cd88d8438a039d4a51b256559992f8"
__proto__: TokenValidationError```

**Comment by drewstaylor** [comment]
Same error is thrown if the 0x prefix is removed:

``ERROR CREATING PUZZLE: => BytesValidationError {value: "29f920a4f69c6713f133c3e5a9a497f857cd88d8438a039d4a51b256559992f", token: BytesToken, name: "BytesValidationError", message: "[rewards_h] Invalid bytes: 29f920a4f69c6713f133c3e5a9a497f857cd88d8438a039d4a51b256559992f"}```

**Comment by carte7000** [comment]
Hi @drewstaylor, thanks for reporting this issue. Bytes should not contain the `0x` prefix so your last comment is correct. However, in your last example it seems that your last byte is missing an `8` can you confirm this? 

If you try to send this hex string `29f920a4f69c6713f133c3e5a9a497f857cd88d8438a039d4a51b256559992f8` does it still fails with a validation error?

**Comment by drewstaylor** [comment]
Ah alas, I can see my mistake now that you've pointed it out. It looks like I truncated the end of the string when I was removing the prefix.

**Comment by drewstaylor** [comment]
I just checked and as expected it works with the correct string length. Thanks. Sorry for the false alarm :)
