### ISSUE TITLE
Getting 500 status when successfully looking up a contract

### ISSUE THREAD

**Issue by Sm00g15** [ecadlabs/taquito#344]
I'm looking up this contract on Carthagenet (https://better-call.dev/carthage/KT1HqWsXrGbHWc9muqkApqWu64WsxCU3FoRf/script)

<img width="846" alt="Screen Shot 2020-04-02 at 8 40 17 PM" src="https://user-images.githubusercontent.com/14209806/78222791-4c707e00-7522-11ea-8ea0-6eb1e91d7cb7.png">

As shown here I'm getting the proper response from the RPC layer (this is just the JSON code delivered by the RPC layer rendered directly into the HTML):
<img width="1090" alt="Screen Shot 2020-04-02 at 8 40 08 PM" src="https://user-images.githubusercontent.com/14209806/78222875-775ad200-7522-11ea-9262-dde1f5724d2a.png">

However you can also see below the JSON code from the RPC I"m getting a 500 internal server error. Any idea why this would be happening on a successful contract lookup?

**Comment by AndrewKishino** [comment]
I believe it has to do with importing a fundraiser account. It's trying to do an activation of the key on import. Take a look at the code in tezos-signer: https://github.com/ecadlabs/taquito/tree/master/packages/taquito-signer/src/import-key.ts

**Comment by Sm00g15** [comment]
Ahhhh yes, that makes sense! Thank you @AndrewKishino
