### ISSUE TITLE
Change delegate is pending indefinitely

### ISSUE THREAD

**Issue by oleiba** [ecadlabs/taquito#345]
This happens only on mainnet, not reproducible on Carthagenet.
Taquito version I use is of tag 6.1.1-beta.0.

The scenario:

0. Start with a tz.. address with some balance
1. Change/Stake to custom baker X
2. Wait for confirmation.
3. Change to custom baker Y
4. **The node responds with a hash like everything is OK, but the transaction never gets into the blockchain.**

Here's a testcase:
```js
    // 1. delegate (source account needs to have balance)
    const source = 'tz2RR83xY6b1F7jAC2QXbNYnZVRiZgY485HB';
    const delegateAddress1 = 'tz2TSvNTh2epDMhZHrw73nV9piBX7kLZ9K9m';
    const delegateAddress2 = 'tz1gfArv665EUkSg2ojMBzcbfwuPxAvqPvjo';

    op = await setDelegate({ source, delegate: delegateAddress1 });
    await op.confirmation();

    // 2. delegate to a new delegate
    op = await setDelegate({ source, delegate: delegateAddress2 });
    await op.confirmation();  // THIS WILL NEVER END
```

**Comment by jevonearth** [comment]
Hi @oleiba 

I tested this on `mainnet` using your code, and it succeeds. 

Can you let me know what version of taquito you are using, and which public node? Then I'll try re-produce with the same version/node.

Thanks!

**Comment by gbenattar** [comment]
Hi,
Here is what we use

```
private static RPC_URL = {
    babylonnet: 'https://rpcalpha.tzbeta.net/',
    mainnet: 'https://mainnet.tezrpc.me'
};
```

It is 100% reproducible on our side. We noticed that for some reasons paying more fees can get the second transaction to succeed but if fees is the issue we would expect taquito to throw before the broadcast.

**Comment by oleiba** [comment]
It appears the issue is that we used an excessive gas limit from our side.
Closing for now, thank you for the help.
