### ISSUE TITLE
sending optional parameter ?

### ISSUE THREAD

**Issue by kafcioo** [ecadlabs/taquito#349]
Is it possible to send an optional parameter? If so how do we do it, for example calling endpoint 
`setSafelistAddress ((option address) :newMbSafelistAddress)`

**Comment by jevonearth** [comment]
Hi Kafcioo, can you share the address of your contract deployed to carthagenet?

**Comment by mbodecek** [comment]
I was able to do this by omitting the argument completely

```js
await Tezos.contract.at(...).methods.setSafelistAddress().send()
```

This works nicely if the parameter layout allows it (the optional parameter is at the end). Not sure if there is a way to do it otherwise

**Comment by jevonearth** [comment]
We have updated docs that cover optional args here: https://tezostaquito.io/docs/complex_parameters

If this is still an issue, please feel free to reopen.
