### ISSUE TITLE
Add more test coverage for the getBlock endpoint

### ISSUE THREAD

**Issue by carte7000** [ecadlabs/taquito#35]
Test more operation variants for the `getBlock` endpoint in `@taquito/rpc`
- [ ] add tests based on data from proto 5, 6 and 7
- [ ] test other operations (transaction, origination, ...)

see comment https://github.com/ecadlabs/taquito/issues/35#issuecomment-727065645

**Comment by jevonearth** [comment]
Related to #27

**Comment by Innkst** [comment]
Need to evaluate the current coverage

**Comment by roxaneletourneau** [comment]
Current state:
There is only one test in the taquito-rpc.spec.ts file for getBlock().
The test "mocks" the return value with an example of data from proto 4.
There is only an operation of kind `endorsement` that is tested.

We could:
- add tests based on data from proto 5, 6 and 7
- test other operations (transaction, origination, ...)

**Comment by michaelkernaghan** [comment]
There area these tests now:

import { CONFIGS } from "./config";
import { RpcClient } from '../packages/taquito-rpc/src/taquito-rpc';


CONFIGS().forEach(({ rpc }) => {
    const client = new RpcClient(rpc);

    describe(`Taquito RPC: ${rpc}`, () => {
        describe('getBlock', () => {
            it('should find get a block using default syntax', async (done) => {
                // defaults to /chains/main/blocks/head/
                const block = await client.getBlock();

                expect(block.protocol).toBeTruthy();
                done();
            })
            it('should get a block using head and tilde syntax', async (done) => {
                const block = await client.getBlock({ block: 'head~2' });
                const blockHeader = await client.getBlockHeader({ block: block.hash })

                expect(block.header.predecessor).toEqual(blockHeader.predecessor);
                done();
            })
            it('should get a block using hash and tilde syntax', async (done) => {
                const block = await client.getBlock();
                const predecessorBlock = await client.getBlock({ block: `${block.hash}~1` })

                expect(predecessorBlock.hash).toEqual(block.header.predecessor);
                done();
            })
        })
    })
})

**Comment by michaelkernaghan** [comment]
this is referring to https://github.com/ecadlabs/taquito/blob/master/packages/taquito-rpc/test/taquito-rpc.spec.ts#L654

**Comment by michaelkernaghan** [comment]
I've added one test for transactions. I want to see it all works. Then we can come back and do more.
