### ISSUE TITLE
Update tzip-10 to use latest beacon-sdk (0.0.3-beta.2)

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taquito#354]
The `tzip-10-wallet-provider-api` branch needs to update the latest `@airgap/beacon-sdk` 

They renamed and moved around several types. This SDK also supports network selection (mainnet/testnet/sandbox). Taquito has some types defined for this already, but they will need to be adjusted.

The SDK is published to NPM (https://www.npmjs.com/package/@airgap/beacon-sdk), the source repo is here: https://github.com/airgap-it/beacon-sdk

I recommend to test the functionality using: https://github.com/ecadlabs/tacowallet and https://github.com/ecadlabs/taquito-demo

**Comment by AndrewKishino** [comment]
Accidentally pushed to the branch which then merged this PR...
