### ISSUE TITLE
I get 'Type 'Generator' is not generic.' error trying to use taquito library in "@ionic/angular": "^5.0.0",

### ISSUE THREAD

**Issue by baahkusi** [ecadlabs/taquito#356]
```
ERROR in node_modules/@taquito/michelson-encoder/dist/types/michelson-map.d.ts:37:13 - error TS2315: Type 'Generator' is not generic.

37     keys(): Generator<K>;
               ~~~~~~~~~~~~
node_modules/@taquito/michelson-encoder/dist/types/michelson-map.d.ts:38:15 - error TS2315: Type 'Generator' is not generic.

38     values(): Generator<T>;
                 ~~~~~~~~~~~~
node_modules/@taquito/michelson-encoder/dist/types/michelson-map.d.ts:39:16 - error TS2315: Type 'Generator' is not generic.

39     entries(): Generator<[K, T]>;

```

**Comment by jevonearth** [comment]
Hi @baahkusi, thanks for using Taquito!

Can you let me know what version of taquito you are using, and some additional details of the project that is failing to build?

**Comment by baahkusi** [comment]
"@taquito/taquito": "^6.2.0-beta.0",

**Comment by baahkusi** [comment]
> Hi @baahkusi, thanks for using Taquito!
> 
> Can you let me know what version of taquito you are using, and some additional details of the project that is failing to build?

**Comment by baahkusi** [comment]
> Hi @baahkusi, thanks for using Taquito!
> 
> Can you let me know what version of taquito you are using, and some additional details of the project that is failing to build?

I am using "@taquito/taquito": "^6.2.0-beta.0",

**Comment by jevonearth** [comment]
Can you clarify if how your project is using `@ionic/angular`? Is this your own project that you are developing, or are you building one of our demo projects? 

If you can provide me with enough details so I can reproduce your issue, then I can investigate. :)

**Comment by baahkusi** [comment]
> Can you clarify how your project is using `@ionic/angular`? Is this your own project that you are developing, or are you building one of our demo projects?
> 
> If you can provide me with enough details so I can reproduce your issue, then I can investigate. :)

I am building an ionic mobile app. It is my own project. Here is the package.json

`{
  "name": "mysafechain",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~8.2.14",
    "@angular/cdk": "~8.2.3",
    "@angular/common": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/http": "^7.2.16",
    "@angular/material": "^8.2.3",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "@ionic-native/barcode-scanner": "^5.23.0",
    "@ionic-native/core": "^5.0.7",
    "@ionic-native/file": "^5.23.0",
    "@ionic-native/file-transfer": "^5.23.0",
    "@ionic-native/globalization": "^5.23.0",
    "@ionic-native/native-storage": "^5.23.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^5.0.0",
    "@ngx-translate/core": "^12.1.2",
    "@ngx-translate/http-loader": "^4.0.0",
    "@taquito/taquito": "^6.2.0-beta.0",
    "blakejs": "^1.1.0",
    "cordova-plugin-file-transfer": "^1.7.1",
    "cordova-plugin-globalization": "^1.11.0",
    "cordova-plugin-nativestorage": "^2.3.2",
    "core-js": "^2.5.4",
    "crypto-js": "^4.0.0",
    "file-saver": "^2.0.2",
    "hammerjs": "^2.0.8",
    "ngx-papaparse": "^3.0.4",
    "random-js": "^2.1.0",
    "rxjs": "~6.5.1",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.20",
    "@angular/cli": "8.3.26",
    "@angular/compiler": "~8.2.14",
    "@angular/compiler-cli": "~8.2.14",
    "@angular/language-service": "~8.2.14",
    "@ionic/angular-toolkit": "^2.1.1",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "phonegap-plugin-barcodescanner": {},
      "cordova-plugin-file-transfer": {},
      "cordova-plugin-nativestorage": {},
      "cordova-plugin-globalization": {}
    }
  }
}`

**Comment by jevonearth** [comment]
Hi @baahkusi 

This is likely because you are using a rather old version of Typescript. [Generator](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-6.html) was added in Typescript 3.6. I recommend you update your project to the latest Typescript 3.8.x release.

**Comment by baahkusi** [comment]
That is a problem since in my specific case it need to use "typescript": "~3.4.3". Do you have any suggestions?

**Comment by jevonearth** [comment]
You can either use javascript (which I discourage) or you need to update to a newer version of typescript. At this point, 3.6 should work. We will be making typescript 3.8.x mandatory in our v7 release later this year, so I do encourage you to upgrade sooner rather than later.
