### ISSUE TITLE
Remove default RPC address so that users make their own choice

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taquito#388]
# Problem

Taquito is configured to use a default RPC node. We took this approach so that users can get started quickly, and Taquito should "just work" with minimal fiddling. 

The problem is that users of Taquito can easily punt on the decision and assume the default is safe. This leads to a lot of applications relying on our default node and thus centralising a part of the ecosystem on one node. There's more problems with offering this default node, but that's the gist of it. 

# Action

* Remove the default node configuration, forcing the user to set their own
* Implement a helpful error message so when users don't set it, they get some clear hints on the what/why/how to proceed
* Create a documentation page with links to community-run nodes and to instructions on how to run your own node. Explain the tradeoffs and encourage the Taquito user to DYOR
* Make the change prominent in release announcements so as not to blindside users with this breaking change.

# Alternative

An alternative would have been to replace the default URL (https://api.tez.ie/rpc/carthagenet) with an unopinionated value as http://localhost:8732/, which is the default value when running a node locally. It would have reduced the magnitude of the breaking change by only impacting applications that actually use the default RPC URL. All applications that currently configure their own RPC by doing setProvider({rpc: ...}) or setRpcProvider(..) would not have been affected by the change.

However, we decided to go with the other solution because setting the URL to http://localhost:8732/ does not satisfy many use cases. Also, changing the default URL to localhost would not warn people using the default with compile-time errors; they would get a connection refused error from localhost.

**Comment by roxaneletourneau** [comment]
Public nodes;
- Tezos Ukraine
- https://tezos.giganode.io/
- SmartPy Nodes:
- Mainnet: https://mainnet.smartpy.io
- Zeronet: https://zeronet.smartpy.io
- Carthagenet: https://carthagenet.smartpy.io
- Cryptium Labs nodes:
- Mainnet: http://mainnet.tezos.cryptium.ch:8732
- Carthagenet: http://carthagenet.tezos.cryptium.ch:8732
- Luke Youngblood nodes (maybe affiliated with the foundation, I'm not sure)
- https://rpc.tzbeta.net/
