### ISSUE TITLE
Which format of secret keys are accepted?

### ISSUE THREAD

**Issue by Sword-Smith** [ecadlabs/taquito#390]
In your [documentation](https://tezostaquito.io/docs/inmemory_signer#usage), you have
```
Tezos.setProvider({signer: await InMemorySigner.fromSecretKey('you_private_key')})
```

But it is not clear to me which format I can use for the secret key. Can I use hex, or do I have to use the thing that starts with 'p2sk'? And if I have to use the one that starts with 'p2sk', how do I convert to that format given a hex string or an Uint8Array.

I would prefer to use an entropy size of 256 bits.

**Comment by jevonearth** [comment]
Hello @Sword-Smith 

`importKey` should support plain or encrypted secrets in base58 encoding.

Here are some examples. The passphrase for the encrypted examples is `test`:

```
tz1 private keys:
ed25516_unencrypted: edsk2rKA8YEExg9Zo2qNPiQnnYheF1DhqjLVmfKdxiFfu5GyGRZRnb
ed25519_encrypted: edesk1GXwWmGjXiLHBKxGBxwmNvG21vKBh6FBxc4CyJ8adQQE2avP5vBB57ZUZ93Anm7i4k8RmsHaPzVAvpnHkFF

tz2 private keys:
p256_encrypted: p2esk28hoUE2J88QNFj2aDX2pjzL7wcVh2g8tkEwtWWguby9M3FHUgSbzvF2Sd7wQ4Kd8crFwvto6gF3otcBuo4T
p256_unencrypted: p2sk3HdQc93EjixRAWs9WZ6b3spNgPD7VriXU8FH8EiHN8sxCh7gmv

tz3 private keys:
secp256k1_encrypted: spesk24UQkAiJk8X6AufNtRv1WWPp2BAssEgmijCTQPMgUXweSKPmLdbyAjPmCG1pR2dC9P5UZZVeZcb7zVodUHZ
secp256k1_unencrypted: spsk2Fiz7sGP5fNMJrokp6ynTa4bcFbsRhw58FHXbNf5ProDNFJ5Xq
```

To create your own address, you can do something like:
```
          import { b58cencode, prefix, Prefix } from '@taquito/utils';
          const keyBytes = Buffer.alloc(32);
          crypto.randomFillSync(keyBytes)

          const key = b58cencode(new Uint8Array(keyBytes), prefix[Prefix.P2SK]);
          const pkh = await new InMemorySigner(key).publicKeyHash();
```

**Comment by jevonearth** [comment]
@roxaneletourneau to update documentation clarifying secret key format.

See https://github.com/ecadlabs/taquito/blob/master/packages/taquito-signer/test/taquito-signer.spec.ts 
and https://github.com/ecadlabs/taquito/blob/master/packages/taquito-signer/test/import-key.spec.ts

For supporting unit tests.

**Comment by Sword-Smith** [comment]
I see that you recommended me to go with `P2SK` which is an address derived from the P256 (NIST) scheme. I was thinking about going with secp256k1` instead. Thoughts?

**Comment by jevonearth** [comment]
You should be able to use the scheme/prefix of your choice. The given example just happened to be `P256`. I would probably choose `secp256k1` also.

Closing this now. Thank you @Sword-Smith
