### ISSUE TITLE
Unclear how to get Michelson in JSON format

### ISSUE THREAD

**Issue by Sword-Smith** [ecadlabs/taquito#393]
An [example](https://tezostaquito.io/docs/originate/#a-initializing-storage-using-a-javascript-object) presenting how Michelson code is deployed using taquito refers to the Michelson in JSON format. But your link above points to the Michelson code which is not in JSON and which is stored in a `.tz` file. How do I get the Michelson code in JSON format from the `.tz` file?

**Comment by Sword-Smith** [comment]
OK. From another [blog](https://medium.com/protofire-blog/tezos-part-4-how-to-integrate-javascript-with-smart-contracts-and-run-unit-tests-c36756149e9d)  I found that the LIGO compiler takes a flag `--michelson-format json` which gives the required output. Perhaps you should change your documentation to point to Michelson source code in JSON format instead of tz format?

I am nitpicking but I am going through the process of learning the ins and outs of Tezos, LIGO, and taquito, and I think others will run into the same problem.

**Comment by jevonearth** [comment]
Hi @Sword-Smith , your reports are always welcome and greatly appreciated.

The [6.3.2](https://github.com/ecadlabs/taquito/releases/tag/6.3.2-beta.0
) release of Taquito ships with a new Michelson <--> JSON encoder/decoder, so you should be able to pass plain Michelson or the JSON representation of Michelson using the `code` parameter of the `originate` method.

You can of course use the ligo option `--michelson-format json` if you prefer to use the Michelson JSON representation. Either should work now. If it does not work, please reopen this ticket with more details. :)
