### ISSUE TITLE
`storage` should be `init`

### ISSUE THREAD

**Issue by Sword-Smith** [ecadlabs/taquito#394]
From:
https://tezostaquito.io/docs/originate/#a-initializing-storage-using-a-javascript-object

```
// generic.json is referring to Michelson source code in JSON representation
const genericMultisigJSON = require('./generic.json')
const originationOp = await Tezos.contract.originate({
  code: genericMultisigJSON,
  storage: {
    stored_counter: 0,
    threshold: 1,
    keys: ['edpkuLxx9PQD8fZ45eUzrK3BhfDZJHhBuK4Zi49DcEGANwd2rpX82t']
  }
})
const contract = await originationOp.contract()
console.log(contract.address)
```

I couldn't get it to work with `storage`. But when I changed it to `init`, it worked.

- [x] Review and revise API docs and Website docs to ensure that the purpose of `init` and  `storage` for the `originate` method is clearly defined.

**Comment by jevonearth** [comment]
Hi @Sword-Smith,

Thank you for reporting, very much appreciated.

You should be able to pass javascript objects using the `storage` property. When using `init` Taquito expects a Michelson expression either in JSON or Plain Michelson representation.

Please make sure you are using the latest version of Taquito, as we recently added a vastly improved Michelson <--> JSON encoder/decoder.

We will revise the docs to make this clearer.

**Comment by jevonearth** [comment]
I checked the website, looks good. Live code examples work.
