### ISSUE TITLE
Get all keys in a BigMap

### ISSUE THREAD

**Issue by sean-magin** [ecadlabs/taquito#398]
Is there a way to get all the keys available in a BigMap with Taquito? 

As @claudebarde pointed out I see that this info is being displayed in Better Call Dev (https://better-call.dev/mainnet/big_map/36/keys), so it's possible, but just wondering if that feature is available natively with Taquito yet?

**Comment by claudebarde** [comment]
I found [this article](https://medium.com/tezoscommons/new-taquito-release-now-with-bigmaps-7d7352351af4) written by @jevonearth saying that the feature will be available in the future.
I don't know if Taquito can provide such a feature, in the meantime I found TzStats API that can do it, for example [https://api.tzstats.com/explorer/bigmap/36/values](https://api.tzstats.com/explorer/bigmap/36/values) returns all the keys in the big map with their values.
A lazy solution would be to use the API but it will require patching if it breaks in the future, the implementation of such a solution without an API is beyond my knowledge :P

**Comment by Innkst** [comment]
duplicate #222
