### ISSUE TITLE
Fix dependencies for @taquito/michelson-encoder

### ISSUE THREAD

**Issue by Necroskillz** [ecadlabs/taquito#409]
It should declare `@taquito/rpc` as a dependency, not just devDependency.

See https://yarnpkg.com/configuration/yarnrc#packageExtensions as to why it's convenient. Currently with yarn 2 you need to add this manually:

```
packageExtensions:
  "@taquito/michelson-encoder@*":
    dependencies:
      "@taquito/rpc": "^6.3.5-beta.0"
```

(There may be other packages which should also be updated)

**Comment by jevonearth** [comment]
It appears we do have a dependency between `@taquito/michelson-encoder` and `@taquito/rpc` because of the `MichelsonV1Expression` type that is imported. Ideally, I'd like to move this type so we can remove this dependency. Will investigate.
