### ISSUE TITLE
how to pass a contract argument to method

### ISSUE THREAD

**Issue by chiptus** [ecadlabs/taquito#415]
Thanks for writing an amazing and helpful library.

I'm trying to implement a dapp that interacts with a FA1.2 contract. For the getters, the contract expects a callback (a contract that received a nat parameter). How do I provide it? basically I want to do `contract.methods.getTotalSupply(outputContract)`.

I've been looking into https://tezostaquito.io/typedoc/classes/_taquito_taquito.contractmethod-2.html and I tried `contract.methods.getTotalSupply(Tezos.contract.at(CONTRACT_ADDRESS))`

**Comment by claudebarde** [comment]
I checked that and it is not possible to convert a JavaScript value into a Michelson value of type `contract 'p` with Taquito. The contract type is special in Michelson (values of type contract are not pushable and cannot be used as storage unlike most of the other types) and smart contracts generally handle them internally. Contracts that expect values of type contract most often expect them from another contract that can format it properly. If you want to test a contract entrypoint that receives a value of type contract, you should build a test contract that can send this kind of value.

**Comment by chiptus** [comment]
ok, thanks for this answer and for the time you took to investigate. I saw
an example of how you did it on the tzip-7 contract.

**Comment by claudebarde** [comment]
Creating a new contract just for testing is a bit tedious but it is the best solution at the moment. It looks like Taquito may offer a better and easier solution in the future so it won't be the case forever :)

**Comment by jevonearth** [comment]
Hi @chiptus 

Our new lambdaView feature might be helpful here. It's still in pre-release, so you will have to use a specific `next` version. You can find the latest pre-release version here: https://github.com/ecadlabs/taquito/releases 

Documentation is available here: https://tezostaquito.io/docs/lambda_view#usage

Closing this issue, but do re-open if it does not satisfy your use case.

**Comment by chiptus** [comment]
Amazing, thanks
