### ISSUE TITLE
Display values other than strings after FAILWITH

### ISSUE THREAD

**Issue by claudebarde** [ecadlabs/taquito#416]
Taquito doesn't seem to display any value returned after a `FAILWITH` other than strings in the `error.message`.
A transaction sent to a contract on Carthagenet that fails with a pair of strings shows `(temporary) proto.006-PsCARTHA.michelson_v1.script_rejected` in the Taquito error message while it shows the following JSON value in the error displayed by the Beacon extension:
```
{
    "kind": "temporary",
    "id": "proto.006-PsCARTHA.michelson_v1.script_rejected",
    "location": 14,
    "with": {
      "prim": "Pair",
      "args": [
        {
          "string": "hello"
        },
        {
          "string": "world"
        }
      ]
    }
  }
```
It would be very valuable to get the arguments returned by a contract that failed.

**Comment by jevonearth** [comment]
@claudebarde can you put together an example of this, with a testnet contract that throws a FAILWITH, please?

**Comment by jevonearth** [comment]
Related #257

**Comment by claudebarde** [comment]
@jevonearth This feature has been implemented by the beacon-sdk and the major wallets and tested by myself. I think we can close the issue now :)
