### ISSUE TITLE
Issue running in a React Native project

### ISSUE THREAD

**Issue by JoleMile** [ecadlabs/taquito#427]
After installing this library in a fresh `react native` project I'm getting the following error: 
`ReferenceError: Can't find variable: document`

Note that I had to `rn-nodeify` the project in order to get it to at least build.
Also note that everything is working in as expected in a normal `node.js` project.

Has anyone made it work in a react native app before?
Any help would be appreciated.

**Comment by jevonearth** [comment]
Hi Jole,

Would it be possible for you to push/publish a tiny react native app that shows this error on GitHub so that we can reproduce the error? We plan to create a template react native app at, but in the meantime, a demo of the issue would be helpful.

**Comment by claudebarde** [comment]
I'm on it! NodeJS doesn't have access to the DOM elements either so I suspect the error comes from there but I wonder which part of Taquito needs a property/method from the `document` object.
@JoleMile, do you have a repo with your app?

**Comment by JoleMile** [comment]
Hi guys,

I since have resolved the issue.
The problem was coming from a specific version of `libsodium`. You can see an open issue about it here https://github.com/jedisct1/libsodium.js/issues/249
`libsodium` is being used by `taquito-signer` https://github.com/ecadlabs/taquito/blob/master/packages/taquito-signer/package.json#L73

I resolved it by using version `6.3.5-beta.0` and adding this to my package.json
```
"resolutions": {
    "libsodium": "0.7.6",
}
```

However, I also tried building the master myself and using that in my project, but that did not work because the current `master` depends on the latest version of `libsodium`.

Hope that helps :)

**Comment by claudebarde** [comment]
Hey @JoleMile, I am working on Taquito with React Native and it doesn't compile at all. As you suggested, I used `rn-nodeify` but I still get errors about the `taquito.ios.js` file not existing. Would you like to share the steps you followed with `rn-nodeify`, that would be very useful, thank you!

**Comment by henrily-ledger** [comment]
Hello, is there any update on this one ? I have an issue when I tried to sign on iOS, we have the same error as 
@JoleMile 

`ReferenceError: Can't find variable: document` 

I also tried @JoleMile fix to change the resolution : 
```
"resolutions": {
    "libsodium": "0.7.6",
}
```
But I get the error with version 11.1.0

**Comment by michaelkernaghan** [comment]
Looks like the user in this one is happy now
