### ISSUE TITLE
SPIKE: Design better API for dryrun, estimates, signing and preparation

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taquito#432]
The `transfer()` method abstracts many underlying steps for the developer user, which is a good thing for typical usescases. When a developer user wishes to retrieve data from some particular underlying step, they use the lower-level abstractions in taquito.

If a user wishes to get the estimate for a transaction operation on a contract method, they need to prepare the call, fetch the parameters, and then call the `Tezos.estimate.transfer({op...})` API.

A proposal for a new set of methods follow;

(_Controversial, maybe a better way around this?_) Break the api so that `contract.transfer()` becomes a no-op method.

Idea is to add the following new methods;

```
contract.transfer({ to: address, amount: amount }).send()
contract.transfer({ to: address, amount: amount }).estimate()
contract.transfer({ to: address, amount: amount }).dryrun()
contract.transfer({ to: address, amount: amount }).sign()
contract.transfer({ to: address, amount: amount }).prepare()
```

And for smart contract invocations, it may look like this:

```
contract.methods.increment(1).send()
contract.methods.increment(1).estimate()
contract.methods.increment(1).dryrun()
contract.methods.increment(1).sign()
contract.methods.increment(1).prepare() 
```

`send` will complete all steps and inject the method
`estimate` will return an Estimate for the operation
`dryrun` will return the dryrun results, including the updated storage as evaluated by the RPC server
`sign` will return the signed operation but not inject the operation
`prepare` will prepare an operation that is ready for singing.

**Acceptance criteria:**
1. Prepare and agree on design
2. Create follow-up issues to prototype(if needed) and implement

**Comment by roxaneletourneau** [comment]
In addition to the above; Provide the ability to obtain operation hash before sending it to the node

**Comment by Innkst** [comment]
related to previous implementation #995

**Comment by Innkst** [comment]
We need to review the design and have a discussion again. Also, please re-confirm the follow-up tasks and let's what non-breaking changes could be implemented earlier and which ones have to wait till v15

**Comment by roxaneletourneau** [comment]
Created follow-up task issues 2019 and 2020
