### ISSUE TITLE
Provide the ability to obtain operation hash before sending it to the node

### ISSUE THREAD

**Issue by emishur** [ecadlabs/taquito#435]
Currently, operation signing and injecting is done as a single operation.

If we want to save pending operation hash in the database we cannot guarantee transactionality.
In the following code snipped if `db.save...` fails we have no way to recover a hash or rollback Tezos operation

```typescript
const operation = await contract.methods.foo(param).send();
await db.savePendingOperation(operation.hash);
```

If we can obtain operation hash before submitting it to tezos, we can recover if either DB or Tezos interaction fails:

```typescript
const operation = await.contract.method.foo(param).sign();
await db.savePendingOperation(operation.hash);
await operation.send();
```

**Comment by jevonearth** [comment]
Linking this to #432  as I think we can satisfy this use-case within the scope of that issue. Thank you @emishur

**Comment by roxaneletourneau** [comment]
As preliminary work, a util function allowing to obtain the operation has been added to the Taquito/utils package.
With this function, it is possible to obtain the operation hash before sending the operation to the node, but this required several steps that are normally abstracted by Taquito. An example has been added: integration-tests/call-contract-method-manual-steps.spec.ts.

A better API will be provided for this use-case with #432.
