### ISSUE TITLE
Ledger signer not working properly

### ISSUE THREAD

**Issue by gretzke** [ecadlabs/taquito#437]
I followed the instructions in the documentation. 

```
const transport = await TransportU2F.create();
signer = new LedgerSigner(transport);
address = await signer.publicKeyHash();
```

In Firefox I get the following error when trying to connect to the device:
name: "TransportError"
message: "Failed to sign with Ledger device: U2F BAD_REQUEST"

**Comment by claudebarde** [comment]
Hey! Are you using it on localhost? The `TransportU2F` library has to be used with `https`, according to the framework you are using, this can be implemented differently for development. If you would give me more information about your setup, I would be very happy to help you with that!

**Comment by gretzke** [comment]
Yes, i was indeed using localhost. After testing with https everything works now, thanks!

**Comment by jevonearth** [comment]
Great, glad you got this working! Closing this ticket.
