### ISSUE TITLE
[website] Add search

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taquito#442]
Using the opensource plan, integrate https://www.algolia.com/ into the tezostaquito website.

**Comment by jevonearth** [comment]
We plan to migrate the site to Netlify, and there's a plugin of some sort that might make algolia setup easier. See: https://github.com/algolia/algoliasearch-netlify/

**Comment by Innkst** [comment]
see also #1107

**Comment by dsawali** [comment]
After working on this for a bit, I've been able to index our site and have a running search bar using Algolia.

This opens up more work for maintaining the index and making sure it updates automatically when there are website changes. I've created an issue to add a process in our CI to index the site after its built in the pipeline to ensure our search functionality is up to date with each code merge: #1282
