### ISSUE TITLE
 Create integration tests that fetch the constant values for each protocol

### ISSUE THREAD

**Issue by roxaneletourneau** [ecadlabs/taquito#449]
We want to create integration tests that will fetch the constants for the different protocols. 

When protocols upgrade, some properties are removed or added from the [constants](https://tezos.gitlab.io/api/rpc.html#get-block-id-context-constants). Having tests showing all properties and values expected for each protocol will be a good way to keep track of the changes.

To do so, the RPC node can be queried for constants by specifying the level associated with a protocol. See https://github.com/ecadlabs/taquito/blob/master/packages/taquito-rpc/src/taquito-rpc.ts#L331

Here are the protocol hashes and level (Mainnet):  
(I used https://tzstats.com/protocols to update this - mk)

Protocol Hash | Proto Number | Level
-- | -- | --
PrihK96nBAFSxVL1GLJTVhu9YnzkMFiBeuJRPA8NwuZVZCE1L6i (No constants here!) | 0 | 0
[Ps9mPmXaRzmzk35gbAYNCAw6UXdE2qoABTHbN2oEEc1qM7CwT9P](https://api.tez.ie/rpc/mainnet/chains/main/blocks/1/context/constants) |1 | 1
[PtCJ7pwoxe8JasnHY8YonnLYjcVHmhiARPJvqcC6VfHT5s8k8sY](https://api.tez.ie/rpc/mainnet/chains/main/blocks/2/context/constants) | 1 | 2
[PsYLVpVvgbLhAhoqAkMFUo6gudkJ9weNXhUYCiLDzcUpFpkk8Wt](https://api.tez.ie/rpc/mainnet/chains/main/blocks/100000/context/constants) | 2 | 100000
[PsddFKi32cMJ2qPjf43Qv5GDWLDPZb3T3bF6fLKiF5HtvHNU7aP](https://api.tez.ie/rpc/mainnet/chains/main/blocks/300000/context/constants) | 3 | 300000
[Pt24m4xiPbLDhVgVfABUjirbmda3yohdN82Sp9FeuAXJ4eV9otd](https://api.tez.ie/rpc/mainnet/chains/main/blocks/600000/context/constants) | 4 | 600000
[PsBabyM1eUXZseaJdmXFApDSBqj8YBfwELoxZHHW77EMcAbbwAS](https://api.tez.ie/rpc/mainnet/chains/main/blocks/700000/context/constants) | 5 | 700000
[PsCARTHAGazKbHtnKfLzQg3kms52kSRpgnDY982a9oYsSXRLQEb](https://api.tez.ie/rpc/mainnet/chains/main/blocks/900000/context/constants) | 6 | 900000
[PsDELPH1Kxsxt8f9eWbxQeRxkjfbxoqM52jvs5Y5fBxWWh4ifpo](https://api.tez.ie/rpc/mainnet/chains/main/blocks/1220000/context/constants) | 7 | 1220000
[PtEdo2ZkT9oKpimTah6x2embF25oss54njMuPzkJTEi5RqfdZFA](https://api.tez.ie/rpc/mainnet/chains/main/blocks/1350000/context/constants) | 8 | 1350000
[PsFLorenaUUuikDWvMDr6fGBRG8kt3e3D3fHoXK1j1BFRxeSH4i](https://api.tez.ie/rpc/mainnet/chains/main/blocks/???/context/constants) | 9 | ???

**Comment by roxaneletourneau** [comment]
Need to validate with @sukhi-singh 
I remember you showing me some work on it, but I don't this it has been merged.

**Comment by michaelkernaghan** [comment]
I will do this issue now
