### ISSUE TITLE
Taquito first class support for deno

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taquito#455]
[Deno](https://deno.land/) is a new runtime for JavaScript and TypeScript.

We want:

- To be able to build Taquito in a deno environment
- To run Taquito's integration tests to a deno environment
- For Taquito packages to be published to the deno package registry: https://deno.land/x
- For Taquito users to have an easy and unsurprising experience when building a service on deno using Taquito

See: https://deno.land/

**Comment by michaelkernaghan** [comment]
general agreement in the team that at this point Deno is not going to be implemented in Taquito.
