### ISSUE TITLE
Example and explanations for using "source" option in contact call

### ISSUE THREAD

**Issue by shekhar-shubhendu** [ecadlabs/taquito#456]
I was trying to add unit tests to check the access control in my contract (using truffle).

In ethereum, if I want to change the `address` from which I want to trigger the contract call I would provide a `from` address and when looking at the taquito documentation I thought it would be the same and I can just pass the [`source` address](https://github.com/ecadlabs/taquito/blob/5a41aeff97726fac66b8723689fe8b983eb9ecae/packages/taquito/src/contract/contract.ts#L12) and the contract call will be made from that address but it seems this is not the case.

It would be nice to have examples and some documentation on how to use the `source` option when making contract calls.

Before making this issue, I tried to find those but was unable to but let these already exist.

**Comment by claudebarde** [comment]
I am not sure I understand correctly what you are trying to achieve.

It is impossible to manipulate which address ends up as the `source` in a Michelson contract. I believe the mechanism is similar in Ethereum: the address that ends up as the one in `tx.origin` in Solidity is ultimately the one that signed the first transaction of the current chain. I would assume the address provided in the `from` property of the `methods.myMethod.send` method in `web3js` is used to match it with the current selected address in MetaMask. The ability to manipulate the address that becomes the `source` in Solidity or Michelson would create a serious security issue (as it wouldn't be possible to be sure of who originates transactions).

Please correct me if you meant something else :)

**Comment by shekhar-shubhendu** [comment]
So if you look at the example [here](https://github.com/trufflesuite/truffle/tree/master/packages/contract#full-example) in @truffle/contract then you can see the user can change the address from which the call originates by just changing the address in the `from` field e.g. `coin.sendCoin(account_two, 3, {from: account_one})`.

Having this kind of functionality helps in testing the access control logic.
I was hoping that we can do this in taquito too like `coin.sendCoin(account_two, 3, {source: account_one})`.

**Comment by claudebarde** [comment]
I think that's an internal mechanism for Truffle to switch between signing accounts during development and make the testing process easier. In a real-world dapp, you cannot specify an address A as the `source` and signs the transaction with an address B (the address B will become the de facto source).
As far as I know about Truffle for Tezos, this feature doesn't exist (it is still in an early stage).

**Comment by shekhar-shubhendu** [comment]
Yeah that I understand. I was talking about testing. No one should allow that in real world. But thanks for the response. :)

It would be nice to have an example for the `source` though and what it actually does in the contract context. Currently, it seems quite confusing at least for people coming from the truffle/ethereum world.

**Comment by claudebarde** [comment]
I think your question is more related to Truffle than Taquito. I will open the subject with the Truffle team but you can also open an issue in the Truffle for Tezos repo.

**Comment by shekhar-shubhendu** [comment]
Actually, i opened it before asking about the `source` option here.
Here is the truffle issue https://github.com/trufflesuite/truffle/issues/3442

**Comment by jevonearth** [comment]
@claudebarde Did you open an issue on the truffle issue tracker? If so, can you link it here, and close this issue.
