### ISSUE TITLE
Support beacon-sdk v2

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taquito#466]
PR is here: airgap-it/beacon-sdk#20

Pre-release builds are available on NPM, the latest at the time of writing is `2.0.0-beta.11`. See https://www.npmjs.com/package/@airgap/beacon-sdk and click on the `Versions` tab.

v2 is expected to include a reset or disconnect method. (not yet in beta.11). We need to consider how to surface this method in the Wallet API.

- [x] Upgrade dependencies in Taquito (updated to 2.0.0-beta.12)
- [x] Update ~~Wallet API~~ BeaconWallet to use Disconnect method
~~- if a wallet doesn't support Beacon's new method, return an error, i.e. 'Not implemented'~~
- [x] Update Taquito examples to use v2 (i.e. TacoWallet)
- see if we can add Disconnect scenario for dApp as well as wallet
- see if we can Switch accounts for examples where we have several wallets (2+) 
- Test with Thanos, Beacon extension and Kukai

**Comment by roxaneletourneau** [comment]
Updated to version 2.0.0-beta.12
The `requestOperation` method of beacon-sdk no longer takes the network as a parameter: fixed it in the` sendOperations` method of the Beaconwallet class.
