### ISSUE TITLE
Add new website page with links to Taquito tutorials and courses

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taquito#467]
Create a page for the website that links to popular blog posts and courses that cover Taquito in some way.

Claudes series of blog posts is a good start. The SmaryPy course is also worthwhile as it has a chapter on Taquito.

**Comment by claudebarde** [comment]
First idea of links to add to the page:
- [Build your first dapp on Tezos](https://medium.com/better-programming/build-your-first-dapp-on-tezos-270c568d4fe9)
- [Build a Tezos dapp with Taquito and the Beacon SDK](https://medium.com/coinmonks/build-a-tezos-dapp-using-taquito-and-the-beacon-sdk-692d7dc822aa)
- [Taquito Workshop](https://www.youtube.com/watch?v=qYk_17YbPa4&feature=emb_logo&ab_channel=CoinList)
- [Working with FA1.2 using LIGO and Taquito](https://assets.tqtezos.com/docs/token-contracts/fa12/2-fa12-ligo/)
- [Protofire tutorial](https://medium.com/protofire-blog/tezos-part-4-how-to-integrate-javascript-with-smart-contracts-and-run-unit-tests-c36756149e9d)
- [Nomadic Labs Training](https://training.nomadic-labs.com/download/taquito.pdf)
- [A delicious TypeScript library for the Tezos blockchain](https://medium.com/tezoscommons/a-delicious-new-typescript-library-for-the-tezos-blockchain-a8fcf776b037)
- [Basic dapp concepts using Taquito](https://hackmd.io/@kinokasai/Sy1v-vtmL)

**Comment by claudebarde** [comment]
Done!
https://tezostaquito.io/docs/tutorial_links
