### ISSUE TITLE
Experiment with TZIP-16 contract using itself as storage

### ISSUE THREAD

**Issue by Innkst** [ecadlabs/taquito#469]
***Note**: Use existing Taquito as a library only, avoiding to make changes to Taquito itself. The rationale is that we think TZIP-16 can be achieved without changing Taquito. Let's do the spike without modifying Taquito, and at the end of the spike, we can make an informed choice about what features can be moved into Taquito to provide a better Developer Experience.*

**Acceptance criteria**

- Create an example smart contract according to TZIP-16 spec storing metadata  using `tezos-storage:here`
- Originate TZIP-16 smart contract using existing Taquito with `tezos-storage:here`:
    - Add Metadata BigMap data per TZIP-16
- Fetch the newly originated smart contract
- Fetch the value stored in key "" (empty!) from the Big Map named `%metadata`
- Fetch and decode the data stored in the `here` big map key as pointed to.
- Document discoveries

[https://gitlab.com/tzip/tzip/-/merge_requests/94](https://gitlab.com/tzip/tzip/-/merge_requests/94) 
 WIP, but should contain some TZIP-16 examples and clarifications.

**Comment by sukhi-singh** [comment]
https://gist.github.com/sukhi-singh/b51340c0f0bfa865e7d840ee67913972

**Comment by roxaneletourneau** [comment]
I created a branch called 'example-tzip16' where I added an example to originate a contract having metadata in its own storage and to fetch these metadata. It is in the example folder and can be run with this command:
`node -r ts-node/register --preserve-symlinks tzip16.ts`

**Comment by roxaneletourneau** [comment]
Some thoughts from this exercise:
- We will need to provide util functions to make bytes conversion as values of the metadata bigmap are in bytes.
- Users will need to modified their contracts to include metadata in the storage.
- We will need to validate that the contract is compliant with tzip16: there is a bigmap called "metadata" in the storage that contains an empty key.
- We will need to check if the metadata are stored on-chain, http/https or ipfs: split URI at the first " : " the first part should be `http`/`https`, `ipfs`, `tezos-storage` or `sha256`
- Some manipulations around " / " character to know if metadata are in the same contract or another (and if so what is the contract address and network)
