### ISSUE TITLE
Experiment with TZIP-16 contract using http URI as storage

### ISSUE THREAD

**Issue by Innkst** [ecadlabs/taquito#470]
_Note: Use existing Taquito as a library only, avoiding to make changes to Taquito itself. The rationale is that we think TZIP-16 can be achieved without changing Taquito. Let's do the spike without modifying Taquito, and at the end of the spike, we can make an informed choice about what features can be moved into Taquito to provide a better Developer Experience._

**Acceptance criteria**
- Originate TZIP-16 smart contract using existing Taquito with an http URI for metadata
    - Can publish on Google storage bucket with public permissions. Here's a prepared example: [https://storage.googleapis.com/tzip-16/tzcomet_example.json](https://storage.googleapis.com/tzip-16/tzcomet_example.json)  Ask Jev if you want to add more examples!
- Create an example smart contract according to TZIP-16 spec with http URI for metadata
- Fetch the newly originated smart contract
- Fetch and decode the value stored in key "" (empty!) from the Big Map named `%metadata`
- Fetch the JSON data using an http client library
- Document discoveries

https://gitlab.com/tzip/tzip/-/merge_requests/94
WIP, but should contain some TZIP-16 examples and clarifications.

**Comment by Innkst** [comment]
@jevonearth mentioned https://github.com/sideway/joi as one of the options

**Comment by sukhi-singh** [comment]
Following were the observations during the experiment:
- No additional blockchain support is needed in Taquito to achieve this. However, better abstractions must be provided for tzip16 support.
- Additional utilities are needed for ASCII to hex encode-decode.
- Taquito can have in-built types for storage and metadata. Currently, the type of storage is `any`.
- Additional libraries would be needed to fetch a resource over HTTPS.

**Comment by sukhi-singh** [comment]
Current code to access metadata `Tezos.contract.at("").storage()["metadata"]`.

Closing the issue, since the procedure and observations have been recorded.
