### ISSUE TITLE
Set up self hosted github actions runner

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taquito#472]
Our integration tests fail regularly, and it could be related to timeouts or slow runners that we get for free. We have our own compute resources, so let's run our own GitHub Actions runners.

See: https://docs.github.com/en/free-pro-team@latest/actions/hosting-your-own-runners

**Comment by GImbrailo** [comment]
Private GitHub runners were created and we are now using these runners for our Actions 
![image](https://user-images.githubusercontent.com/29157965/108287375-8f8a0e80-713f-11eb-8aaa-19d786b4dd8d.png)
