### ISSUE TITLE
TZIP-16: Explore if we can leverage lambda function design for off-chain views

### ISSUE THREAD

**Issue by Innkst** [ecadlabs/taquito#477]
- Understand how to replicate off-chain views and inspect the results:
   - How to execute the views through the RPC with helpers/scripts/run_code
   - Use `"michelson-storage-view"` implementation, unless `"rest-api-query"`  is easier
   - any other way?
- Do we need a new API to return off-chain views for TZIP-16 implementation or can we re-use lambdaviews implementations in a generic way to server both use cases.
   - refer to a lambdaview implementation https://github.com/ecadlabs/taquito/pull/471
   - do these off-chain views fit in with lambdaviews semantically?
   - is there a way to separate the concerns?

**Comment by roxaneletourneau** [comment]
"michelson-storage-view"
- We can not reuse the "LambdaView" class to execute these off-chain views. When we call a real view method of a smart contract, a "voidLAmbda" is created and the ["viewMethod" is included in the code] of this "voidLambda".(https://github.com/ecadlabs/taquito/blob/master/packages/taquito/src/contract/lambda-view.ts#L110). This is not working for off-chain views as they are not part of the code of the smart contract.
- We can execute the views through the RPC with "helpers/scripts/run_code". The next step would be to find how to build the "script" based on the view metadata and the storage of the contract for any view and contract. 

For this example: https://tqtezos.github.io/TZComet/#/explorer%3Fexplorer-input%3DKT1R5cYuidmPgDU79WJ5yFV9uNyxvQaZooyL
the view field in the metadata is:
```
[{"michelson-storage-view":{
    "parameter":{"prim":"nat","args":[],"annots":[]},
    "return-type":{"prim":"nat","args":[],"annots":[]},
    "code":[{"prim":"DUP","args":[],"annots":[]},{"prim":"CDR","args":[],"annots":[]},	{"prim":"CAR","args":[],"annots":[]},{"prim":"SWAP","args":[],"annots":[]},
	{"prim":"CAR","args":[],"annots":[]},{"prim":"MUL","args":[],"annots":[]}]
}}]
```
and the script to run the view through helpers/scripts/run_code is:
```
{"script":[
    {"prim":"parameter","args":[{"prim":"pair","args":[{"prim":"nat"},{"prim":"pair","args":	[{"prim":"nat"},{"prim":"big_map","args": 
         [{"prim":"string"}, {"prim":"bytes"}],"annots":["%metadata"]}]}]}]},
    {"prim":"storage","args":[{"prim":"option","args":[{"prim":"nat"}]}]},
    {"prim":"code","args":[[_{"prim":"CAR"}_,[{"prim":"DUP"},{"prim":"CDR"},{"prim":"CAR"}, {"prim":"SWAP"},{"prim":"CAR"}, 
         {"prim":"MUL"}],_{"prim":"SOME"}, {"prim":"NIL","args":[{"prim":"operation"}]},{"prim":"PAIR"}]]_}],
"storage":{"prim":"None"},
"input":{"prim":"Pair","args":[{"int":"5"},{"prim":"Pair","args":[{"int":"7"},{"int":"25972"}]}]},
"amount":"0",
"chain_id":"NetXjD3HPJJjmcd"}
```
