### ISSUE TITLE
Docs for batch api

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taquito#484]
Document what the batch API is
When it is useful
It's limitations

Examples

Include common counter errors (for search engine indexing) that users often run into before discovering the batch API.

**Comment by claudebarde** [comment]
Here is the [first draft of the Batch API documentation](https://hackmd.io/kVi-tau-Qfm9QfTCDZ0O3w).
The only limitation that comes to my mind is the 10 operation limit I observed during my tests, although this isn't mentioned anywhere, it would be great to have someone take a look at it.

**Comment by claudebarde** [comment]
Pull request submitted #490

**Comment by claudebarde** [comment]
Batch API documentation was added with this pull request: https://github.com/ecadlabs/taquito/pull/490
