### ISSUE TITLE
Remove support and operations between Babylon and Kathmandu

### ISSUE THREAD

**Issue by Innkst** [ecadlabs/taquito#485]
Goal: to be in sync with current protocol.
If something is marked deprecated, it should still work, but fully deprecated need to be removed.

This issue says Babylon, but we should look for Cartage, Delphi, and so on until now.
Mostly focus on protocols between Babylon and Kathmandu.

Review those tasks below from that perspective:
- [ ] Remove op forging code for Babylon and other operations that are no longer relevant in Lima/Mumbai
- [ ] All tests should successfully pass
- [ ] check for any Babylon support in demo apps and Taquito template projects, any code examples
- [ ] check any mentions in documentation and website too

**Comment by michaelkernaghan** [comment]
this has been merged in PR
