### ISSUE TITLE
Isn't this an unnecessarily complicated buffer to hex string conversion?

### ISSUE THREAD

**Issue by HugoKooijman** [ecadlabs/taquito#487]
This function:
https://github.com/ecadlabs/taquito/blob/155071aca0da07cade3dc1972765569df242380e/packages/taquito-utils/src/taquito-utils.ts#L215

Wouldn't buf.toString('hex') suffice?

**Comment by e-asphyx** [comment]
Yes, it would

**Comment by michaelkernaghan** [comment]
user is free to make that choice, but we are not changing the function,
