### ISSUE TITLE
Taquito documentation Problems

### ISSUE THREAD

**Issue by adamshinder** [ecadlabs/taquito#488]
In the [Quick Start documentation](https://tezostaquito.io/docs/quick_start/#importing-a-faucet-key) Page on Importing a Faucet Key Section:

```
import { InMemorySigner, importKey } from '@taquito/taquito-signer';
```

SHOULD BE:
```
import { InMemorySigner, importKey } from '@taquito/signer';
```

On Line 4:
```
Tezos.setProvider({ signer: new InMemorySigner() });
```
This doesn’t need to be there. it’s made to catch a bad signer but if you put in a good signer, it throws an error.

```
importKey(
 Tezos,
 FAUCET_KEY.email,
 FAUCET_KEY.password,
 FAUCET_KEY.mnemonic.join(' '),
 FAUCET_KEY.secret
);
```
Import key returns a promise, this should be stated in some way, for example:

```
importKey(
 Tezos,
 FAUCET_KEY.email,
 FAUCET_KEY.password,
 FAUCET_KEY.mnemonic.join(' '),
 FAUCET_KEY.secret
).catch(e => console.error(e));
```

**Comment by jevonearth** [comment]
Addressed in #490 
Thank you to @adamshinder for reporting these issues.
