### ISSUE TITLE
Update all website examples to show contract and wallet API example variants.

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taquito#493]
@roxaneletourneau implemented this pattern on the https://tezostaquito.io/docs/originate doc page.

All code examples should be updated to show usage with wallet API and contract API

Related to: #486

**Comment by michaelkernaghan** [comment]
skipping the examples on the lambda views contracts

skipping the last example on the http://localhost:3001/docs/next/smartcontracts page
