### ISSUE TITLE
transfer-all into a new implicit account 

### ISSUE THREAD

**Issue by oleiba** [ecadlabs/taquito#496]
Existing integration tests for draining an account (i.e. emptying an account) consider the case of transferring into an *existing* implicit account.
In contrast, there's the case of transferring all of the account's funds into a *new* implicit account, in which case the sender is required to pay a storage fee.

Pre-Delphinet, I was able to empty an account completely in such case. The storage fee was 0.257 XTZ.
Post-Delphinet, I am not able to empty an account completely into a new implicit account. The estimated storage fee is again 0.257 XTZ, but in practice, as I see [in this transaction ](https://delphi.tzkt.io/tz2MJfj3sDRz7uf1oV11hjYN9ycXEk2C3LoX/operations/) the storage fee is 0 but there's an allocation fee of 0.06425 XTZ. 

When I set the amount to be the sender's balance minus (estimated fee + 0.06425) I get the transaction eventually reverted.
When I set the amount to be the sender's balance minus (estimated fee + 0.064251) I get the transaction confirmed successfully, but it keeps a 0.000001 XTZ balance on the sender's. 

Can you consider adding a test-case for transferring-all into a new implicit account?

**Comment by oleiba** [comment]
Hi! Any plan/suggestion on this?

**Comment by roxaneletourneau** [comment]
Hi @oleiba 
Thank you for reporting this. I run into the same issue for Delphinet. I will continue investigating that and keep you posted with my findings.

**Comment by roxaneletourneau** [comment]
Hi @oleiba,
It seems that the cost of emptying an account has increased in Delphinet. 
The transaction to empty the account succeeds when increasing the gas limit.

```
const address = await Tezos.signer.publicKeyHash();
const balance = await Tezos.tz.getBalance(address);
console.log(
	`The account we want to drain is ${address}.\nIts initial balance is ${balance.toNumber() / 1000000} ꜩ.`
);
const estimate = await Tezos.estimate.transfer({
	to: await tezos.signer.publicKeyHash(),
	amount: balance.toNumber() - 64250,
	mutez: true
});
const totalFees = estimate.suggestedFeeMutez + estimate.burnFeeMutez;
const maxAmount = balance.minus(totalFees).toNumber();
console.log(
	`The estimated fees related to the emptying operation are ${totalFees} mutez.\n
	Considering the fees, the amount we need to send to empty the account is ${maxAmount / 1000000} ꜩ.`
);
const opTransfer = await Tezos.contract.transfer({
	to: await tezos.signer.publicKeyHash(),
	mutez: true,
	amount: maxAmount,
	fee: estimate.suggestedFeeMutez,
	gasLimit: 1900, // estimate.gasLimit,
	storageLimit: estimate.storageLimit
});
console.log(`Waiting for confirmation of the draining operation...`);
await opTransfer.confirmation();
console.log(`The account has been emptied.`);
const finalBalance = await Tezos.tz.getBalance(address);
console.log(`The balance is now ${finalBalance.toNumber() / 1000000} ꜩ.`);
```

**Comment by oleiba** [comment]
Thank you for your reply. 
Does your example empty the sending account completely (even when sent to a new account)?
Is 1900 is the magic number for a transfer gas limit? 
I assume it would be nice to have both magic numbers (64250 for burn fee and 1900 for gas limit) as constants in the SDK, but up to you.

**Comment by roxaneletourneau** [comment]
@oleiba 
Yes, it empties completely the account when sent to a new account. Here is an example: https://delphi.tzstats.com/ooxDYArnDi48JcVB4awQ8wKrWkeFR8bFKNHVp7ACVAyzNWWjSyp/3410441

It looks like the node expects a higher gas limit than usual for this particular case (which surprises me). 

1900 is a gas limit value that is high enough to have this transaction broadcasted without having to increase the fees.
