### ISSUE TITLE
Update to beacon-sdk 1.2.0

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taquito#497]
Make a branch from tar `7.0.0-beta.0` and update to https://www.npmjs.com/package/@airgap/beacon-sdk/v/1.2.0

We will release this as taquito `7.0.1-beta.0`. It's important to make the branch from the tag as we have new features in `master`

**Comment by roxaneletourneau** [comment]
The update is in a branch called `update-beacon-sdk1.2.0`
