### ISSUE TITLE
Add documentation on running flextesa in a dev workflow

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taquito#499]
Make documentation explaining how to get a local flextesa node set up, and how to use it in a development workflow.

- [ ]  Internal notion page
- [ ] Generic user documentation for the website, i.e. environment setup 

Related to:
#457 
#276

**Comment by roxaneletourneau** [comment]
https://tezos.gitlab.io/flextesa/

**Comment by hui-an-yang** [comment]
https://github.com/ecadlabs/taquito/tree/master/integration-tests#taquito-integration-tests-with-flextesa
@michaelkernaghan has documented well how to run integration tests with flextesa. 
Also, flextesa is no longer maintained; the latest docker image was 6m ago for oxford1.
flextesa tests will not be relevant anymore; we have [ticket2851](https://github.com/ecadlabs/taquito/issues/2851) to update our ci script. We will add updating the README.md in integration-test folder, too.
