### ISSUE TITLE
Basic support for TZIP-16 with IPFS as a storage

### ISSUE THREAD

**Issue by Innkst** [ecadlabs/taquito#501]
**As a Developer, I want to read the TZIP-16 smart contract and its metadata with IPFS as storage so that I can further manipulate its data.**

**Acceptance criteria:**
- High-level APIs to `@taquito/taquito` supports IPFS storage:
    - fetch contract metadata for a given contract
    - get metadata element <string> from a given contract
- When fetching metadata for a given contract, validate:
    - big_map %metadata string bytes
        - if validation fails, fail fetching with an error: _Metadata has a wrong type._
    - Check if it is located within the top-level tree of nested pairs forming the
    storage type
        - if validation fails, fail fetching with an error: _Metadata not found._
    - ~~metadata value against TZIP-16 JSON schema~~
        - ~~if validation fails, fail to fetch with an error: _Metadata does not comply with TZIP-16 specification._~~
- User can use a custom fetcher in place of the default one
   - This covers a use case where the user needs to use authentication or custom headers as part of their individual workflow.
- User can use a customer IPFS provider. 
   - HTTP provider is used by default
- Supported cases:
    - Storage types: IPFS
       - with or without sha256
       - https://github.com/ipfs/in-web-browsers/blob/master/ADDRESSING.md#addressing-with-native-url
      - https://tezosguides.com/ipfs/
    - Edge case: 
       - empty metadata, still TZIP-16
       - Emojis, Naughty Strings (https://github.com/minimaxir/big-list-of-naughty-strings, ) and other edge cases UTF-8 (French, Chinese characters)
    - Failure scenarios:
        - Invalid URI
        - Invalid JSON
        - No metadata
        - Invalid metadata type/location

OUT OF SCOPE:
* Off-chain views ( will be covered in a separate ticket)

**Comment by roxaneletourneau** [comment]
Example contract: KT1BfdzrP3ybxSbQCNZrmdk2Y5AQjRK1KKkz

I used the HTTP API exposed by IPFS (instead of a library) with a default public gateway (ipfs.io). The constructor of the IpfsHandler class takes an optional ipfsGatheway. 
It is therefore customizable via the Tzip16Module class.
