### ISSUE TITLE
Basic support for TZIP-16 with tezos_storage as a storage

### ISSUE THREAD

**Issue by Innkst** [ecadlabs/taquito#503]
**As a Developer, I want to read the TZIP-16 smart contract and its metadata with contract as storage so that I can further manipulate its data.**

**Acceptance criteria:**
- High-level APIs to `@taquito/taquito` work with on-chain storage (tezos-storage):
    - fetch contract metadata for a given contract
    - get metadata element <string> from a given contract
- When fetching metadata for a given contract, validate:
    - big_map %metadata string bytes
        - if validation fails, fail fetching with an error: _Metadata has a wrong type._
    - Check if it is located within the top-level tree of nested pairs forming the
    storage type
        - if validation fails, fail fetching with an error: _Metadata not found._
    - ~~metadata value against TZIP-16 JSON schema~~
        - ~~if validation fails, fail to fetch with an error: _Metadata does not comply with TZIP-16 specification._~~
- User can use a custom fetcher in place of the default one
   - This covers a use case where the user needs to use authentication or custom headers as part of their individual workflow.
- Supported cases:
    - Storage types: 
      - tezos-storage:self 
         - with/without sha256 hash
      - tezos-storage: refers to the other smart contract for the current network
         - with/without sha256 hash
    - Edge case: 
       - empty metadata, still TZIP-16
       - Emojis, Naughty Strings (https://github.com/minimaxir/big-list-of-naughty-strings, ) and other edge cases UTF-8 (French, Chinese characters)
    - Failure scenarios:
        - Invalid URI
        - Invalid JSON
        - No metadata
        - Invalid metadata type/location

OUT OF SCOPE:
* Other types of storage(sha256)
* Off-chain views ( will be covered in a separate ticket)

**Comment by roxaneletourneau** [comment]
> When fetching metadata for a given contract, validate:
> - big_map %metadata string bytes
> - Check if it is located within the top-level tree of nested pairs forming the
> storage type

`Tzip16ContractAbstraction.getMetadata()` will look in the top-level pairs of the contract storage to find the big map matching the following specific type (or fail with `BigMapMetadataNotFound`): 
```
{
    prim: 'big_map',
    args: [{ prim: 'string' }, { prim: 'bytes' }],
    annots: ['%metadata']
}
```

> - metadata value against TZIP-16 JSON schema

**Not implemented yet.** Currently, it only fails with `InvalidMetadata` if metadata is not a JSON object. It may not be appropriate to fail it if it is not compliant (take the example where there is a typo in one of the keys). We could add a public method that do the check to the Tzip16ContractAbstraction class or add a property to the MetadataEnvelope.

> User can use a custom fetcher in place of the default one

The constructor of the `Tzip16Module` class takes an optional Metadata Provider as a parameter. This allows to inject a custom metadata provider and/or custom protocol handlers if desired. `tezos.addExtension(new Tzip16Module());`

**Comment by zamrokk** [comment]
Hi @roxaneletourneau , we are testing different way of representing FA2 and it might be an issue with taquito on this token_id 0 definition here : 

https://better-call.dev/ghostnet/KT1HgSfpwbhSNCL8qUTtN4kXKmsFTyLHAZh5/storage/big_map/202564/keys

when taquito try to parse using tzip12/tzip16 module, then it comes to this code here and throw an error

` private formatMetadataToken(
    tokenId: number,
    metadataTokenMap: MichelsonMap<string, string>,
    metadataFromUri?: any
  ): TokenMetadata {
    const tokenMetadataDecoded = {
      token_id: tokenId,
    };
    for (const keyTokenMetadata of metadataTokenMap.keys()) {
      if (keyTokenMetadata === 'decimals') {
        Object.assign(tokenMetadataDecoded, {
          // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
          [keyTokenMetadata]: Number(bytes2Char(metadataTokenMap.get(keyTokenMetadata)!)),
        });
      } else if (!(keyTokenMetadata === '')) {
        Object.assign(tokenMetadataDecoded, {
          // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
          [keyTokenMetadata]: bytes2Char(metadataTokenMap.get(keyTokenMetadata)!),
        });
      }
    }
    // if an URI is present, add the fetched properties to the object
    // if a property is in the URI and the map, prevalence is accorded to value from the URI
    if (metadataFromUri) {
      for (const property in metadataFromUri) {
        Object.assign(tokenMetadataDecoded, { [property]: metadataFromUri[property] });
      }
    }
    if (!('decimals' in tokenMetadataDecoded)) {
      throw new InvalidTokenMetadata();
    }
    return tokenMetadataDecoded as TokenMetadata;
  }`
  
  this is the line throwing the error => 
  `  if (!('decimals' in tokenMetadataDecoded)) {
      throw new InvalidTokenMetadata();
    }`
    
    is because the field is just converted from bytes to char and then trying to find a field "decimals" on a string (that should be an object) will fail
