### ISSUE TITLE
Build and publish taquito to npm from pull requests

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taquito#506]
**As a developer, I would like to get an updated npm package so that I can test and evaluate new features and bug fixes as soon as possible without having to clone and locally link Taquito.**

**Acceptance criteria:**
- Use npm org called @taquito_edge 
- When a PR is created, and if the tests pass, build and publish the packages to npm
- For a PR from  a branch in the Taquito repo or a forked repository:
   - A branch named: `mk-wallet-empty-delegated-implicit-account`
   - The latest commit hash `0fdad917947ae2fb553cc2ea3b2b62818d57d6ea`
   - The short commit hash would be `0fdad917` (first 8 characters)
   - Version is composed from template `0.0.0-${SHORT_SHA}--${BRANCH_NAME}`
   - `"0.0.0-0fdad917--mk-wallet-empty-delegated-implicit-account"`
   - npm package name:
      - `@taquito_edge/taquito@0.0.0-0fdad917--mk-wallet-empty-delegated-implicit-account`
      - `@taquito_edge/michel-codec@0.0.0-0fdad917--mk-wallet-empty-delegated-implicit-account`
   -Note, the npm "dist-tag" should be set to "edge". Command example: `lerna publish --dist-tag edge from-package`
- Publish a description and a disclaimer: TBD (_WARNING This build is produced from a feature branch and could contain unreviewed changes from the public. Use with caution, do not use in production_) See details below.
- After PR is merged, the same process is triggered with:
    - Version:"`${LAST_VERSION}-${SHORT_SHA}--master", i.e. "v8.0.3-0fdad917--master"`
- Add README documentation for users on how to get a feature build(from PR) or current build(from master).

**To get the current version on master**, and to compose a new package name, the following command is servicable:

```
export GITSHA=0fdad917 # Assumed git sha on master as example
export VERSION="$(jq -r .version packages/taquito/package.json | cut -d '-' -f 1)-${GITSHA}--master"
```

Result will be: `8.0.3-0fdad917--master`

Shell command to add warning line to first line of all package `README.md` files:

```shell
find packages/ -mindepth 1 -maxdepth 2 -name README.md  | xargs sed -i '1s/^/# WARNING This build is produced from a feature branch and could contain unreviewed changes from the public. Use with caution, do not use in production\n\n/'
```

The steps to make a tagged release of Taquito can be found here: https://www.notion.so/ecad/Release-Process-3a1ac1aa751f4450bb3410f3fb1a56b7

**Comment by AlirezaHaghshenas** [comment]
In PRs if we start the version number with `0.0.0-` then sorting packages by version gives no usable insight, but if we use the existing package number (like we do after merging into master), there will be more meaning encoded into the version number.

I can see two cons to using package's version in PRs:
1. If the PR author has changed the version in package, our npm packages will be confusing again
2. If the PR is made from the `master` branch of a fork, then the version can be confused with packages published after merging.

Is there more logic behind this version scheme?

**Comment by jevonearth** [comment]
Branches can be made at different times from master at different versions,
so version numbers might seem sequential, but often won't be. My reasoning
was that if the version numbers from PRS are not in order, then let's not
use versions at all (and be explicit about it by using 0.0.0), and rely on
git sha's + branch name instead.

I'm open to better ideas off course! ;)

**Comment by AlirezaHaghshenas** [comment]
If there was a way to prevent version changes in forks, I think having the same version number from package.json (is this the same as LAST_VERSION?) could be more informative. It gives some information like: which commit (probably of master) this was forked from, and meets some other expectations as well, like: if there is a master package, then each PR package with a higher version is expected to have all features in this version, plus some (usually only one) additional feature.

I think we can do one of:
1. Ignore the chance of the fork developer to change version numbers (and break people's expectations)
2. Use 0.0.0 and think about this later.

**Comment by jevonearth** [comment]
Let's go with what you feel is best. We can see how it works. There's no
impediment to change our approach in this context later on, should we see
fit.

**Comment by jevonearth** [comment]
Done and working, nice work @AlirezaHaghshenas
