### ISSUE TITLE
Type Error with InMemorySigner

### ISSUE THREAD

**Issue by d4hines** [ecadlabs/taquito#510]
Attempting to follow the [quick start guide](https://tezostaquito.io/docs/quick_start#importing-a-faucet-key), I run into the following error from Typescript:
```
srct/index.ts:7:29 - error TS2554: Expected 1-2 arguments, but got 0.

7 Tezos.setProvider({ signer: new InMemorySigner() });
                              ~~~~~~~~~~~~~~~~~~~~

  node_modules/@taquito/signer/dist/types/taquito-signer.d.ts:25:17
    25     constructor(key: string, passphrase?: string);
                       ~~~~~~~~~~~
    An argument for 'key' was not provided.


Found 1 error.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Any help fixing this would be appreciated.

**Comment by roxaneletourneau** [comment]
Hi @d4hines 
The constructor of InMemorySigner class takes a private key as a parameter and (an optional passphrase to decrypt the private key if it is encrypted).
Here is an example: https://github.com/ecadlabs/taquito/blob/master/example/contract-schema.ts

**Comment by jevonearth** [comment]
Closing. If this is still an issue and you need further help, please reopen!
