### ISSUE TITLE
println?

### ISSUE THREAD

**Issue by d4hines** [ecadlabs/taquito#511]
As I'm working through the Taquito docs, I keep seeing references to `println`, which doesn't exist in Javascript standard lib. It might be smoother for users trying to copy-paste code by changing such references to `console.log`.

**Comment by roxaneletourneau** [comment]
Hi @d4hines 
`println` is a custom method allowing to print data under the live examples when hitting the run button. Changing it to `console.log` would be problematic as the data would be printed in the console browser instead of under the examples.

**Comment by michaelkernaghan** [comment]
this suggests changing all live code examples in docs to use console log instead of println.
