### ISSUE TITLE
Integration tests for origination of contracts having metadata with HTTPS URI as storage

### ISSUE THREAD

**Issue by roxaneletourneau** [ecadlabs/taquito#530]
- [x] Deploy a contract having valid metadata stored at an HTTPS URL (use google bucket to store metadata)
- [x] Deploy a contract having empty metadata stored at an HTTPS URL 
- [x] Deploy a contract having invalid metadata stored at an HTTPS URL 
- [x] Deploy a contract having metadata which contains emoji stored at an HTTPS URL 
- [x] Deploy a fa2 contract having metadata stored at an HTTPS URL

**Comment by Innkst** [comment]
Related to #451
