### ISSUE TITLE
Add additional integration tests for the wallet API

### ISSUE THREAD

**Issue by roxaneletourneau** [ecadlabs/taquito#544]
Most of the integration tests used the contract API.
For the wallet API, there are currently integration tests for origination in the file: wallet-api.spec.ts. We should build out better test coverage.

**Comment by michaelkernaghan** [comment]
I am taking tests for contract.* and converting to make wallet.*

**Comment by michaelkernaghan** [comment]
my progress can be tracked on Sheet 2 of this google doc:  https://docs.google.com/spreadsheets/d/1QceR58FTIm34R86aWtzAsBHeWVDGBPR20O5ASShuj_s/edit?usp=sharing

**Comment by michaelkernaghan** [comment]
I have completed adding mirror tests to do with wallet API what contracts do.

Does that close this issue?

**Comment by roxaneletourneau** [comment]
Yes, thanks for your work on that!

**Comment by michaelkernaghan** [comment]
ok thanks!
