### ISSUE TITLE
Support for tickets

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taquito#550]
**This ticket might be needed if there are any high-level abstractions to be added to Taquito Contract or other APIs themselves.**

The following instructions and type are already supported:
- new Michelson type `ticket(t)`
- new operations: TICKET, READ_TICKET, SPLIT_TICKET, JOIN_TICKETS  called SAPLING_VERIFY_UPDATE and SAPLING_EMPTY_STATE (see the Michelson [reference ](https://tezos.gitlab.io/008/michelson.html#michelson-008) for more details).

This ticket will cover extra abstractions needed for tickets.
Refer to https://www.notion.so/ecad/Taquito-Epic-Tickets-624a27ae625f4fa39dcc2b756ce216e3 for more details.

Related docs:
- https://tezos.gitlab.io/008/michelson.html#michelsontickets-008
- https://medium.com/aditya-gautam-tech-blog/the-significance-of-tickets-on-edo-protocol-5bb126811d37

**Comment by Innkst** [comment]
We have discussed current support for tickets and based on work already done, new abstractions are not required.

**Comment by zamrokk** [comment]
public EncodeObject(_args: any): any {
    throw new EncodeTicketError();
  }

**Comment by zamrokk** [comment]
![image](https://user-images.githubusercontent.com/2536368/161713678-27a5773d-830f-4ffb-b0a5-e018dc8021c6.png)

**Comment by roxaneletourneau** [comment]
Hi @zamrokk 
This is a bug in the MichelsonMap, I created an issue to fix it: https://github.com/ecadlabs/taquito/issues/1497
