### ISSUE TITLE
Update Taquito Docs website live code examples to use edonet

### ISSUE THREAD

**Issue by roxaneletourneau** [ecadlabs/taquito#566]
Now need to be updated to Edo.

The live code examples are using Carthagenet. Needs to be updated to Delphinet.

- Replace carthagenet by delphinet in index.js files of CodeBlock and Playground folders
- For the examples that call a contract, deploy the same contract on Delphinet

**Comment by claudebarde** [comment]
I started working on it. The main issue is going to be copying big maps from Carthagenet to Delphinet, copying the entries manually would take forever, writing a script to copy them would still take a substantial amount of time, what should we do with them?

**Comment by michaelkernaghan** [comment]
You would need to change the URL or network there:
https://github.com/ecadlabs/taquito/blob/master/website/src/theme/CodeBlock/index.js#L81
https://github.com/ecadlabs/taquito/blob/master/website/src/theme/Playground/index.js#L49
https://github.com/ecadlabs/taquito/blob/master/website/src/theme/Playground/index.js#L52
https://github.com/ecadlabs/taquito/blob/master/website/src/theme/Playground/index.js#L60
And there are examples that make a call to contracts deploy

**Comment by michaelkernaghan** [comment]
it('Deploy a contract having metadata stored at on IPFS', async (done) => {
            // carthagenet: KT1PBndiMVyeptfQejZKYcSB6YmucaJdXVBQ
            // delphinet: KT1BfdzrP3ybxSbQCNZrmdk2Y5AQjRK1KKkz

need to add a contract for edonet

**Comment by michaelkernaghan** [comment]
Docs using delphinet contract that needs an edonet replacement:

Pages that use : tz1PgQt52JMirBUhhkq1eanX8hVd1Fsg71Lr
    
docs/complex_parameters.md
docs/drain_account.md
docs/storage_annotations.md

Pages that use : tz1h3rQ8wBxFd8L9B3d7Jhaawu6Z568XU3xY
estimate.md
lambda_view.md
ledger_signer.md
making_transfers.md
maps_bigmaps.md
quick_start.md

Pages that use : KT1PupyraehzPEjTKJgY2qmZHXdP5pQUyGgC
estimate.md

Pages that use: KT1Guzg4pWj5BEyc8qtoicNsuPCYfjRbYLZc
complex_parameters.md
drain_account.md

Pages that use: KT1Bki1YP1JdykrMH4iTTt7bguHsbeuUAbpG

Pages that use: KT1MB4fe2b9euiMk1W4evxnfQHbq8FB5Yrbe

**Comment by michaelkernaghan** [comment]
This is the PR from the upgrade from Carthage to Delphi:
https://github.com/ecadlabs/taquito/pull/571/commits/a29809e19ce271f58361e5ab2cbe63a6d6ae690a

**Comment by michaelkernaghan** [comment]
I have created a spreadsheet that lists each page, each live code example, and the implicit and/or originated accounts used by each.

https://docs.google.com/spreadsheets/d/1-mifIF1LNZUJ_etpFcSsYx2yaZT0anz_AeDrrmfCLAI/edit#gid=0

the list can be sorted and pivoted, so for each implicit account for example we can tell which live code examples it is used in. 

I just need to find out how to create new accounts for the tests that will work with edonet. I suppose this means finding the node that is in use and creating accounts that can be found there by the tests.
