### ISSUE TITLE
Create tzip16 contracts/metadata with hostile data

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taquito#568]
Create a suite of contracts that contain tzip16 contract meta-data with hostile payloads.

Motivation; to provide users of Tezos easily accessible examples of hostile data so that new tooling and dApps deal with this class of vulnerabilities early on.

Example data can be found here:

XSS type data: https://github.com/payloadbox/xss-payload-list
Naughty Strings: https://github.com/minimaxir/big-list-of-naughty-strings

OUT OF SCOPE:
- Storage
- storage with bigmaps

**Comment by michaelkernaghan** [comment]
useful info:  https://dev-tester.com/test-your-form-inputs-with-naughty-strings/

**Comment by michaelkernaghan** [comment]
I have created a draft blog post on this topic here:
https://docs.google.com/document/d/12eyQYodFoLe5HDCANwo7ls_lvmCo0uL-HgfCemYB-Uo/edit

anyone with the link can edit

we can put it into a final destination with formatting when done

**Comment by michaelkernaghan** [comment]
also try some XXS strings from : https://owasp.org/www-community/xss-filter-evasion-cheatsheet

**Comment by michaelkernaghan** [comment]
I have revised the document:  https://docs.google.com/document/d/12eyQYodFoLe5HDCANwo7ls_lvmCo0uL-HgfCemYB-Uo/edit?usp=sharing

and I have added three constructed contracts on Florencenet that can be ported to mainnet. The addresses are in the document in the Conclusion.

**Comment by michaelkernaghan** [comment]
I have attached a report to https://www.notion.so/ecad/TZIP-16-Contract-Metadata-1fcff4a9ca534541a1dc77fca3e74a2e
