### ISSUE TITLE
Retrieve Token Metadata (TZIP 12+16)

### ISSUE THREAD

**Issue by Innkst** [ecadlabs/taquito#570]
**As Developer, I would like to have the ability to retrieve token metadata information for a token per contract that is TZIP-12 compatible, so that I can use the info in my Application.**

**Acceptance Criteria:**

- Retrieve token metadata from TZIP-16 `%metadata big_map` through `token_metadata`view.
    - All TZIP-16 metadata use cases are supported: contract storage, http/https, ipfs with/without sha256
- If the `token_metadata` view doesn't exist, retrieve token metadata from the storage as `%token_metadata big_map`
- Token metadata represents a collection of token`(map string bytes)` information for each token (nat (token_id)) specified by the contract and contains the following properties:
    - name (optional): UTF-8 string giving a “display name” to the token
    - symbol (optional): UTF-8 string for the short identifier of the token
    (e.g. XTZ, EUR, …).
    - decimal (required): an integer (converted to a UTF-8 string in decimal)
    which defines the position of the decimal point in token balances for display
    purposes.

NOTE: Above needs to happen in the specified sequence because if both are defined, the `token_metadata`view is given a preference based on the [TZIP-12 spec](https://gitlab.com/tzip/tzip/-/blob/master/proposals/tzip-12/tzip-12.md#token-metadata).

**Comment by jevonearth** [comment]
:clap:

**Comment by zamrokk** [comment]
@roxaneletourneau : is there a way to fetch additional fields of the metada map ? 
I am thinking of `thumbnailUri` for example

**Comment by roxaneletourneau** [comment]
Hi @zamrokk, if there are additional values ​​(more than token_id, decimals, name and symbol) they should be returned as well. If not, can you send me the address of a contract having `thumbnailUri`, I will take a closer look.

**Comment by zamrokk** [comment]
ok, so I extended the TokenMetada type, lets see the tests on next days :)
