### ISSUE TITLE
Wallet API Testing page for Beacon/tzip-10

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taquito#582]
As a Taquito developer/tester, I want a web page that exercises all the common user journeys/activities between a dapp and a TZIP10 wallet so that I have an area to conduct repeatable tests of Taquito, Beacon and supported wallets. 

Tentative URL for the new page:  `http://tezostaquito.io/tests/tzip10`

- Each feature action should be in its own visual box/section. We will add descriptive text to the sections to contextulise the feature and purpose for the user/tester.
- Each section and input element (text fields, buttons) should have unique `id` values so that writing browser automation tests is easy and predictable.
- Each action should be timed, and the time should be printed to the web-page to make it easy for a tester to see precisely how long an action takes.

Specific buttons/inputs for;

- [x] connect wallet
- [x] disconnect wallet (depends on the connected state)
- [ ] reset (I forget the correct term)
- [x] Send tokens to address
- [x] Originate smart contract with success
- [x] Originate smart contract that fails
- [x] Call smart contract method that takes a primitive type as an argument
- [x] Call smart contract method that takes a complex type as an argument
- [ ] Call smart contract that takes  a complex type with optinoal params (both cases)
- [ ] Call smart contract that will throw a failwith error.
- [ ] Request signing of arbitrary string

We want this page within the website so that when website deployment previews (#473) get deployed, testing can be done immediately.

**Comment by AndreasGassmann** [comment]
That list is a very good start. We should include all of those cases in the beacon-sdk tests as well. Currently, we only have unit tests, but I would also like to introduce e2e tests that verify the behaviour in an actual browser with all the moving parts. Some additional things that I would like to cover in the beacon-sdk are related to establishing a connection to different wallets (eg. browser wallet and p2p wallet), the "reconnect" behaviour on page refreshes, as well as error cases that are triggered by changes in the wallet (eg. a connected account is removed in the wallet).

Do you already have an e2e testing setup in place (or in mind)? Maybe we could run a similar setup and save some time by sharing the test-setup.

**Comment by mkernaghan** [comment]
Tzip10 has proposed handshake: https://gitlab.com/tzip/tzip/-/blob/master/proposals/tzip-10/tzip-10.md#handshake-

could the web page make those steps clear (walkthrough with timings) , or is this better "under the hood"?

**Comment by jevonearth** [comment]
@AndreasGassmann we don't have e2e infra setup yet, but this work is a precursor to that. 

Some elements of wallet interactions are designed not to be automated, so we while we can automate a lot of this stuff, some will have to be tested by humans.

Testing these scenarios with the different tzip10 wallets is our goal so we can get a good overview.

The reconnect scenarios is a good one. I want to also get into permissions, but probably on the second round of this.

@mkernaghan WRT handshakes, if possible, we can surface a lot of that technical information on the test page.

**Comment by mkernaghan** [comment]
Most of the specific buttons listed are working now.
Are you intending to add more @claudebarde ?

**Comment by claudebarde** [comment]
@mkernaghan I want to run more tests (and hear from yours!) before ticking the boxes, for example with Kukai wallet as Jev mentioned the issue with the testnet version today.

**Comment by mkernaghan** [comment]
I did a walkthrough and tried out things in the Beacon Test Dapp.  This is a draft, I made have made errors:
https://ecadlabs.ontestpad.com/script/42/report
perhaps we can use this as a checklist to determine when this issue can be closed.

**Comment by mkernaghan** [comment]
It would be great if we could add to the Test Dapp:
a link to the operation hash for the contract tested

**Comment by Innkst** [comment]
I believe, test are now here: https://ecadlabs.ontestpad.com/project/2/. The above link didn't work somehow.

**Comment by michaelkernaghan** [comment]
*these are working:*
 connect wallet
 disconnect wallet (depends on the connected state)
 Send tokens to address
 Originate smart contract with success
 Originate smart contract that fails
 Call smart contract method that takes a primitive type as an argument
 
*these are on the page but not working*
Call smart contract method that takes a complex type as an argument
 Call smart contract that takes a complex type with optional params (both cases)

*These I believe are not on the page*
 Call smart contract that will throw a failwith error.
 Request signing of an arbitrary string
 reset (I forget the correct term)
