### ISSUE TITLE
[Feature Request] - Operation results should be exposed before block confirmation

### ISSUE THREAD

**Issue by RomarQ** [ecadlabs/taquito#585]
Currently, WalletOperation class only exposes the operation results after at least 1 block was seen with the injected operation.

Having access to operation results before the block confirmation would be useful to present information to the users while the operation gets included in the chain.

**Comment by jevonearth** [comment]
We should try address this at the same time as we do #435

**Comment by RomarQ** [comment]
At the time, I ended up using another API I think.

An example where having access to the result before the block confirmation is helpful is on originated operations, where the address of the originated contract is in the pre-apply result.

What if the API was like this? (I don't remember the API anymore, just some pseudo code bellow)

`<operations>.send()` returns:

```ts
{
 operation_hash: string;
 estimated_result: PreapplyResult;
 wait: (blocks: number) => Promise<OperationResult>
}
```

This is just a suggestion, nothing really important.

**Comment by roxaneletourneau** [comment]
Ok I see, having the address of the originated contract before the confirmation is interesting.
But the thing with the wallet API is that we are missing information that would be needed for the preapply step. Fees can be set by the wallet, we don't know the branch and the signature, which are required as parameters of helpers/preapply/operations
