### ISSUE TITLE
Token Metadata support for TZIP-7/FA1.2 contracts

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taquito#593]
A proposal (https://gitlab.com/tzip/tzip/-/merge_requests/140) to use FA2/TZIP-12 metadata in FA1.2 contracts is in the process of being finalised.

The single difference is that FA1.2 contracts use only token id `0`.

An example FA1.2 contract with token metadata from Kolibri exists here 
https://delphi.tzstats.com/KT1CiJv61tJ7CUK7oKMmNYRSjpxGJ4GC9TX5

Appears to work okay in the Taquito Metadata explorer. See: https://taquito-metadata-explorer.netlify.app/#/delphinet/KT1CiJv61tJ7CUK7oKMmNYRSjpxGJ4GC9TX5

We need to evaluate the impact of this in Taquito, and how to document/present how to get fa1.2 metadata. The provider is named tzip-12 at the moment.

Acceptance criteria:
- Add integration test to read the above contract(or similar) metadata with token id '0' using Taquito(it looks like it is on delphi, can we find one on the newer protocol?) using tzip-12 abstraction.
- If it doesn't work right away, we need to look into more detail and may need a separate issue.

**Comment by michaelkernaghan** [comment]
The delphi net material is no longer avilabale. Perhaps the equivalent from mainnet is here:   https://better-call.dev/mainnet/KT1K9gCRgaLRFKTErYt1wVxA3Frb9FjasjTV/code

**Comment by michaelkernaghan** [comment]
Does this integration test:  ~/taquito/integration-tests/tzip12-token-metadata.spec.ts   already do this?  It appears to take tzip12 and add fa2 metadata

**Comment by michaelkernaghan** [comment]
The example above uses a governance contract that is at: https://better-call.dev/mainnet/KT1JBmbYxTv3xptk2CadgEdMfjUCUXKEfe5u/operations

**Comment by michaelkernaghan** [comment]
I have found a simpler example to follow by Michael Klien:
https://github.com/tqtezos/lorentz-contract-metadata

**Comment by michaelkernaghan** [comment]
The existing Test: tzip12-token-metadata.spec.ts is for tokens that have multiple ids, not tokens that are only id = 0

**Comment by michaelkernaghan** [comment]
I think we need to distinguish token support from token metadata support.

the example contract I have made by Michael Klien with Lorentz does not have a metadata bigmap

The Taquito docs say:
There are two scenarios to obtain the metadata of a token:

They can be obtained from executing an off-chain view named token_metadata present in the contract metadata
or from a big map named token_metadata in the contract storage.

The storage is just this:
```
storage (pair (big_map address (pair nat (map address nat)))
      (pair address (pair bool nat)));
```
There is a getMetadata entrypoint that has parameter:
```
  (pair %getMetadata (list nat)
                                 (contract (list (pair nat
                                                     (pair string
                                                           (pair string
                                                                 (pair nat
                                                                       (map
                                                                         string
                                                                         string))))))))))));
```
and the code ends with this:
```
 { DUP ;
               CAR ;
               DIP { CDR } ;
               DIP { DIP { DUP } ; SWAP } ;
               PAIR ;
               CAR ;
               ITER { PUSH nat 0 ;
                      COMPARE ;
                      EQ ;
                      IF
                        {}
                        { PUSH string "single token only has id 0" ; FAILWITH } } ;
               PUSH (list (pair nat
                            (pair string
                                  (pair string (pair nat (map string string)))))) { Pair 0 (Pair "TOK" (Pair "Token" (Pair 0 {}))) } ;
               DIP { AMOUNT } ;
               TRANSFER_TOKENS ;
               NIL operation ;
               SWAP ;
               CONS ;
               PAIR } } } } }}`;
```
for this contract, the tzip12 and tzip16 abstract extensions do not apply

**Comment by michaelkernaghan** [comment]
If the token id is not 0 then it fails. That defines the FA2 part.
If it is 0 it creates the token.

I have not figured out how to obtain the token for this contract with Taquito.

**Comment by michaelkernaghan** [comment]
The above contract requires to be called by another contract. It won't be appropriate for this test.

**Comment by michaelkernaghan** [comment]
The integration test  "contract-originate-token-contract.spec.ts"  creates a token from a similar contract, and does not have metadata. So that test shows a tzip-7 contract with tokens.

**Comment by Innkst** [comment]
Closing based on the above comments.
