### ISSUE TITLE
Provide Utility for Verifying Signatures

### ISSUE THREAD

**Issue by keefertaylor** [ecadlabs/taquito#611]
It would be useful to have an API that could verify signatures of payloads. Specifically, it would take:
1) A message
2) A public key (edpk...) 
3) A signature (edsig...)

And would return a boolean indicating if the signature matches. 

As a bonus, it could also support tz2/tz3 signature schemes (sppk/spsig, p2pk,p2sig, IIRC)

**Comment by gwendall** [comment]
@tolmekian1453 @jevonearth Here is a small repro, any idea what I'm doing wrong ?

https://github.com/gwendall/sign-test
