### ISSUE TITLE
RPC Response Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by DEV-SALIM** [ecadlabs/taquito#616]
Hello,

I had this error in my production environment :

`TypeError: Cannot read property '0' of undefined
    at /usr/src/app/node_modules/@taquito/michelson-encoder/src/tokens/pair.ts:119:46
    at PairToken.traversal (/usr/src/app/node_modules/@taquito/michelson-encoder/src/tokens/pair.ts:98:42)
    at PairToken.Execute (/usr/src/app/node_modules/@taquito/michelson-encoder/src/tokens/pair.ts:118:17)
    at /usr/src/app/node_modules/@taquito/michelson-encoder/src/tokens/pair.ts:120:32
    at PairToken.traversal (/usr/src/app/node_modules/@taquito/michelson-encoder/src/tokens/pair.ts:104:20)
    at PairToken.Execute (/usr/src/app/node_modules/@taquito/michelson-encoder/src/tokens/pair.ts:118:17)
    at /usr/src/app/node_modules/@taquito/michelson-encoder/src/tokens/pair.ts:119:30
    at PairToken.traversal (/usr/src/app/node_modules/@taquito/michelson-encoder/src/tokens/pair.ts:95:19)
    at PairToken.Execute (/usr/src/app/node_modules/@taquito/michelson-encoder/src/tokens/pair.ts:118:17)
    at Schema.Execute (/usr/src/app/node_modules/@taquito/michelson-encoder/src/schema/storage.ts:72:31)`

This error happened today, and here is my code:

`Tezos.setProvider({ rpc: 'https://mainnet-tezos.giganode.io' });
const tcontract= await Tezos.contract.at('KT1VUDwGZH3y4iEtBB2ykYSh2KAAa8r5xD6w');
const tcontractStorage = await tcontract.storage();`

Package.json:
`    "dependencies": {
        "@taquito/taquito": "^6.3.5-beta.0",
        "aws-sdk": "^2.756.0",
        "babel": "^6.23.0",
        "babel-cli": "^6.26.0",
        "babel-preset-node8": "^1.2.0",
        "bignumber.js": "^9.0.0",
        "body-parser": "^1.19.0",
        "compression": "^1.7.4",
        "conseiljs": "^5.0.4",
        "cors": "^2.8.5",
        "express": "^4.17.1",
        "express-jwt": "^6.0.0",
        "express-validator": "^5.2.0",
        "forever": "^1.0.0",
        "jwks-rsa": "^1.10.1",
        "jwt-decode": "^3.0.0",
        "moment": "^2.26.0",
        "mongoose": "^5.7.1",
        "morgan": "^1.9.1",
        "multer": "^1.4.2",
        "multer-s3": "^2.9.0",
        "nodemon": "^1.19.2",
        "path": "^0.12.7",
        "request": "^2.88.2"
    }`

?? Any solution ??

**Comment by claudebarde** [comment]
Hi!
The version of Taquito you are using is outdated and doesn't support the new combs brought by the Edo protocol.  
Please update to version `8.0.1-beta.1` and make the necessary fixes explained [in this document](https://tezostaquito.io/docs/v7_breaking_changes)
Let me know if that fixed it :)

**Comment by roxaneletourneau** [comment]
I tried with the latest version of Taquito and I confirm your contract is working.

```
Tezos.setRpcProvider('https://api.tez.ie/rpc/mainnet');
const contract = await Tezos.contract.at('KT1VUDwGZH3y4iEtBB2ykYSh2KAAa8r5xD6w')
const storage = await contract.storage();
console.log(storage)
```

The output was:
```
{
      administrator: 'tz1X2y2XiykPpoCPqpMRysEidZFV8ExUQgUp',
      balances: BigMapAbstraction {
        id: BigNumber { s: 1, e: 2, c: [Array] },
        schema: Schema {
          root: [BigMapToken],
          bigMap: [BigMapToken],
          [Symbol(taquito-schema-type-symbol)]: true
        },
        provider: RpcContractProvider {
          context: [Context],
          estimator: [RPCEstimateProvider],
          contractProviderTypeSymbol: Symbol(taquito--provider-type-symbol)
        }
      },
      paused: false,
      safelistAddress: 'KT1M3aoRDvJFoCFHKRfxtg3ertu2YTn7c7pt',
      tokenName: 'TKZ',
      totalSupply: BigNumber { s: 1, e: 5, c: [ 100817 ] }
    }
```

**Comment by roxaneletourneau** [comment]
I tried with the latest version of Taquito, and I confirm your contract is working.

```
Tezos.setRpcProvider('https://api.tez.ie/rpc/mainnet');
const contract = await Tezos.contract.at('KT1VUDwGZH3y4iEtBB2ykYSh2KAAa8r5xD6w');
const sto = await contract.storage();
console.log(sto);
```

The output was:
```
{
      administrator: 'tz1X2y2XiykPpoCPqpMRysEidZFV8ExUQgUp',
      balances: BigMapAbstraction {
        id: BigNumber { s: 1, e: 2, c: [Array] },
        schema: Schema {
          root: [BigMapToken],
          bigMap: [BigMapToken],
          [Symbol(taquito-schema-type-symbol)]: true
        },
        provider: RpcContractProvider {
          context: [Context],
          estimator: [RPCEstimateProvider],
          contractProviderTypeSymbol: Symbol(taquito--provider-type-symbol)
        }
      },
      paused: false,
      safelistAddress: 'KT1M3aoRDvJFoCFHKRfxtg3ertu2YTn7c7pt',
      tokenName: 'TKZ',
      totalSupply: BigNumber { s: 1, e: 5, c: [ 100817 ] }
    }
```

**Comment by DEV-SALIM** [comment]
Thanks @claudebarde @roxaneletourneau for your answers, I'll try it, 
I'm currently in the production environnement, is there a troubleshooting solution?

**Comment by DEV-SALIM** [comment]
> 
> 
> Hi!
> The version of Taquito you are using is outdated and doesn't support the new combs brought by the Edo protocol.
> Please update to version `8.0.1-beta.1` and make the necessary fixes explained [in this document](https://tezostaquito.io/docs/v7_breaking_changes)
> Let me know if that fixed it :)

Thank you for your answer, I'll try it, 
Currently i'm in the production env, is there a troubleshooting solution?

**Comment by DEV-SALIM** [comment]
Thanks @claudebarde @roxaneletourneau for your answers, works well now.
