### ISSUE TITLE
New error in the batch version of contract origination

### ISSUE THREAD

**Issue by emishur** [ecadlabs/taquito#624]
There is a new error in taquito versions after `8.0.0-beta.3`

The following code that worked in `8.0.0-beta.3`

```typescript
async prepareOperation(..., batch: OperationBatch): Promise<OperationBatch> {
    ...
    const storage = `(Pair "${admin}" None)`;
    return batch.withOrigination({ code, init: storage });
  }
```
Gives the following error: `"Wrong code parameter type, expected an array"`

Non-batched version works fine:
```typescript
const storage = `(Pair "${admin}" None)`;
...
const originationOp = await tz.contract.originate({
      code,
      init: storage
    });
const contract = await originationOp.contract();
```

[Full error text and contract code](https://gist.github.com/emishur/23374415bf094ba13de94d9cf9f6cbbd)

**Comment by jevonearth** [comment]
Fixed and released in `@taquito/taquito@8.0.3-beta.0` 

Thank you @emishur for the report! Thank you @roxaneletourneau for the quick turnaround! :)
