### ISSUE TITLE
Add logging to console for taquito integration tests when call to key agent returns 503

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taquito#629]
When running Taquito integration tests, either locally or in the CI, a critical call to the keygen agent is made. When the call fails, the tests will fail, but it is not obvious why. 
If we add a log to console to the code where the key agent is called, if the response is 503, we can see immediately that the cause of the test failures is that keygen needs attention.

here is the relevant call to keygen agent in integration-tests/config.ts:

  const key = await httpClient.createRequest<string>({
    url: keyUrl,
    method: 'POST',
    headers: requestHeaders,
    json: false,
  });

**Comment by roxaneletourneau** [comment]
@michaelkernaghan  
I tried something: wrap the call in a try-catch and logging to the console any error that happens (not specific to 503). It will be in my next PR with the fix for the estimation test.
