### ISSUE TITLE
Does not encode nat and int longer than 1e+21

### ISSUE THREAD

**Issue by dexterslabor** [ecadlabs/taquito#637]
Encoding a numeral with more than 21 digits does not work. Eg. this happens when invoking a contract with `nat` as parameter. This is an example contract that takes `nat` as parameter in %default [KT1MpPsdFiwnLURhGBzmCTUB7XsGCBebmiRs](https://better-call.dev/edo2net/KT1MpPsdFiwnLURhGBzmCTUB7XsGCBebmiRs).

The problem is that the BigNumber needs to be converted to a String for the Tezos node. Taquito uses `BigNumber.toString()` that performs the parsing. Unfortunately, in JavaScript long numbers with many zeros get converted to the scientific notation. Instead of `1,000,000,000,000,000,000,000` it shows `1e+21` as string. The solution is to use `BigNumber.toFixed()`. 

```js
const largerNumber = BigNumber("1000000000000000000000")
print(largeNumber.toString()) // "1e+21"

const largerNumber = BigNumber("1000000000000000000000")
print(largeNumber.toFixed()) // "1000000000000000000000"
 ```

This issue is similar to https://github.com/madfish-solutions/thanos-wallet/issues/243.

I only skimmed the code, but I suspect it needs to be changed here:
[taquito-michelson-encoder/src/tokens/comparable/nat.ts](https://github.com/ecadlabs/taquito/blob/6a4e4ab6ac59555ffa5b58dd04702b0f4cb81735/packages/taquito-michelson-encoder/src/tokens/comparable/nat.ts#L54)
[taquito-michelson-encoder/src/tokens/comparable/int.ts](https://github.com/ecadlabs/taquito/blob/6a4e4ab6ac59555ffa5b58dd04702b0f4cb81735/packages/taquito-michelson-encoder/src/tokens/comparable/int.ts#L56)

**Comment by roxaneletourneau** [comment]
Thank you @dexterslabor for submitting this issue and the solution using .toFixed().
