### ISSUE TITLE
Create sample app and documentation for usage of tickets

### ISSUE THREAD

**Issue by Innkst** [ecadlabs/taquito#646]
- [ ] publication describes how tickets can be read from the storage and bigmap, that tickets can be used as parameters when smart contract entry points are invoked.
   - atm we are working on article for LIGO tickets and we can include a snippet for "How to read tickets with Taquito"

**Comment by jevonearth** [comment]
blocked by #686

**Comment by Innkst** [comment]
possible resolved in #727

**Comment by claudebarde** [comment]
Documentation is available here: https://medium.com/ecad-labs-inc/how-to-use-tickets-with-ligo-e773422644b7
Dapp using tickets is a WIP.

**Comment by claudebarde** [comment]
Closing the issue as the dapp and article were published last week: https://medium.com/ecad-labs-inc/how-to-build-your-first-tezos-dapp-2021-edition-b1263b4ba016
