### ISSUE TITLE
Link for "Share a link to this contract" on Taquito Metadata Explorer does nothing

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taquito#662]
On the Taquito Metadata Explorer (https://taquito-metadata-explorer.netlify.app)  there is a link with the name: Share a link to this contract

but clicking the link does nothing and there is no error message.

**Steps To Reproduce**
1. Go to https://taquito-metadata-explorer.netlify.app.'
2. Click on 'Share a link to this contract'
3. nothing happens

**Expected behavior**
When the link is clicked it should either go somewhere or issue an error message.

**Comment by claudebarde** [comment]
The `Share a link to this contract` thingy copies a link to the contract in your clipboard. If you open a new tab and press CTRL+V, you will see it.
An animation of some sort may make the process more self-explanatory but I considered it more cosmetic than useful as the website is supposed to be used only internally. It can be added though if necessary.

**Comment by Innkst** [comment]
"Copy this contract" or "Copy to clipboard" or the copy icon would be more self-explanatory.
This issue doesn't belong to Taquito, so closing.
