### ISSUE TITLE
Integrate the taquito-test-dapp into the Taquito pipeline

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taquito#663]
**Is your feature request related to a problem and use case? Please describe.**

The taquito-test-dapp is for testing that dapp / wallet interactions work well using Taquito/Beacon. The taquito-test-dapp needs to be updated from Taquito releases or pre-releases, which is labor intensive.

**Describe the solution you'd like**

- Move the https://github.com/ecadlabs/taquito-test-dapp into the Taquito git repository.
- On PR's, when the Taquito website gets deployed to a preview build, the taquito-test-dapp should also be built and published. They should be built separately, a failing build should not impact the other.

## Acceptance criteria

When a PR is created, CI creates a website preview such as `https://9f5eb399--tezostaquito.netlify.app`. The following criteria will use this URL as an example.

- Project should be located under `apps/taquito-test-dapp`
- Project must be marked as private so that it does not publish to NPM
- The taquito-test-dapp must be built against the local taquito code base (not npm packages) so that its functions rely on the taquito code in the same branch.
- Thetaquito-test-dapp must be published to `https://9f5eb399--tezostaquito.netlify.app/taquito-test-dapp`.
- When the PR is merged to master, the website will build, and the test dapp will publish to https://tezostaquito.io/taquito-test-dapp`.

**Comment by michaelkernaghan** [comment]
We will want the test app to show the version of Taquito code it is running
