### ISSUE TITLE
Use local packData implementation to encode bigmap keys

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taquito#667]
**Is your feature request related to a problem and use case? Please describe.**

Fetching big map values is slow because Taquito needs to also pack the key value using the `rpc.packData()` method. See [here](https://github.com/ecadlabs/taquito/blob/master/packages/taquito/src/contract/rpc-contract-provider.ts#L103)

**Describe the solution you'd like**

Allow the `getBigMapKeyByID` to use the new michel-codec `packData` implementation.

**Describe alternatives you've considered**

**Additional context**

As `packData` implementation is new. We can consider making this user-configurable. So the Taquito user can opt to rely on the local `packData` impl, or the RPC version. This option is not without cost, as maintaining, testing and documenting two paths is considerable.

**Comment by Innkst** [comment]
blocked by #613

**Comment by jevonearth** [comment]
Related to #607
