### ISSUE TITLE
In Taquito Docs remove the warning that Lamba views are pre-release

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taquito#674]
The Taquito docs page for lambda view has a warning that Lamba views are pre-release - this warning should be removed

1. Go to https://tezostaquito.io/docs/lambda_view/
2. The warning about pre-release should be removed

**Comment by roxaneletourneau** [comment]
At the same time, move the note saying that a signer needs to be configured at the top of the page.
