### ISSUE TITLE
Make a utility to manage contracts  used in tests when there are Tezos Protocol changes

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taquito#675]
Make a utility that we can run against a sandbox or new testnet that originates all contracts we rely on and puts the addresses in a file, which we can then update Taquito and the website with somehow.

There are the addresses listed here: 
https://github.com/ecadlabs/taquito/blob/master/integration-tests/config.ts#L21
And also the lambdaview contract, and there might be some others.

And there are the contracts listed for Taquito Docs Live Code Examples here :
https://docs.google.com/spreadsheets/d/1-mifIF1LNZUJ_etpFcSsYx2yaZT0anz_AeDrrmfCLAI/edit?usp=sharing

**Comment by Innkst** [comment]
related to #457

**Comment by jevonearth** [comment]
The following scripts now exist to do this:
```
examples/deploy-integration-tests-contracts.ts
examples/deploy-lambda-contract.ts
```
