### ISSUE TITLE
e2e tests suite

### ISSUE THREAD

**Issue by carte7000** [ecadlabs/taquito#68]
At the moment, we are mostly doing unit tests against each part of tezos-ts. We want a way to test the library functionalities against real nodes and in an automated way.

Ideally, we would only use the public API of our packages to implement those tests.

- [x] Add a new e2e tests project that will depend on each package and only use the public API to do the tests
- [ ] Add job on CI to run this new tests suite (trigger should be on PR or tags)

**Comment by jevonearth** [comment]
Partially done, need to solve running the integration tests in CI so they don't time out. May consider using Granary for a private testnet integration target.
