### ISSUE TITLE
Adding DI to HttpBackend

### ISSUE THREAD

**Issue by progital** [ecadlabs/taquito#69]
We want to mock `HttpRequest` for our tests. So lets add an optional constructor argument - "creator" function. If it's defined then `createXHR` method returns its result.

**Comment by jevonearth** [comment]
I think we made the HTTP client injectable since this Issue was opened, but I'm not 100% sure. Needs verification.

The cost of mocking requests for testing purposes may be higher than doing integration tests against a real node.

**Comment by michaelkernaghan** [comment]
yes the http cient is now injectable:

is the HTTP client in Taquito  injectable ?

Yes, the HTTP client in Taquito is injectable. Taquito is a TypeScript library for building ÐApps on the Tezos blockchain, and it allows you to customize and inject your own HTTP client. This feature is useful for developers who want to use a specific HTTP client or implement custom logic for handling network requests.

To inject your own HTTP client, you need to implement the `RpcClient` interface provided by Taquito. This interface defines the methods that your custom HTTP client should have. Once you have implemented the `RpcClient` interface, you can pass your custom HTTP client instance to the `RpcProvider` or `TezosToolkit` constructor.

Here's an example of how to inject a custom HTTP client:

```typescript
import { TezosToolkit, RpcClient, RpcProvider } from '@taquito/taquito';

class MyCustomHttpClient implements RpcClient {
  // Implement required methods from RpcClient interface
  // ...
}

const customHttpClient = new MyCustomHttpClient();
const rpcProvider = new RpcProvider(customHttpClient);
const tezos = new TezosToolkit(rpcProvider);
```

By injecting your custom HTTP client, you can control how Taquito interacts with the Tezos RPC and customize the behavior as per your requirements.
