### ISSUE TITLE
Remove delphinet specific integration tests 

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taquito#690]
- [x] Remove deliphnet from github workflows
- [x] Remove delphinet specific integration tests
- [x] Remove delphinet references from website

**Comment by michaelkernaghan** [comment]
before :  Remove delphinet specific integration tests   -  ensure there is an edonet version

**Comment by michaelkernaghan** [comment]
Link this issue with Remove support and operations for Babylon #485

link  #485

**Comment by michaelkernaghan** [comment]
I have removed delphinet, carthagenet, and babylonnet specific integration tests

**Comment by michaelkernaghan** [comment]
I have cleaned up the old protocol references on the web site (Taquito docs)

**Comment by michaelkernaghan** [comment]
There is a tutorial using Delphunet on the michelson.md page.
I am making a separate issue for this as it requires making sure the tutorial still works and may mean creating new accounts and contracts.

**Comment by michaelkernaghan** [comment]
There is also issue:  Taquito Docs upgrade guide page needs to be updated from V7 to V8 #673
