### ISSUE TITLE
Update code examples on Taquito Docs where Thanos is used to temple instead.

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taquito#698]
In Taquito docs, there are examples of Thanos wallet that need to be updated to use the new name Temple wallets.

This includes live code examples and the packages and dependencies.

After any changes the I've code examples need to work in the live site.

**Steps To Reproduce**
1. Go to https://tezostaquito.io/docs/wallet_API
2. Scroll down to the live code example under "Try the Thanos wallet!" (or now it is "Try the Temple wallet!)
3.  the line "   const wallet = new ThanosWallet('MyAwesomeDapp');"  will need to change and accompanying code and deployment changes needed to make that live code example work with TempleWallet

**Expected behavior**
The live code examples refer to Temple instead of Thanos

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Innkst** [comment]
It has been updated
