### ISSUE TITLE
Taquito unit tests RPC calls need review and update for deprecated calls

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taquito#703]
Florence doesn't include Backing Accounts anymore. This is no longer relevant.

**Description**
The `packages/taquito-rpc/test/taquito-rpc.spec.ts` test suite has tests that verify that mock client calls for RPC return the correct Tezos RPC call

Since these tests are mocks they will not fail when a Tezos RPC call is deprecated.  A review of the unit tests to update the RPC calls to be tested should be done, as there are 14 deprecated calls coming for Florence. : https://tezos.gitlab.io/009/rpc.html#rpcs-full-description

**Steps To Reproduce**
1. Go to `packages/taquito-rpc/test/taquito-rpc.spec.ts` in Taquito codebase
2. Observe the test   `describe('getDelegate', () => {`
3. The test calls `client.getDelegate('address')` and verifies a mock response matches the required Tezos CLI call
`tezos-client get /chains/main/blocks/head/context/contracts/address' .  
4. If you try that tezos cli command it will fail. But the mock does know it will fail ...
5. compare the test `describe('getBlockHash', () => {` which looks for   `Method: 'GET',  url: root/chains/test/blocks/head/hash',`
6. '`tezos-client rpc get /chains/main/blocks/head/hash`' works
(test | main depending)

**Expected behavior**
The mocks in the unit test should be matched with current RPC calls

**Comment by Innkst** [comment]
Florence doesn't include Backing Accounts anymore. This is no longer relevant.
