### ISSUE TITLE
SPIKE: GetOperation from Indexers

### ISSUE THREAD

**Issue by Innkst** [ecadlabs/taquito#705]
**As a Taquito user that has an Operation Hash I want an API that I can use to fetch the Operation so that I can inspect the contents and status of that Operation**

## Background

The Tezos RPC node does not offer the ability to fetch an operation by operation hash (May be inplemented in future see [Tezos Issue 1131](https://gitlab.com/tezos/tezos/-/issues/1131#note_515836272)).

Note, this is a spike, aka a prototype of implementation

**Acceptance criteria:**
- Each of the below operation can be retrieved by hash using API for each of the indexers:
   - https://tezgraph.com/ 
   - https://api.tzkt.io/#tag/Operations
   - https://tzstats.com/docs/api/index.html
   - https://better-call.dev/docs
- Document operation properties available by each indexer api for each kind of operation, i.e. name, type, format and description.
- Propose a generalized list of properties based on the above discovery: name, type, format(i.e. unixepoch vs. UTC, etc.) and description
- Define TypeScript type definitions for the generalized properties for operations.

# Examples (mainnet)
**Transaction**
https://tzstats.com/oogJQZM1bHNSzJ6egr6dAFweERUTmJLTjR7Nf9XbNrjMkQbddSs/39721104
A transaction transferring 1 XTZ token from one implicit account to another

**Batch Operation w/ Delegation and Reveal**
https://tzstats.com/onwbonv722FrR2m8isDPgCz4XzSmkC4oaQEHcFsYw3SLiPgKE7y
A batch operation with a delegation operation and a reveal operation.

**Endorsement**
https://tzstats.com/ooiS1StmuxRTs6nVYM7kUgWCwVH5FKup1Rq1UGXkwcpY98RyLAK
This is an endorsement operation.

**Batch Operation w/ Call and Transfer**
https://tzstats.com/onsZtZR1xWQ3Un8zpJUadaTRbxJfMjaL343TdZQg3zbPYvJXU8Q/39938569
This operation has two items. A contract call, and a transfer of 0.005 XTZ tokens from an originated account (KT1) to an implicit account (TZ1).

**Batch with reveal and contract origination**
https://tzstats.com/ooQfLJHv9k5upzZ8JKsXh8X2Cdef9FCur6Fz4ytFMkomo8mgzS7
This has operation has two items in its batch. A Public Key Reveal and a "New delegator" contract (an origination).

**activate_account**
https://api.tzstats.com/explorer/op/ooXr5mXN7tvMXJ6TLRrbvugP6LAQ9LNuYEu4WffcAmpB6jQXSd6

**double_baking_evidence**
https://api.tzstats.com/explorer/op/ooofziA3QbNVB3p7cEEAtYDVS8nQpeGPSMSJfqkJnbBWpk4G3sc

**double_endorsement_evidence**
https://api.tzstats.com/explorer/op/ooxzQzgXJwmN2JauYvFAaLvvKPp5D8ioE8nBysj6aChQSiNuekb

**proposals**
https://api.tzstats.com/explorer/op/onkZMtPcLbLQRfDfUpZC3UgiddNVaUYMdmdVFNEeWd5A1YoJHNR

**ballot**
https://api.tzstats.com/explorer/op/ooy6d9GH6xCw6ue9uTXERxw8gLNKj6F1LgXWhEb44o5WcRsRALw

**seed_nonce_revelation**
https://api.tzstats.com/explorer/op/op6mK17FpYUH931bTXZQQcac17FUjiUaAFo3nmYXGGfYATVKoZH

**Comment by roxaneletourneau** [comment]
Findings added to the notion page `Taquito indexer package` for this spike

**Comment by Innkst** [comment]
tzKT API was changed recently and we want to review it. We will review it before starting the actual implementation.
