### ISSUE TITLE
Update the tutorial example on Taquito Docs michelson.md page to use edonet.

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taquito#719]
**Description**
on docs/michelsonmap.md there is a tutorial set up for use with delphinet. this should be converted to use with edonet.
This may require creating a new contract on edonet and ensuring the tutorial works.

**Steps To Reproduce**
1. Go to https://tezostaquito.io/docs/michelsonmap
2. Observe a little way down the page: "This tutorial uses a simple smart contract deployed on Delphinet with a map"
3. The tutorial and its references and assets need to be changed to work with edonet.

**Comment by claudebarde** [comment]
I edited the article and created a pull request => https://github.com/ecadlabs/taquito/pull/757
