### ISSUE TITLE
Document how to enable local pack for Big Maps on website 

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taquito#726]
Update the https://github.com/ecadlabs/taquito/blob/de6e34ab8ce2ec51c0ec29b4b8ddd67ce1734ee6/docs/maps_bigmaps.md

page with instructions on how to enable local pack for big maps, and the benefits of doing so.

See draft release notes on #712

**Comment by claudebarde** [comment]
See https://github.com/ecadlabs/taquito/pull/727
