### ISSUE TITLE
Error: this.rpc.getBalance is not a function

### ISSUE THREAD

**Issue by oscamacho** [ecadlabs/taquito#730]
call **Tezos.tz.getBalance(address)** reports an error that does not allow to be displayed the balance for any address provided.
instead it shows the wording **this.rpc.getBalance is not a function**... i go to see the docs but i don't understand where the problem is

**Comment by Innkst** [comment]
see also https://tezos.stackexchange.com/questions/3296/this-rpc-getbalance-is-not-a-function

**Comment by Innkst** [comment]
This is a Javascript error and once TezosToolkit is initialized, this error shouldn't happen.
Closing this ticket, but please let us know if this is still an issue.
