### ISSUE TITLE
Verify that `@see` URLs in the RPC package point to the correct RPC documentation.

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taquito#731]
In `packages/taquito-rpc/src/taquito-rpc.ts` we have RPC client functions that map 1:1 to RPC endpoints in the Tezos node.

In the TypeDoc comment, we list the `@see` annotation that links to the corresponding RPC endpoint documentation.

Verify if:

- [x] All RPC client functions have a `@see` URL
- [x] Each URL should point to `https://tezos.gitlab.io/api/rpc.html#someanchor` so the protocol version is not in the URL like ``https://tezos.gitlab.io/008/rpc.html#someanchor` 
- [x] List RPC methods that do not have a corresponding rpc client method
- [x] Each URL should point to the correct and corresponding RPC (See PR #729 that corrected some incorrect links)

**Comment by michaelkernaghan** [comment]
I have cross references the tests with the specs here:
https://docs.google.com/spreadsheets/d/1_2Bs3hyJsDeDJzOegSJg3orE_ralbUacNY9PVQxHLQ4/edit?usp=sharing

**Comment by jevonearth** [comment]
@michaelkernaghan Report looks good. Did you verify that each URL in the `@see` properties leads to the appropriate link and anchor?

**Comment by michaelkernaghan** [comment]
I verified that each URL goes to the appropriate https://tezos.gitlab.io/008/rpc.html#get-block-id, for example
so yes, that would be link and anchor, yes :)

**Comment by michaelkernaghan** [comment]
I think this can be closed. Similar work can be carried on in #732

**Comment by michaelkernaghan** [comment]
to complete:  Each URL should point to https://tezos.gitlab.io/api/rpc.html#someanchor so the protocol version is not in the URL like ``https://tezos.gitlab.io/008/rpc.html#someanchor`
there is one link that requires repair:   

https://tezos.gitlab.io/007/rpc.html#post-block-id-helpers-scripts-run-code
should be
https://tezos.gitlab.io/api/rpc.html#post-block-id-helpers-scripts-run-code

**Comment by michaelkernaghan** [comment]
What remains for this issue can be completed in #732 and this one can be closed.
