### ISSUE TITLE
Inventory RPC client methods against RPC server and list RPC endpoints that are not supported

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taquito#732]
The `@taquito/rpc` package implements client functions that correspond to Tezos RPC's. 

Create a document/table of RPCs indicating which ones are implemented or missing.

Use the following RPC documentation as reference:

- https://tezos.gitlab.io/shell/rpc.html
- https://tezos.gitlab.io/008/rpc.html

The resulting list will be used to prioritise what RPC methods need to be added.

**Comment by michaelkernaghan** [comment]
The list is available at https://docs.google.com/spreadsheets/d/1_2Bs3hyJsDeDJzOegSJg3orE_ralbUacNY9PVQxHLQ4/edit#gid=0

**Comment by michaelkernaghan** [comment]
I have updated the spreadsheet for Granada.

**Comment by michaelkernaghan** [comment]
this has been completed
