### ISSUE TITLE
Add the telegram group to the community links in the https://tezostaquito.io/ footer

### ISSUE THREAD

**Issue by paulo60pg** [ecadlabs/taquito#746]
This would help builders to communicate and find answers there.
Right now the group is quite hard to find.

**Acceptance criteria:**
- Add "Telegram" link to the footer of the website at https://tezostaquito.io/ following "Stack Exchange":
   -  link to https://t.me/tezostaquito

**Comment by michaelkernaghan** [comment]
added the link
