### ISSUE TITLE
When connecting to Kukai use the right network

### ISSUE THREAD

**Issue by murbard** [ecadlabs/taquito#753]
> the beacon DAppClient contructor you should set an explicit preferredNetwork of edonet, the default is mainnet so currently if you select Kukai it sends you to mainnet Kukai
> 
> preferredNetwork: NetworkType.EDONET should be added to the contructor options when an app is for testing on edonet, note that this can't be overriden by requests once ininitalized, the network setting during requests must match it

See https://github.com/murbard/ctez/issues/13

**Comment by claudebarde** [comment]
The documentation has been updated to inform users about the `preferredNetwork` property when wanting to use Kukai on testnet (see pull request https://github.com/ecadlabs/taquito/pull/757)

**Comment by roxaneletourneau** [comment]
Closing the issue as it is now documented here: https://tezostaquito.io/docs/wallet_api/#--tzip-10-wallet
