### ISSUE TITLE
SPIKE: determine the API endpoints used by Open Minter

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taquito#754]
Compile a list of the endpoints that the OpenMinter app is hitting with response times.

https://edonet.test.niftyminter.io/

on edonet

use BDC etc to see what is at the endpoints if necessary

Are they bigMaps?

**Comment by michaelkernaghan** [comment]
There seem to be only one endpoint that hits a contact or other node element:

https://edonet.test.niftyminter.io/collection/KT1Hagc5XQYzkX7HfRbUNXdi4CBfiENzbHiU/token/89

This contract has storage:

'''
storage pair
assets $assets
metadata big_map(string, bytes)
assets pair
ledger big_map(nat, address)
next_token_id nat
operators $operators
token_metadata $token_metadata
operators big_map
key $operators_key
value unit
operators_key pair
address
address
nat
token_metadata big_map
key nat
value $token_metadata_value
token_metadata_value pair
token_id nat
token_info map(string, bytes)
'''

**Comment by michaelkernaghan** [comment]
![image](https://user-images.githubusercontent.com/78441942/112881142-2ec7ed00-9080-11eb-938b-8ab55dd6c0aa.png)

**Comment by jacobarluck** [comment]
Hey there. I think you may be on an older version of minter. Check out 0.5.0

**Comment by michaelkernaghan** [comment]
ok
thanks

**Comment by michaelkernaghan** [comment]
open minter touches indexers a lot but does not make direct calls to nodes

**Comment by michaelkernaghan** [comment]
Each time you click to view an NFT in the marketplace the app loads all the bigMaps for all the other NFTs in the marketplace.

**Comment by jevonearth** [comment]
Thanks for the info Michael. Closing this issue.
