### ISSUE TITLE
Estimate for reveal operation are not returned on batch estimation

### ISSUE THREAD

**Issue by roxaneletourneau** [ecadlabs/taquito#772]
**Description**
The implicit reveal data are not returned when doing estimation on batched operations.
For example, during a batch with two transfers, the estimate array returned only contains my two transfers estimation when there should be also a reveal estimation.

**Steps To Reproduce**
Using an unrevealed account, the following code:
```
const batch = await Tezos.estimate
    .batch([
        {
            kind: OpKind.TRANSACTION,
            to: 'tz1ZfrERcALBwmAqwonRXYVQBDT9BjNjBHJu',
            amount: 1
        },
        {
            kind: OpKind.TRANSACTION,
            to: 'tz1ZfrERcALBwmAqwonRXYVQBDT9BjNjBHJu',
            amount: 1
        }
    ])

console.log(batch)
```
returns:
```
[
      Estimate {
        _milligasLimit: 1427000,
        _storageLimit: 0,
        opSize: 106,
        minimalFeePerStorageByteMutez: 250,
        baseFeeMutez: 100
      },
      Estimate {
        _milligasLimit: 1427000,
        _storageLimit: 0,
        opSize: 106,
        minimalFeePerStorageByteMutez: 250,
        baseFeeMutez: 100
      }
    ]
```
**Expected behavior**
It should also return an estimate for the reveal operation.

**Additional context**
The reveal estimation should be included in the array but it gets removed by this line of code: https://github.com/ecadlabs/taquito/blob/master/packages/taquito/src/contract/rpc-estimate-provider.ts#L133.

**Comment by remyzorg** [comment]
It could be a could idea to add some details over the estimated operation, using the opKind, to be able to filter.

**Comment by roxaneletourneau** [comment]
@remyzorg at Now, an array of estimate objects is returned where the first estimate matches the first operation of the batch, and so on.
I added an optional parameter that can be set to true, if we want to include an estimate for the reveal operation when needed. This estimate will be the first one of the returned array.

example:
```
const batchOpEstimate = await Tezos.estimate
                .batch([
                    { kind: OpKind.DELEGATION, source: await Tezos.signer.publicKeyHash(), delegate: knownBaker },
                    { kind: OpKind.TRANSACTION, to: 'tz1ZfrERcALBwmAqwonRXYVQBDT9BjNjBHJu', amount: 2 },
                ], { includeRevealOperation:true })
```
The returned array of estimates does not include the opKind, so I am unclear on your proposition. Do the parameter I added will suit your need, or could you give an example of the solution you have in mind, please?
