### ISSUE TITLE
USER STORY: Get operation base on hash using TezGraph as an indexer

### ISSUE THREAD

**Issue by Innkst** [ecadlabs/taquito#775]
**As a Taquito user that has an Operation Hash I want an API that I can use to fetch the Operation so that I can inspect the contents and status of that Operation**

**Background**
The Tezos RPC node does not offer the ability to fetch an operation by operation hash (May be implemented in the future see [Tezos Issue 1131](https://gitlab.com/tezos/tezos/-/issues/1131#note_515836272)).

**Acceptance criteria:**
- Any operation (see examples in https://github.com/ecadlabs/taquito/issues/705) can be retrieved by hash using API for each of the indexers:
   - https://tezgraph.com/ 

- Support all operations where available for TezGraph(more indexers will be added in issues https://github.com/ecadlabs/taquito/issues/776 and https://github.com/ecadlabs/taquito/issues/777)
   - origination (o)
   - delegation (d)
   - reveal (r)
   - transaction (t)
   - ~activate_account (a)~
   - endorsement (e)
   - ~seed_nonce_revelation (s)~
   - ~double_endorsement_evidence (de)~
   - ~double_baking_evidence (db)~
   - ~proposals (p)~
   - ~ballot (b)~
 - Return the following common fields 
   - hash
   - kind
   - block
   - timestamp
   - level
   - source
  - Return fields specific to each operation:
     - https://www.notion.so/ecad/TODO-Taquito-indexer-package-7c806acc2f3d460f902935cdac4eb996#27ee96cf883843a4a9d988470a5a7434

   

**Non-functional:**
- Extendable design: More Indexers, more generalized fields could be added in the future
- consider performance, scalability, security

OUT OF SCOPE:
   - https://api.tzkt.io/#tag/Operations
   - https://tzstats.com/docs/api/index.html

**Additional context**
Note, the spike was done in https://github.com/ecadlabs/taquito/issues/705
Documented https://www.notion.so/ecad/TODO-Taquito-indexer-package-7c806acc2f3d460f902935cdac4eb996#7ef66c8ee8fd4044a444ce771a8120b2

**Comment by michaelkernaghan** [comment]
tezgraph is no longer maintained.
