### ISSUE TITLE
Export BeaconWallet types/enums

### ISSUE THREAD

**Issue by w4ll3** [ecadlabs/taquito#778]
**Is your feature request related to a problem and use case? Please describe.**
A clear and concise description of what the problem/use case is. 
When using Typescript having no access to the types/enums makes pretty hard to code, since there are a lot of types than doesn't overlap.

**Describe the solution you'd like**
Make it possible to import types/enums.

**Describe alternatives you've considered**
Disabling Typescript.
Which solution worked? What didn't work?
Disabling Typescript.

**Comment by roxaneletourneau** [comment]
Hi, are you referring to the Network enum? Are there other specific types you would like us to export?

**Comment by w4ll3** [comment]
The Network is one of them, another one is the BeaconWalletEvents, which we use to listen to some events

**Comment by claudebarde** [comment]
I am not sure of the value it brings to reexport these types through the `BeaconWallet` package. Because the package wraps the Beacon SDK, you have access to the types by importing them directly from the beacon-sdk library without having to install it manually:
```
import { NetworkType, BeaconEvent, defaultEventCallbacks } from "@airgap/beacon-sdk";
```

**Comment by michaelkernaghan** [comment]
closing as "Will not fix". also closing Re-export types from @airgap/beacon-sdk #808 which is the same.
