### ISSUE TITLE
Repair Taquito website issues identified by MOZ

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taquito#780]
**Description**
MOZ webcrawler is reporting issues with the Taquito website. These should be repaired.

**Steps To Reproduce**
1. Go to the MOZ report at https://analytics.moz.com/pro/analytics/crawl/issues/overview/14073325/2423301?utm_source=campaign_emails
2. Review the 643 or so issues and repair them

Most of the issues are "description too short". This is because every page in the  typedoc dir has 
meta name="description" content="Documentation for Taquito

Description Too Short
What it is:
Your meta description is too short. The meta description provides the content that appears directly below the title tag on the SERP and encourages searchers to click. Learn more about meta descriptions.
Why it's an issue:
When your meta description is too short, your click-through rate may suffer.
How to fix it:
Britney says: “Update your meta description to the ideal length of 55-300 characters.”

perhaps this change can be made in one go for all pages.
maybe change it to
"The @taquito/taquito package contains higher-level functionality that builds upon the other packages in the Tezos Typescript Library Suite."

**Expected behavior**
The number of issues found by MOZ should be decreased

**Comment by michaelkernaghan** [comment]
related to #622

**Comment by michaelkernaghan** [comment]
Does anyone know how typedoc generates the Description field on the web pages and how you can change what Description it creates?  for example the last line in this file (edited) 

Michael Kernaghan  9:12 AM
<!doctype html>
<html class="default no-js">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{{#ifCond model.name '==' project.name}}{{project.name}}{{else}}{{model.name}} | {{project.name}}{{/ifCond}}</title>
    <meta name="description" content="Documentation for {{project.name}}">

**Comment by michaelkernaghan** [comment]
If we can change the one source for the description metadata field it can repair MOZ complaint for 200 files in one go.

**Comment by jevonearth** [comment]
We reported this issue to typedoc sometime back here:
https://github.com/TypeStrong/typedoc/issues/1211

Unfortunatley the fix they made just puts the tag as `<meta name="description" content="Documentation for {{project.name}}">` where we want to describe the actual package with prose.

**Comment by michaelkernaghan** [comment]
In that case, I vote for setting MOZ to ignore "description too short".

**Comment by michaelkernaghan** [comment]
not useful for anything other than google search placement so closing.
