### ISSUE TITLE
michelson-encoder / michel-codec alignment/replacment.

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taquito#784]
**As a developer user, I would like to have a tool that provides type checking based on the Michelson smart contract so that I benefit from compile-time type safety.**

Types will be generated based on a contract type with methods and storage. Generics will be added to the TezosToolkit to carry the types to the right places and then provides type checking.

This package (named "taquito-contract-type-generator") should:

- Make discovery of how to structure data for entrypoints and initial storage easy for new users (Presently possible via SchemaExtract but not well known)

We anticipate either break the existing "contract" (misnomer) & Wallet API when implementing #432. We plan to use the new taquito-contract-type-generator functionality in the new [version of the] API outlined in #432  

**Acceptance Criteria**
- The following use cases are to be supported:
   - Given a Smart Contract, generate a TypeScript type that aligns with the Michelson Type definition of the Contracts storage
   - Given a smart Contract, generate TypeScript types for the parameters of each to the Contracts entry points

**Comment by Innkst** [comment]
validation was split out into a separate issue #1017

**Comment by Innkst** [comment]
This tool will be implemented separately from Taquito.
