### ISSUE TITLE
Cannot read property 'DAppClient' of undefined

### ISSUE THREAD

**Issue by pinpong** [ecadlabs/taquito#787]
Hello,

i wrote  small example with flutter.
http://pinpong.eu/taquitoExample/#/

I've added the packages to the index.html:

```js
  <script src="https://unpkg.com/@airgap/beacon-sdk@2.2.3/dist/walletbeacon.min.js">
  </script>
  <script src="https://unpkg.com/@taquito/beacon-wallet@8.1.0/dist/taquito-beacon-wallet.umd.js">
  </script>
  <script src="https://unpkg.com/@taquito/taquito@8.1.0/dist/taquito.min.js">
  </script>
```

Press the connect button from example page to get the error:

```
TypeError: Cannot read property 'DAppClient' of undefined
    at new BeaconWallet (taquito-beacon-wallet.ts:41)
```

The beacon sdk connection works standalone with Temple Wallet.
All packages injected, check the example.

**Comment by jevonearth** [comment]
Hello @pinpong 

Can you publish a small git project so that we can reproduce this problem? We don't, at this time test Taquito in a flutter context.

**Comment by pinpong** [comment]
@jevonearth here is the example:

https://github.com/pinpong/flutter_taquito_example

**Comment by pinpong** [comment]
After spending lot of time i found the issue.

https://unpkg.com/@taquito/beacon-wallet@8.1.0/dist/taquito-beacon-wallet.umd.js

```js
factory(global.taquitoBeaconWallet = {}, global.beaconSdk, global.taquito)
```

should
```js
factory(global.taquitoBeaconWallet = {}, global.beacon, global.taquito)
```

Thats the problem and not flutter related issue.

**Comment by Shoxc** [comment]
Good spot @pinpong.
Should really be getting fixed as it’s annoying af

**Comment by jevonearth** [comment]
Is there something here for us to fix? We don't have the bandwidth to test within a Flutter context. 

Thank you.

**Comment by Shoxc** [comment]
This problem occurs with any project that isn’t using npm .

**Comment by claudebarde** [comment]
The issue has been reproduced in this very simple JavaScript-based app: https://github.com/claudebarde/frameworkless-dapp
