### ISSUE TITLE
Draggable warning

### ISSUE THREAD

**Issue by ungarson** [ecadlabs/taquito#796]
Is it possible to make this warning draggable? Sometimes it hides the information that I need.
Or maybe closeable by swiping to right: look at the macos notifications as an example.

<img width="505" alt="Screenshot 2021-04-19 at 18 15 31" src="https://user-images.githubusercontent.com/13982759/115260343-566c1b80-a13b-11eb-89d7-c5203bcb50e0.png">

**Comment by jevonearth** [comment]
This dialog overlay comes from beacon. You can override all those and place them/present them however you prefer.

If they were to be made drag-able, that would be a feature request for https://github.com/airgap-it/beacon-sdk 

Could you open a feature request with them? Closing for now, but feel free to reopen if you think there's more Taquito can do in this regard.
