### ISSUE TITLE
Create a Taquito FAQ page

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taquito#800]
Create a FAQ page for the Taquito website.

Add common questions, and make sure that common errors are written in a way that is searchable/find-able using google/other search engines.

Each question should be linkable directly.

**Comment by Innkst** [comment]
If we have top 5 questions asked by all/most of the users, let's start adding them in the comment.
If the question was only asked ones, it doesn't make sense to add here.

**Comment by jevonearth** [comment]
What @Innkst said :)

I posted a common question, along with a (self-answered) answer here: https://github.com/ecadlabs/taquito/discussions/826

Closing this issue for now.

**Comment by claudebarde** [comment]
Here are some questions that appear from time to time and that may be worth documenting:
- How to format the parameters properly in Taquito to send a transaction to the `transfer` entrypoint of an FA2 contract?
- How to get all the key/value pairs of a big map with Taquito?
- GET error when fetching a big map value with its key (normal 404 error from the node)
