### ISSUE TITLE
Include jest-stare test report in CICD integration test result

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taquito#804]
We would like a simple way to review and track the results of failed tests in the integration test section of the CICD.

The CICD system at the moment is less efficient than it should be because of a high number of flaky tests.

The jest stare report will make it easier to identify patterns in these failures and help us to improve the CICD effectiveness.

the report is present in the package.json in the integration tests folder.
it just needs to be active and viewable within the CICD context.

**Comment by jevonearth** [comment]
We should be able to do this one of two ways;

- Save the report as a build artefact (Simple on Gitlab CI, I have not done this with Github Actions, would be surprised if it is difficult)
- Publish the jest-stare output along with the website preview. Example `https://36b9e009--tezostaquito.netlify.app/jest-stare`

**Comment by michaelkernaghan** [comment]
Not required
