### ISSUE TITLE
Update Taquito website to use Florencenet

### ISSUE THREAD

**Issue by roxaneletourneau** [ecadlabs/taquito#822]
The live code examples are using edonet. We need to update the website to use florencenet. 
For live code examples that make calls to a smart contract, we need to deploy a similar contract on Florencenet and replace the address in the examples.

Deploying all the contracts used in the examples is quite time-consuming.
It is a good occasion to find how we can make this task more efficient.

**Comment by michaelkernaghan** [comment]
Document for tracking the changes:

https://docs.google.com/document/d/15rfuo70GkMHiKV_ChrRUbLcxOUo7S6hegQ4pzX21WlQ/edit?usp=sharing
