### ISSUE TITLE
Examples in Metadata Explorer are not working with current nodes

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taquito#823]
in Metadata Explorer  I can't get any of the examples to work. they either 404 because on the wrong node, or there is an error retrieving them if the node is right./

**Steps To Reproduce**
1. Go to 'https://taquito-metadata-explorer.netlify.app/'
2. Select Florencenet and Click on examples
3. The examples either get 404 because they are not on florencenet, or they get an error.

**Expected behavior**
Examples should work

**Additional context**

**Comment by Innkst** [comment]
to be moved to metadata-explorer repo

**Comment by jevonearth** [comment]
@michaelkernaghan can you re-create this issue on this project: https://github.com/claudebarde/taquito-metadata-explorer

And close this issue. Thanks.

**Comment by michaelkernaghan** [comment]
transferred the issue to : https://github.com/claudebarde/taquito-metadata-explorer
