### ISSUE TITLE
Support endorsement with slot in Taquito@9 for Florence

### ISSUE THREAD

**Issue by dfalling** [ecadlabs/taquito#824]
**Description**
The recent 9.0.0 release is missing some necessary type changes for [Florence's endorsement operations](https://tezos.gitlab.io/protocols/009_florence.html#endorsements-now-checked-in-linear-time-attention-indexers).

`block.operations[0][0]`:
Edo:
```json
{
  "kind": "endorsement",
  "level": 1448811,
  "metadata": {}
}
```

Florence:
```json
{
  "kind": "endorsement_with_slot",
  "endorsement": {
    "branch": "...",
    "operations": {
      "kind": "endorsement",
      "level": "1448811",
    "signature": "..."
  },
  "slot": 12,
  "metadata": {}
}
```

**Steps To Reproduce**
1. Create a function or variable that takes an operation contents:
```typescript
import {OperationContents, OperationContentsAndResult} from "@taquito/rpc";
let findEndorsements = (contents: (OperationContents | OperationContentsAndResult)[]) => {
    if (contents.kind === "endorsement_with_slot") {
      console.log("endorsement");
    }
};
```
2. Note that the type system warns that `endorsement_with_slot` is not a valid `kind`

**Expected behavior**
Taquito should support the new `endorsement_with_type` kind, and associated operation structure.

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - Client Node 14

**Additional context**
To view the differences in RPC responses, check out the responses from [Edo](https://mainnet-tezos.giganode.io/chains/main/blocks/head/) and [Florence](https://florence-tezos.giganode.io/chains/main/blocks/head/).

**Comment by roxaneletourneau** [comment]
A preview build has been deployed to the preview repository and can be used if the missing types are holding you up until our next release:
`npm i @taquito/rpc@9.0.0-2c9963b5--852 --registry https://npm.preview.tezostaquito.io/`

**Comment by itkach** [comment]
>  `npm i @taquito/rpc@9.0.0-2c9963b5--852 --registry https://npm.preview.tezostaquito.io/`

@roxaneletourneau not sure how to make this work... we depend on @taquito/taquito, but
