### ISSUE TITLE
Docs lacks information about a passphrase

### ISSUE THREAD

**Issue by ungarson** [ecadlabs/taquito#827]
When I try to use new InMemorySigner(key), it throws me an error saying that `Error: Encrypted key provided without a passphrase`, I guess it should be described in the docs that passphrase is required as an argument of InMemorySigner

https://tezostaquito.io/docs/quick_start#importing-a-private-key

**Comment by roxaneletourneau** [comment]
Hi @ungarson 
A passphrase is required when the key to import is encrypted. There is more specific documentation about the InMemorySigner here: https://tezostaquito.io/docs/inmemory_signer#loading-an-encrypted-private-key-with-a-passphrase
