### ISSUE TITLE
Remote Signer

### ISSUE THREAD

**Issue by crzypatchwork** [ecadlabs/taquito#845]
was wondering if it would be interesting to have a README.md with some instructions for initializing an instance of the Remote Signer: 

https://github.com/ecadlabs/taquito/tree/master/packages/taquito-remote-signer

as well possibly other instances could have such ref

**Comment by roxaneletourneau** [comment]
@michaelkernaghan as you are working on adding missing README.md files, could you address this at the same time in PR#830 ?

**Comment by michaelkernaghan** [comment]
This issue is a duplicate of issue #832 which is for having additional tech content for devs added to the READMe.md
