### ISSUE TITLE
Error: Interval must be more than 0

### ISSUE THREAD

**Issue by gretzke** [ecadlabs/taquito#862]
Since v8.1.1 a new dynamic polling interval was intoduced. Using taquito with a local development chain sets the interval to 0, which throws this Error: `Error: Interval must be more than 0`

The error occurred for me trying to originate a contract
```typescript
const contract = await this.tezos.contract
  .originate({ code, storage })
  .then((originationOperation) => originationOperation.contract());
```

setting the polling interval manually fixes this issue: 
```typescript
this.tezos.setProvider({ signer: this.signer, config: { confirmationPollingIntervalSecond: 1 } })
```

**Comment by roxaneletourneau** [comment]
@gretzke could you share what is the time_between_blocks constants of your environment?
It can be obtained by running `await tezos.rpc.getConstants()`

**Comment by gretzke** [comment]
time_between_blocks is 0. I'm using ganache-cli@6.12.1-tezos.0 btw

**Comment by roxaneletourneau** [comment]
Closing this as the issue was fixed already: when the confirmationPollingInterval is 0, a default value of 0.1 is set.
