### ISSUE TITLE
Add Scripts Folder For Deploying Contracts

### ISSUE THREAD

**Issue by robbymister** [ecadlabs/taquito#873]
**Is your feature request related to a problem and use case? Please describe.**
Some tests or updates require contracts that are updated between testnet updates. This folder should keep a list of easily modified contracts that can be deployed quickly with different testnets.

**Describe the solution you'd like**
Adds a folder that contains scripts for quickly deployable contracts.

**Comment by Innkst** [comment]
The linked pull request included the contract for BeaconDapp, but this ticket is Taquito-focused.

**Comment by michaelkernaghan** [comment]
the attached pull request was closed as the contracts to be stored are for beacon test dapp, not for taquito.

I am closing this issue, therefore.

the beaon test dapp contracts are updated for each no protocol. a directory in that app will be considered.
