### ISSUE TITLE
What is this kind of error?

### ISSUE THREAD

**Issue by vanderi2** [ecadlabs/taquito#875]
![image](https://user-images.githubusercontent.com/83936674/118704649-c1b61580-b7ed-11eb-86d5-84158f11bf60.png)

**Comment by claudebarde** [comment]
It would be helpful to have the details of the object in the `with` property. It looks like a fail error message from a smart contract.

**Comment by vanderi2** [comment]
Actually, I call this contract as always:

```Javascript
    signer.contract.at("KT1Hkg5qeNhfwpKW4fXvq7HGZB9z2EnmCCA9")
    .then(c => {
        return c.methods.collect(parseFloat(objkt_amount), parseFloat(swap_id))
            .send({ amount: parseFloat(amount), mutez: true })
    })
    .then(operation => {
        console.log("Collect operation sent.")
    })
    .catch(error => console.log(error));
```
But for some reason, it raises this error sometimes. But it works the majority of the time. But I could not find a proper explanation for why this is happening.

**Comment by claudebarde** [comment]
I need the object in the `with` property. Can you copy-paste it in a comment?

**Comment by vanderi2** [comment]
Unfortunately, I can't provide the `with` property now as that image was taken in the output of the terminal console, and the `console.log` omits the `with` property. I will log the error to a file when it happens again and paste it here.

**Comment by claudebarde** [comment]
The `with` property holds more information about what happened in the contract. This doesn't look like a problem with Taquito, it's a contract issue, but you can paste the info here and I will have a look at it :)

**Comment by vanderi2** [comment]
To be honest, I have no idea what is happening in this error message, lol
[error.txt](https://github.com/ecadlabs/taquito/files/6511647/error.txt)

**Comment by claudebarde** [comment]
The Hic et Nunc minter [contract fails on line 159](https://better-call.dev/mainnet/KT1Hkg5qeNhfwpKW4fXvq7HGZB9z2EnmCCA9/code) with the *155* error code. I wasn't able to find out what this error code relates to, I would advise you to review the parameters you pass to the entrypoint you call and if they look correct to you, to contact the team to ask about the meaning of the error code.

**Comment by vanderi2** [comment]
How do you know that the contract fails on line 159? Just asking so I can learn.

**Comment by claudebarde** [comment]
At the very bottom of the `error.txt` file you attached, you can see the `with` object I was talking about earlier:
```
"with": {
        "int": "155"
      }
```
It indicates that the contract returned an `int` with the value `155` when it failed. I just checked the Michelson code to find the place where an `int 155` is pushed before a `FAILWITH`, which is on line 159. Some contracts include details about their error codes in their metadata but I haven't been able to find it in this one, so only the developers know what the error code means :)

**Comment by vanderi2** [comment]
Thank you very much. Can you give me your address? :)

**Comment by claudebarde** [comment]
You can find me on Twitter or Telegram: @claudebarde, don't hesitate to use the [Taquito Telegram channel](https://t.me/tezostaquito) if you need a quick reply.
I am closing the issue for now.
