### ISSUE TITLE
How to display all the content from a BigMap

### ISSUE THREAD

**Issue by vivekascoder** [ecadlabs/taquito#936]
I want to display the content of a BigMap, How can i do it ? I can't find any method or way in the docs.

**Comment by claudebarde** [comment]
If by "display the content of a BigMap", you mean "all the key/pairs of a bigmap", this is not possible with Taquito at the moment. You have to use an indexer API to get that kind of information, for example, https://api.mainnet.tzkt.io/#tag/BigMaps

**Comment by vivekascoder** [comment]
Ohk,

**Comment by vivekascoder** [comment]
## [Solution]

```js
...
api.get("/v1/bigmaps/<bigmap_id>/keys").then((response) => {
      this.causes = response.data;
    });
    api.get('/v1/bigmaps/<bigmap_id>/keys').then((response) => {
      this.fundings = response.data
    })
  },
...
```

You can get the bigmap_id by getting your contract's storage.

Example
```bash
curl https://api.florencenet.tzkt.io/v1/contracts/KT1P83YxdPnoQtxaJcxz3nwjh8b24XhJB9oC/storage
```

Returns
```json
{
  "causes": 77305,
  "fundings": 77306
}
```
If my case i had two bigmaps, the result can vary according to your contract's storage.
