### ISSUE TITLE
Implement hash checksum validation functions in taquito

### ISSUE THREAD

**Issue by carte7000** [ecadlabs/taquito#95]
Validate hashes that have checksums and avoid making HTTP calls when we can determine that the parameters are invalid.

Addresses, block hashes, and so forth have a checksum. We intend to add support to validate locally. (We are currently deferring such validation to the node.) By supporting this validation within the library, we can give end-users and developers a better experience by detecting problems or input errors earlier.

Acceptance criteria:
- Implement a validation function that checks:
    - [x ] Addresses (Link to utility method here)' - Already DONE
    - [x ] Chain - Already DONE 
    - [ ] Operation Hash
    - [ ] Block Hash
    - [ ] Protocol Hash
    - [ ] ??? Do we need any other items to be added here?

ToDo:
- [ ] List all hashes that can be validated.
- [ ] Make sure each one has a method (add to the list below)
- [ ] Make sure each one has documentation

See: https://tezostaquito.io/docs/validators

**Comment by carte7000** [comment]
#211 Include checksum validation for parameter encoding but not for regular transfer/delegation/origination address

**Comment by Innkst** [comment]
Could we please have a quick check if there are any more hashes that are not listed to be validated as well - see the last acceptance criteria. thanks!
