### ISSUE TITLE
Add ability to sign and check arbitrary messages using the `failing_noop` operation to local forger

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taquito#952]
**Is your feature request related to a problem and use case? Please describe.**

Signing arbitrary data is a common activity in blockchain, but it presents risks in that a wallet, if permissive, can sign a malicious operation that is purporting to be arbitrary data.

**Describe the solution you'd like**

The `florencenet` protocol amendment introduced a new operation type called [failing_noop](https://tezos.gitlab.io/protocols/009_florence.html#new-failing-noop-operation) which is an operation type that is guaranteed to never be included in the chain.

**Acceptance criteria**
* Implement abstractions in Taquito to easily sign arbitrary data wrapped in a `failing_noop` operation.
* Implement abstractions in Taquito to easily check the signature validity of a signed `failing_noop` operation.
* Make sure it works for both contract and wallet API
* An integration tests that attempts to inject a valid `failing_noop` operation that are expected to fail
* Abstractions should be similar to already implemented RPC forger

**Describe alternatives you've considered**

Prior to this operation type, wallet developers implemented a data structure to help mitigate this risk. See: https://docs.google.com/document/d/1ZgA7mZNrWl1YZ0snzjiFw1ahyXjvWFS1GvU5-caUDCE/edit

**Additional context**

If Taquito implements the ability to sign and check data using this operation type, wallet developers are more likely to restrict the signing of arbitrary data that comes in the form of a `failing_noop` operation.

See Tezos MR https://gitlab.com/tezos/tezos/-/merge_requests/2361 for more information.

**Comment by Innkst** [comment]
We have support for this in RPC forger, but could add it to local forger and create an integration test.

**Comment by fredcy** [comment]
Near as I can tell, the local forger does not yet support the `failing_noop` operation kind. If so, could it be please be added?

**Comment by Innkst** [comment]
@fredcy would you be able to share some details on how you are using it? It will help us to understand your use case.

**Comment by Innkst** [comment]
See related request with the use case description here https://github.com/ecadlabs/taquito/issues/2507
