### ISSUE TITLE
Abortion Support e.g. AbortSignal

### ISSUE THREAD

**Issue by psmolinsky** [ecadlabs/taquito#954]
**Is your feature request related to a problem and use case? Please describe.**

If some operation is restarted for various reasons (e.g. it takes too long, something is failing) or the app is being shut down then it is useful to be able to abort the operation. So it would be nice if Taquito support some way of aborting its operations.

**Describe the solution you'd like**

Taquito supports some way of aborting its operation e.g. [AbortSignal](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal).

**Comment by Innkst** [comment]
Thank you for the input, please see https://github.com/ecadlabs/taquito/pull/512#issuecomment-864281454 on the related issue
We will consider it when designing update to the API #432
