### ISSUE TITLE
Property `status` doesn't exist on batched transaction

### ISSUE THREAD

**Issue by claudebarde** [ecadlabs/taquito#962]
When preparing a transaction with a single operation, `.send()` returns a value of type `TransactionWalletOperation ` where the `status` property is available to know the status of the transaction after confirmation.
However, when multiple operations are batched in a single transaction using the Batch API, `.send()` returns a value of type `WalletOperation ` where the `status` property is missing.

For example, when sending a single operation to a Plenty pool to harvest the rewards, this works:
```
const op = await contract.methods.GetReward([["unit"]]).send();
await op.confirmation();
const opStatus = await op.status();
```

But when batching multiple calls to the `GetReward` entrypoint, this doesn't work anymore:
```
let batch = Tezos.wallet.batch().withContractCall(contract.methods.GetReward([["unit"]])).withTransfer({
    to: admin,
    amount: Math.ceil(fee * 10 ** 6),
    mutez: true
});
let op = await batch.send();
await op.confirmation();
const opStatus = await op.status();
```
TypeScript throws an error: `Property 'status' does not exist on type 'WalletOperation'`.

**Comment by roxaneletourneau** [comment]
Update the answer to this question when ready: https://tezos.stackexchange.com/questions/3639/how-can-i-tell-if-a-walletoperation-failed-in-taquito
