### ISSUE TITLE
About @taquito/beacon-wallet (sodium.randombytes_buf is not a function...)

### ISSUE THREAD

**Issue by vdt000** [ecadlabs/taquito#966]
Hello Vedat!

Thank you for using Taquito!

Could you please post your question on our projects GitHub Discussion page here: https://github.com/ecadlabs/taquito/discussions/new

I will make sure we follow up with you there as soon as possible!

-Jev 

On Mon, Jul 5, 2021 at 1:30 PM Vedat Arslan <vdt@rocketmail.com> wrote:

    Merhaba (Hi),

    I am software eng from Turkey, Tezos team.
    We work on web app that connects users wallet.
    But when we try a simple code on node.js that we copied your documents.
    We get an error like this and we can't work around.

    TypeError: sodium.randombytes_buf is not a function
        at Object.<anonymous> (D:\Projects\bitay\NFT\NFT-tq\node_modules\@airgap\beacon-sdk\dist\cjs\utils\generate-uuid.js:72:34)
        at step (D:\Projects\bitay\NFT\NFT-tq\node_modules\@airgap\beacon-sdk\dist\cjs\utils\generate-uuid.js:52:23)
        at Object.next (D:\Projects\bitay\NFT\NFT-tq\node_modules\@airgap\beacon-sdk\dist\cjs\utils\generate-uuid.js:33:53)
        at fulfilled (D:\Projects\bitay\NFT\NFT-tq\node_modules\@airgap\beacon-sdk\dist\cjs\utils\generate-uuid.js:24:58)

    and code is:

    beacon.js

    import { TezosToolkit } from "@taquito/taquito";
    import { BeaconWallet } from "@taquito/beacon-wallet";
    import { TezosOperationType } from "@airgap/beacon-sdk";
    //import { localStorage } from "localstorage-polyfill";
    import pkg from 'localstorage-polyfill'; //because we are on server-side, browser localstorage must be implemented like this
    const { localStorage } = pkg;
    //check for borwser or server
    if (typeof window !== "undefined") {
        console.log("Rendering on browser")
    } else {
        console.log("Rendering on server");
    }

    const Tezos = new TezosToolkit("https://mainnet-tezos.giganode.io");
    const wallet = new BeaconWallet({ name: "Beacon Docs Taquito" }); // Takes the same arguments as the DAppClient constructor

    Tezos.setWalletProvider(wallet);

    let myAddress = "";

    // This code should be called every time the page is loaded or refreshed to see if the user has already connected to a wallet.
    const activeAccount = await wallet.client.getActiveAccount();
    if (activeAccount) {
        // If defined, the user is connected to a wallet.
        // You can now do an operation request, sign request, or send another permission request to switch wallet
        console.log("Already connected:", activeAccount.address);
        myAddress = activeAccount.address;
    } else {
        await wallet.requestPermissions();
        myAddress = await wallet.getPKH();
        console.log("New connection:", myAddress);
    }

    // At this point we are connected to an account.
    // Let's send a simple transaction to the wallet that sends 1 mutez to ourselves.
    const hash = await wallet.sendOperations([
        {
            kind: TezosOperationType.TRANSACTION,
            destination: myAddress, // Send to ourselves
            amount: "1", // Amount in mutez, the smallest unit in Tezos
        },
    ]);

    console.log("Operation Hash: ", hash);

    package.json

    {
      "name": "nft-tq",
      "version": "1.0.0",
      "description": "",
      "main": "b.js",
      "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1"
      },
      "author": "",
      "license": "ISC",
      "type": "module",
      "dependencies": {
        "@taquito/beacon-wallet": "^9.2.0",
        "@taquito/taquito": "^9.2.0"
      }
    }

    I think it is an issue with Taquito import system. Any help appreciated...

    Vedat Arslan
    Tesekkurler (Thanks)

-- 
ECAD Labs Inc.

**Comment by Innkst** [comment]
This issue was further discussed in https://github.com/ecadlabs/taquito/discussions/965 and update to beacon-sdk v2.2.9 helped.

**Comment by Innkst** [comment]
#882
