### ISSUE TITLE
Draining an unrevealed account doesn't empty it completely on v9.2.0-beta

### ISSUE THREAD

**Issue by priyeshs11** [ecadlabs/taquito#975]
**Description**

DEFAULT_FEE.REVEAL in constants is currently set at 1420, however currently the reveal operation costs only 374 mutez.

 - Version `9.2.0-beta`

This behaviour causes an issue when draining an unrevealed account. As per the docs [here](https://tezostaquito.io/docs/drain_account), it suggests to leave the DEFAULT_FEE.REVEAL amount in the account to accomodate for a reveal operation before emptying an account. Due to the difference in fees set in constants and the actual fees, it leaves a residue amount of 1046 mutez when trying to drain an account.

**Steps To Reproduce**
1. Follow [this](https://tezostaquito.io/docs/drain_account) to drain an unrevealed account.
2. Check the balance of the account that was drained.
3. You will see some amount leftover in the drained account.

**Expected behavior**
The balance should be zero after draining an unrevealed account.

**Additional context**
https://github.com/ecadlabs/taquito/issues/496
https://github.com/ecadlabs/taquito/pull/683/files

The test in the above PR makes a seperate transaction before emptying the account. Thus this issue is not encountered there as the emptying transaction doesn't have to account for the revealing fees because it has already been revealed by that point.  I believe the test isn't testing the right thing which is emptying an unrevealed account.

**Comment by priyeshs11** [comment]
**Update**: It seems like this issue started happening since we upgraded from `7.0.1-beta.0` to `9.2.0-beta`. The reveal operation costed us 1420 on v7 but only 374 on v9.

It seemed trivial to update the `DEFAULT_FEE.REVEAL` to 374 for our calculations, however that doesn't fix it and gives a `proto.009-PsFLoren.contract.balance_too_low` error when submitting the transfer.

```
TezosOperationError {
  errors: [
    {
      kind: 'temporary',
      id: 'proto.009-PsFLoren.contract.balance_too_low',
      contract: 'tz1TZjdpySnLErceDafjHGU5HRZwh1EaTczo',
      balance: '998075',
      amount: '999120'
    }
  ],
  name: 'TezosOperationError',
  id: 'proto.009-PsFLoren.contract.balance_too_low',
  kind: 'temporary',
  message: '(temporary) proto.009-PsFLoren.contract.balance_too_low'
}
```
The actual spendable balance at the time of above error was 1000000 mutez (1XTZ). The above error shows the balance as 998075 which suggests it calculates the balance as 1000000 (actual balance) - 505 (transaction fees) - 1420 (reveal fees  DEFAULT_FEE.REVEAL) = 998075. However, when processing the transaction on `v9.2.0-beta` the actual reveal fee charged is only 374 mutez.

**Comment by roxaneletourneau** [comment]
Thanks @priyeshs11 for reporting this issue and for the details.
The default value has been lowered to 374 mutez in the constants file, which solves the issue. This will be part of release 10.
