### ISSUE TITLE
Update Taquito website to use Granadanet

### ISSUE THREAD

**Issue by roxaneletourneau** [ecadlabs/taquito#993]
The live code examples are using florencenet. We need to update the website to use Granadanet.
For live code examples that make calls to a smart contract, we need to deploy a similar contract on Granadanet and replace the address in the examples.

See: https://github.com/ecadlabs/taquito/issues/822

**Comment by michaelkernaghan** [comment]
Document for managing the transition:  https://docs.google.com/document/d/15rfuo70GkMHiKV_ChrRUbLcxOUo7S6hegQ4pzX21WlQ/edit#heading=h.4i1h3h5p804x

**Comment by michaelkernaghan** [comment]
I will make a folder under /examples that can be used to keep Michelson contract code and Ligo contract code
We can generate new contracts for new protocols from the Ligo scripts.
