### ISSUE TITLE
Can't specify Tezos in docs

### ISSUE THREAD

**Issue by ungarson** [ecadlabs/taquito#996]
This page: https://tezostaquito.io/docs/lambda_view
And I believe every other page has the same issue.

As you can see, Tezos seem to be predefined somewhere else, and it set to florencenet, but I needed to set it to granadanet. I couldn't find Tezos definition nowhere in this page.
<img width="1039" alt="Screen Shot 2021-08-02 at 15 24 50" src="https://user-images.githubusercontent.com/13982759/127861664-f9055e29-ba44-4c0e-a1ad-693e0b6c8160.png">

**Comment by Innkst** [comment]
The current website doesn't support the ability to choose a particular network.
In their own application, users can set up TezosToolkit as required.
This will be covered in #486
